import type { NonDrugItem } from '../types/NonDrugItem';

// Extended non-drug medical supplies database with remaining items (41-200)
export const extendedNonDrugItems: NonDrugItem[] = [
  // Medical Equipment
  {
    id: 'nd-041',
    itemCode: 'ME-001',
    itemName: 'Infusion Pump',
    specification: 'Volumetric, Battery backup, 4 channels',
    sku: 'INF-PUMP-4CH',
    category: 'Medical Equipment',
    supplier: 'MediCare Solutions',
    budgetSource: 'APPL',
    unitPrice: 2500.00,
    stockLevel: 10,
    minLevel: 2,
    maxLevel: 20,
    status: 'Active',
    createdAt: '2024-01-10',
    updatedAt: '2024-12-01'
  },
  {
    id: 'nd-042',
    itemCode: 'ME-002',
    itemName: 'Patient Monitor',
    specification: '5-parameter, Touch screen, Portable',
    sku: 'MON-5PAR-TOUCH',
    category: 'Medical Equipment',
    supplier: 'PharmaCorp Malaysia',
    budgetSource: 'CC/DP',
    unitPrice: 8500.00,
    stockLevel: 5,
    minLevel: 1,
    maxLevel: 10,
    status: 'Active',
    createdAt: '2024-01-15',
    updatedAt: '2024-12-01'
  },
  {
    id: 'nd-043',
    itemCode: 'ME-003',
    itemName: 'Defibrillator',
    specification: 'Biphasic, AED mode, Battery operated',
    sku: 'DEF-BIP-AED',
    category: 'Medical Equipment',
    supplier: 'BioPharm Solutions',
    budgetSource: 'APPL',
    unitPrice: 12000.00,
    stockLevel: 3,
    minLevel: 1,
    maxLevel: 6,
    status: 'Active',
    createdAt: '2024-01-20',
    updatedAt: '2024-12-01'
  },
  {
    id: 'nd-044',
    itemCode: 'ME-004',
    itemName: 'Ventilator',
    specification: 'ICU grade, Invasive/Non-invasive, Touch screen',
    sku: 'VENT-ICU-TOUCH',
    category: 'Medical Equipment',
    supplier: 'Global Medical',
    budgetSource: 'CC/DP',
    unitPrice: 45000.00,
    stockLevel: 2,
    minLevel: 1,
    maxLevel: 4,
    status: 'Active',
    createdAt: '2024-02-01',
    updatedAt: '2024-12-01'
  },
  {
    id: 'nd-045',
    itemCode: 'ME-005',
    itemName: 'Ultrasound Machine',
    specification: 'Portable, Color Doppler, 3 probes',
    sku: 'US-PORT-3PROBE',
    category: 'Medical Equipment',
    supplier: 'Prime Health Corp',
    budgetSource: 'APPL',
    unitPrice: 25000.00,
    stockLevel: 1,
    minLevel: 1,
    maxLevel: 2,
    status: 'Active',
    createdAt: '2024-02-05',
    updatedAt: '2024-12-01'
  },

  // Cleaning & Disinfection
  {
    id: 'nd-046',
    itemCode: 'CD-001',
    itemName: 'Alcohol 70% Solution',
    specification: '70% Isopropyl alcohol, 500ml bottle',
    sku: 'ALC-70-500ML',
    category: 'Cleaning & Disinfection',
    supplier: 'MediSupply Sdn Bhd',
    budgetSource: 'APPL',
    unitPrice: 8.50,
    stockLevel: 200,
    minLevel: 40,
    maxLevel: 400,
    status: 'Active',
    createdAt: '2024-01-12',
    updatedAt: '2024-12-01'
  },
  {
    id: 'nd-047',
    itemCode: 'CD-002',
    itemName: 'Chlorhexidine 4% Solution',
    specification: '4% Chlorhexidine gluconate, 500ml bottle',
    sku: 'CHX-4-500ML',
    category: 'Cleaning & Disinfection',
    supplier: 'BioPharm Solutions',
    budgetSource: 'CC/DP',
    unitPrice: 12.50,
    stockLevel: 150,
    minLevel: 30,
    maxLevel: 300,
    status: 'Active',
    createdAt: '2024-01-15',
    updatedAt: '2024-12-01'
  },
  {
    id: 'nd-048',
    itemCode: 'CD-003',
    itemName: 'Sodium Hypochlorite 5%',
    specification: '5% Bleach solution, 1 liter bottle',
    sku: 'BLEACH-5-1L',
    category: 'Cleaning & Disinfection',
    supplier: 'Global Medical',
    budgetSource: 'APPL',
    unitPrice: 6.50,
    stockLevel: 100,
    minLevel: 20,
    maxLevel: 200,
    status: 'Active',
    createdAt: '2024-01-18',
    updatedAt: '2024-12-01'
  },
  {
    id: 'nd-049',
    itemCode: 'CD-004',
    itemName: 'Disinfectant Wipes',
    specification: 'Quaternary ammonium, 100 wipes/pack',
    sku: 'WIPES-QA-100',
    category: 'Cleaning & Disinfection',
    supplier: 'Prime Health Corp',
    budgetSource: 'CC/DP',
    unitPrice: 15.00,
    stockLevel: 300,
    minLevel: 60,
    maxLevel: 600,
    status: 'Active',
    createdAt: '2024-02-01',
    updatedAt: '2024-12-01'
  },
  {
    id: 'nd-050',
    itemCode: 'CD-005',
    itemName: 'Surface Disinfectant Spray',
    specification: 'Hospital grade, 500ml spray bottle',
    sku: 'SPRAY-HOSP-500ML',
    category: 'Cleaning & Disinfection',
    supplier: 'MediCare Solutions',
    budgetSource: 'APPL',
    unitPrice: 18.00,
    stockLevel: 120,
    minLevel: 24,
    maxLevel: 240,
    status: 'Active',
    createdAt: '2024-02-05',
    updatedAt: '2024-12-01'
  },

  // Personal Protective Equipment
  {
    id: 'nd-051',
    itemCode: 'PPE-001',
    itemName: 'N95 Respirator Mask',
    specification: 'N95, Disposable, 20 pieces/box',
    sku: 'N95-20BOX',
    category: 'Personal Protective Equipment',
    supplier: 'PharmaCorp Malaysia',
    budgetSource: 'APPL',
    unitPrice: 35.00,
    stockLevel: 500,
    minLevel: 100,
    maxLevel: 1000,
    status: 'Active',
    createdAt: '2024-01-10',
    updatedAt: '2024-12-01'
  },
  {
    id: 'nd-052',
    itemCode: 'PPE-002',
    itemName: 'Face Shield',
    specification: 'Clear plastic, Adjustable headband, 10 pieces/box',
    sku: 'FSH-CLEAR-10',
    category: 'Personal Protective Equipment',
    supplier: 'BioPharm Solutions',
    budgetSource: 'CC/DP',
    unitPrice: 25.00,
    stockLevel: 200,
    minLevel: 40,
    maxLevel: 400,
    status: 'Active',
    createdAt: '2024-01-15',
    updatedAt: '2024-12-01'
  },
  {
    id: 'nd-053',
    itemCode: 'PPE-003',
    itemName: 'Disposable Gown',
    specification: 'Non-woven, Water resistant, 50 pieces/box',
    sku: 'GOWN-NW-50',
    category: 'Personal Protective Equipment',
    supplier: 'Global Medical',
    budgetSource: 'APPL',
    unitPrice: 45.00,
    stockLevel: 150,
    minLevel: 30,
    maxLevel: 300,
    status: 'Active',
    createdAt: '2024-01-20',
    updatedAt: '2024-12-01'
  },
  {
    id: 'nd-054',
    itemCode: 'PPE-004',
    itemName: 'Shoe Covers',
    specification: 'Disposable, Non-slip, 100 pairs/box',
    sku: 'SHOE-COV-100',
    category: 'Personal Protective Equipment',
    supplier: 'Prime Health Corp',
    budgetSource: 'CC/DP',
    unitPrice: 12.00,
    stockLevel: 300,
    minLevel: 60,
    maxLevel: 600,
    status: 'Active',
    createdAt: '2024-02-01',
    updatedAt: '2024-12-01'
  },
  {
    id: 'nd-055',
    itemCode: 'PPE-005',
    itemName: 'Hair Cover',
    specification: 'Disposable, Non-woven, 100 pieces/box',
    sku: 'HAIR-COV-100',
    category: 'Personal Protective Equipment',
    supplier: 'MediSupply Sdn Bhd',
    budgetSource: 'APPL',
    unitPrice: 8.50,
    stockLevel: 400,
    minLevel: 80,
    maxLevel: 800,
    status: 'Active',
    createdAt: '2024-02-05',
    updatedAt: '2024-12-01'
  },

  // Laboratory Equipment
  {
    id: 'nd-056',
    itemCode: 'LE-001',
    itemName: 'Microscope',
    specification: 'Compound, 1000x magnification, LED illumination',
    sku: 'MICRO-COMP-1000X',
    category: 'Laboratory Equipment',
    supplier: 'MediCare Solutions',
    budgetSource: 'APPL',
    unitPrice: 3500.00,
    stockLevel: 5,
    minLevel: 1,
    maxLevel: 10,
    status: 'Active',
    createdAt: '2024-01-10',
    updatedAt: '2024-12-01'
  },
  {
    id: 'nd-057',
    itemCode: 'LE-002',
    itemName: 'Centrifuge',
    specification: 'Benchtop, 4000 RPM, 12 tubes capacity',
    sku: 'CENT-BT-4K-12',
    category: 'Laboratory Equipment',
    supplier: 'PharmaCorp Malaysia',
    budgetSource: 'CC/DP',
    unitPrice: 2800.00,
    stockLevel: 3,
    minLevel: 1,
    maxLevel: 6,
    status: 'Active',
    createdAt: '2024-01-15',
    updatedAt: '2024-12-01'
  },
  {
    id: 'nd-058',
    itemCode: 'LE-003',
    itemName: 'Incubator',
    specification: 'CO2, 37°C, 6 shelves, Digital display',
    sku: 'INC-CO2-37C-6S',
    category: 'Laboratory Equipment',
    supplier: 'BioPharm Solutions',
    budgetSource: 'APPL',
    unitPrice: 8500.00,
    stockLevel: 2,
    minLevel: 1,
    maxLevel: 4,
    status: 'Active',
    createdAt: '2024-01-20',
    updatedAt: '2024-12-01'
  },
  {
    id: 'nd-059',
    itemCode: 'LE-004',
    itemName: 'Autoclave',
    specification: 'Steam sterilizer, 25L capacity, Digital timer',
    sku: 'AUTO-25L-DIG',
    category: 'Laboratory Equipment',
    supplier: 'Global Medical',
    budgetSource: 'CC/DP',
    unitPrice: 12000.00,
    stockLevel: 2,
    minLevel: 1,
    maxLevel: 4,
    status: 'Active',
    createdAt: '2024-02-01',
    updatedAt: '2024-12-01'
  },
  {
    id: 'nd-060',
    itemCode: 'LE-005',
    itemName: 'pH Meter',
    specification: 'Portable, Digital, 0.01 accuracy',
    sku: 'PH-DIG-001',
    category: 'Laboratory Equipment',
    supplier: 'Prime Health Corp',
    budgetSource: 'APPL',
    unitPrice: 450.00,
    stockLevel: 8,
    minLevel: 2,
    maxLevel: 16,
    status: 'Active',
    createdAt: '2024-02-05',
    updatedAt: '2024-12-01'
  },

  // Continue with more categories to reach 200 total...
  // I'll add the remaining items in the next part
];
