import type {
  StockItem,
  PurchaseOrder,
  WardRequisition,
  GoodsReceivedNote,
  PharmacySubStoreStats,
} from '../types/PharmacySubStore';

const today = new Date();

// Mock Stock Items
export const mockStockItems: StockItem[] = [
  {
    id: 'STK001',
    itemCode: 'MED-001',
    itemName: 'Paracetamol',
    genericName: 'Paracetamol',
    category: 'drug',
    drugClass: 'Analgesic/Antipyretic',
    therapeuticClass: 'Pain Relief',
    strength: '500mg',
    dosageForm: 'Tablet',
    packSize: 1000,
    unitOfMeasure: 'Tablets',
    currentStock: 25000,
    availableStock: 23500,
    reservedStock: 1500,
    reorderLevel: 15000,
    minimumStock: 10000,
    maximumStock: 50000,
    economicOrderQuantity: 20000,
    status: 'adequate',
    daysToStockout: 45,
    preferredSupplier: 'Pharmaniaga Berhad',
    alternateSuppliers: ['Duopharma', 'CCM Pharmaceuticals'],
    lastPurchasePrice: 0.05,
    averagePrice: 0.05,
    standardCost: 0.05,
    storageLocation: 'General Store - Zone A',
    binLocation: 'A-12-03',
    batches: [
      {
        batchNumber: 'PARA-2024-001',
        expiryDate: new Date('2027-01-31'),
        quantity: 15000,
        receivedDate: new Date('2024-11-01'),
        grnNumber: 'GRN-2024-1001',
        supplierBatchNumber: 'PHG-PARA-2024-Q4',
        manufacturingDate: new Date('2024-10-15'),
        costPrice: 0.05,
      },
      {
        batchNumber: 'PARA-2024-002',
        expiryDate: new Date('2027-03-31'),
        quantity: 10000,
        receivedDate: new Date('2024-12-15'),
        grnNumber: 'GRN-2024-1245',
        supplierBatchNumber: 'PHG-PARA-2024-Q4B',
        manufacturingDate: new Date('2024-11-20'),
        costPrice: 0.05,
      },
    ],
    oldestBatchExpiry: new Date('2027-01-31'),
    isControlled: false,
    isHighValue: false,
    isColdChain: false,
    isNarcotic: false,
    averageMonthlyConsumption: 18000,
    lastIssueDate: new Date(today.setHours(10, 30, 0)),
  },
  // Additional low/near-expiry/slow-moving items to reach 10 per tab
  {
    id: 'STK006',
    itemCode: 'MED-006',
    itemName: 'Atorvastatin',
    genericName: 'Atorvastatin Calcium',
    category: 'drug',
    strength: '40mg',
    dosageForm: 'Tablet',
    packSize: 1000,
    unitOfMeasure: 'Tablets',
    currentStock: 300,
    availableStock: 280,
    reservedStock: 20,
    reorderLevel: 800,
    minimumStock: 600,
    maximumStock: 5000,
    economicOrderQuantity: 2000,
    status: 'low',
    daysToStockout: 14,
    preferredSupplier: 'Duopharma',
    alternateSuppliers: ['Pharmaniaga'],
    lastPurchasePrice: 0.6,
    averagePrice: 0.6,
    standardCost: 0.6,
    storageLocation: 'Zone B',
    binLocation: 'B-12-02',
    batches: [
      { batchNumber: 'ATOR-24-01', expiryDate: new Date('2025-03-15'), quantity: 300, receivedDate: new Date('2024-11-01'), grnNumber: 'GRN-2024-1401', supplierBatchNumber: 'ATOR-24Q4', costPrice: 0.6 },
    ],
    oldestBatchExpiry: new Date('2025-03-15'),
    isControlled: false,
    isHighValue: false,
    isColdChain: false,
    isNarcotic: false,
    averageMonthlyConsumption: 50,
  },
  {
    id: 'STK007',
    itemCode: 'MED-007',
    itemName: 'Omeprazole',
    genericName: 'Omeprazole',
    category: 'drug',
    strength: '20mg',
    dosageForm: 'Capsule',
    packSize: 500,
    unitOfMeasure: 'Capsules',
    currentStock: 100,
    availableStock: 90,
    reservedStock: 10,
    reorderLevel: 600,
    minimumStock: 400,
    maximumStock: 5000,
    economicOrderQuantity: 2000,
    status: 'critical',
    daysToStockout: 7,
    preferredSupplier: 'CCM',
    alternateSuppliers: [],
    lastPurchasePrice: 0.35,
    averagePrice: 0.35,
    standardCost: 0.35,
    storageLocation: 'Zone B',
    binLocation: 'B-10-04',
    batches: [
      { batchNumber: 'OMEP-24-08', expiryDate: new Date('2025-02-28'), quantity: 100, receivedDate: new Date('2024-10-20'), grnNumber: 'GRN-2024-1220', supplierBatchNumber: 'OMEP-Q4', costPrice: 0.35 },
    ],
    oldestBatchExpiry: new Date('2025-02-28'),
    isControlled: false,
    isHighValue: false,
    isColdChain: false,
    isNarcotic: false,
    averageMonthlyConsumption: 40,
  },
  {
    id: 'STK008',
    itemCode: 'MED-008',
    itemName: 'Bisoprolol',
    genericName: 'Bisoprolol Fumarate',
    category: 'drug',
    strength: '5mg',
    dosageForm: 'Tablet',
    packSize: 1000,
    unitOfMeasure: 'Tablets',
    currentStock: 500,
    availableStock: 480,
    reservedStock: 20,
    reorderLevel: 1200,
    minimumStock: 800,
    maximumStock: 6000,
    economicOrderQuantity: 2000,
    status: 'low',
    daysToStockout: 20,
    preferredSupplier: 'Pharmaniaga',
    alternateSuppliers: [],
    lastPurchasePrice: 0.55,
    averagePrice: 0.55,
    standardCost: 0.55,
    storageLocation: 'Zone A',
    binLocation: 'A-08-01',
    batches: [
      { batchNumber: 'BISO-24-10', expiryDate: new Date('2025-04-10'), quantity: 500, receivedDate: new Date('2024-12-10'), grnNumber: 'GRN-2024-1502', supplierBatchNumber: 'BISO-Q4', costPrice: 0.55 },
    ],
    oldestBatchExpiry: new Date('2025-04-10'),
    isControlled: false,
    isHighValue: false,
    isColdChain: false,
    isNarcotic: false,
    averageMonthlyConsumption: 45,
  },
  {
    id: 'STK009',
    itemCode: 'MED-009',
    itemName: 'Cefuroxime',
    genericName: 'Cefuroxime Axetil',
    category: 'drug',
    strength: '250mg',
    dosageForm: 'Tablet',
    packSize: 1000,
    unitOfMeasure: 'Tablets',
    currentStock: 0,
    availableStock: 0,
    reservedStock: 0,
    reorderLevel: 2000,
    minimumStock: 1500,
    maximumStock: 8000,
    economicOrderQuantity: 4000,
    status: 'out-of-stock',
    daysToStockout: 0,
    preferredSupplier: 'CCM',
    alternateSuppliers: ['Duopharma'],
    lastPurchasePrice: 0.95,
    averagePrice: 0.95,
    standardCost: 0.95,
    storageLocation: 'Zone C',
    binLocation: 'C-02-06',
    batches: [],
    isControlled: false,
    isHighValue: false,
    isColdChain: false,
    isNarcotic: false,
    averageMonthlyConsumption: 30,
  },
  {
    id: 'STK010',
    itemCode: 'MED-010',
    itemName: 'Metformin',
    genericName: 'Metformin Hydrochloride',
    category: 'drug',
    strength: '500mg',
    dosageForm: 'Tablet',
    packSize: 1000,
    unitOfMeasure: 'Tablets',
    currentStock: 700,
    availableStock: 680,
    reservedStock: 20,
    reorderLevel: 5000,
    minimumStock: 3000,
    maximumStock: 12000,
    economicOrderQuantity: 6000,
    status: 'adequate',
    daysToStockout: 90,
    preferredSupplier: 'Pharmaniaga',
    alternateSuppliers: [],
    lastPurchasePrice: 0.15,
    averagePrice: 0.15,
    standardCost: 0.15,
    storageLocation: 'Zone A',
    binLocation: 'A-02-02',
    batches: [
      { batchNumber: 'MET-24-11', expiryDate: new Date('2025-02-15'), quantity: 700, receivedDate: new Date('2024-12-28'), grnNumber: 'GRN-2024-1601', supplierBatchNumber: 'MET-Q4', costPrice: 0.15 },
    ],
    oldestBatchExpiry: new Date('2025-02-15'),
    isControlled: false,
    isHighValue: false,
    isColdChain: false,
    isNarcotic: false,
    averageMonthlyConsumption: 55,
  },
  {
    id: 'STK002',
    itemCode: 'MED-002',
    itemName: 'Insulin Glargine',
    genericName: 'Insulin Glargine',
    category: 'drug',
    drugClass: 'Long-acting Insulin',
    therapeuticClass: 'Antidiabetic',
    strength: '100 IU/mL',
    dosageForm: 'Injection',
    packSize: 1,
    unitOfMeasure: 'Vial (10mL)',
    currentStock: 45,
    availableStock: 38,
    reservedStock: 7,
    reorderLevel: 50,
    minimumStock: 30,
    maximumStock: 120,
    economicOrderQuantity: 60,
    status: 'low',
    daysToStockout: 12,
    preferredSupplier: 'Sanofi Malaysia',
    alternateSuppliers: [],
    lastPurchasePrice: 85.50,
    averagePrice: 87.00,
    standardCost: 85.50,
    storageLocation: 'Cold Room 1',
    binLocation: 'CR1-B-05',
    batches: [
      {
        batchNumber: 'INS-2024-567',
        expiryDate: new Date('2025-12-31'),
        quantity: 45,
        receivedDate: new Date('2024-09-15'),
        grnNumber: 'GRN-2024-0889',
        supplierBatchNumber: 'SNF-INS-2024-M09',
        manufacturingDate: new Date('2024-08-01'),
        costPrice: 85.50,
      },
    ],
    oldestBatchExpiry: new Date('2025-12-31'),
    isControlled: false,
    isHighValue: true,
    isColdChain: true,
    isNarcotic: false,
    averageMonthlyConsumption: 120,
    lastIssueDate: new Date(today.setHours(9, 0, 0)),
    notes: 'Cold chain item - maintain 2-8°C',
  },
  {
    id: 'STK003',
    itemCode: 'MED-003',
    itemName: 'Morphine Sulphate',
    genericName: 'Morphine Sulphate',
    category: 'drug',
    drugClass: 'Opioid Analgesic',
    therapeuticClass: 'Strong Analgesic',
    strength: '10mg/mL',
    dosageForm: 'Injection',
    packSize: 10,
    unitOfMeasure: 'Ampoules',
    currentStock: 150,
    availableStock: 145,
    reservedStock: 5,
    reorderLevel: 100,
    minimumStock: 80,
    maximumStock: 300,
    economicOrderQuantity: 100,
    status: 'adequate',
    daysToStockout: 60,
    preferredSupplier: 'Duopharma Biotech',
    alternateSuppliers: ['Pharmaniaga'],
    lastPurchasePrice: 3.50,
    averagePrice: 3.50,
    standardCost: 3.50,
    storageLocation: 'Controlled Drug Room',
    binLocation: 'CD-A-02',
    batches: [
      {
        batchNumber: 'MORPH-2024-088',
        expiryDate: new Date('2026-08-31'),
        quantity: 150,
        receivedDate: new Date('2024-10-05'),
        grnNumber: 'GRN-2024-0998',
        supplierBatchNumber: 'DUO-MORPH-2024-Q3',
        manufacturingDate: new Date('2024-09-10'),
        costPrice: 3.50,
      },
    ],
    oldestBatchExpiry: new Date('2026-08-31'),
    isControlled: true,
    isHighValue: true,
    isColdChain: false,
    isNarcotic: true,
    averageMonthlyConsumption: 80,
    lastIssueDate: new Date(today.setHours(8, 15, 0)),
    notes: 'Controlled substance - double checking required',
  },
  {
    id: 'STK004',
    itemCode: 'CONS-001',
    itemName: 'Surgical Gloves (Size 7.5)',
    genericName: 'Sterile Latex Gloves',
    category: 'consumable',
    packSize: 50,
    unitOfMeasure: 'Pairs',
    currentStock: 120,
    availableStock: 95,
    reservedStock: 25,
    reorderLevel: 500,
    minimumStock: 300,
    maximumStock: 2000,
    economicOrderQuantity: 1000,
    status: 'critical',
    daysToStockout: 8,
    preferredSupplier: 'Top Glove Corporation',
    alternateSuppliers: ['Supermax', 'Hartalega'],
    lastPurchasePrice: 25.00,
    averagePrice: 26.50,
    standardCost: 25.00,
    storageLocation: 'General Store - Zone C',
    binLocation: 'C-08-15',
    batches: [
      {
        batchNumber: 'GLOVE-2024-789',
        expiryDate: new Date('2029-12-31'),
        quantity: 120,
        receivedDate: new Date('2024-12-10'),
        grnNumber: 'GRN-2024-1298',
        supplierBatchNumber: 'TG-GLOVE-2024-W50',
        manufacturingDate: new Date('2024-11-25'),
        costPrice: 25.00,
      },
    ],
    oldestBatchExpiry: new Date('2029-12-31'),
    isControlled: false,
    isHighValue: false,
    isColdChain: false,
    isNarcotic: false,
    averageMonthlyConsumption: 500,
    lastIssueDate: new Date(today.setHours(7, 45, 0)),
    notes: 'High demand item - urgent reorder required',
  },
  {
    id: 'STK005',
    itemCode: 'MED-005',
    itemName: 'Amoxicillin',
    genericName: 'Amoxicillin Trihydrate',
    category: 'drug',
    drugClass: 'Antibiotic',
    therapeuticClass: 'Beta-Lactam Antibiotic',
    strength: '500mg',
    dosageForm: 'Capsule',
    packSize: 100,
    unitOfMeasure: 'Capsules',
    currentStock: 0,
    availableStock: 0,
    reservedStock: 0,
    reorderLevel: 5000,
    minimumStock: 3000,
    maximumStock: 15000,
    economicOrderQuantity: 8000,
    status: 'out-of-stock',
    daysToStockout: 0,
    preferredSupplier: 'CCM Pharmaceuticals',
    alternateSuppliers: ['Pharmaniaga', 'Duopharma'],
    lastPurchasePrice: 0.30,
    averagePrice: 0.32,
    standardCost: 0.30,
    storageLocation: 'General Store - Zone B',
    binLocation: 'B-05-10',
    batches: [],
    isControlled: false,
    isHighValue: false,
    isColdChain: false,
    isNarcotic: false,
    averageMonthlyConsumption: 8500,
    lastIssueDate: new Date('2025-01-03'),
    notes: 'OUT OF STOCK - Emergency PO raised',
  },
];

// Mock Purchase Orders
export const mockPurchaseOrders: PurchaseOrder[] = [
  {
    id: 'PO001',
    poNumber: 'PO-2025-0001',
    poDate: new Date('2025-01-02'),
    supplierName: 'Pharmaniaga Berhad',
    supplierCode: 'SUP-001',
    supplierContact: '03-7956 2200',
    supplierAddress: 'Level 8, Bangunan TH Selborn, Jalan Tun Razak, KL',
    status: 'ordered',
    priority: 'routine',
    totalAmount: 125000.00,
    gstAmount: 0,
    grandTotal: 125000.00,
    paymentTerms: '30 days from invoice date',
    items: [
      {
        id: 'POI001-1',
        itemCode: 'MED-001',
        itemName: 'Paracetamol 500mg Tablet',
        strength: '500mg',
        packSize: 1000,
        orderedQuantity: 50000,
        receivedQuantity: 0,
        outstandingQuantity: 50000,
        unitPrice: 0.05,
        totalPrice: 2500.00,
      },
      {
        id: 'POI001-2',
        itemCode: 'MED-010',
        itemName: 'Metformin 500mg Tablet',
        strength: '500mg',
        packSize: 1000,
        orderedQuantity: 80000,
        receivedQuantity: 0,
        outstandingQuantity: 80000,
        unitPrice: 0.15,
        totalPrice: 12000.00,
      },
    ],
    expectedDeliveryDate: new Date('2025-01-20'),
    deliveryAddress: 'Pharmacy Sub Store, Hospital Lawas, Sarawak',
    requestedBy: 'Pharmacist Hassan',
    approvedBy: 'Chief Pharmacist Dr. Lim',
    approvedDate: new Date('2025-01-03'),
    receivedItems: 0,
    totalItems: 2,
    partiallyReceived: false,
    quotationNumber: 'QT-2024-1234',
  },
  {
    id: 'PO002',
    poNumber: 'PO-2025-0002',
    poDate: new Date('2025-01-05'),
    supplierName: 'CCM Pharmaceuticals',
    supplierCode: 'SUP-003',
    supplierContact: '03-8023 8000',
    supplierAddress: 'Lot 2-5, Jalan P/8, Kawasan MIEL, Shah Alam',
    status: 'approved',
    priority: 'urgent',
    totalAmount: 24000.00,
    gstAmount: 0,
    grandTotal: 24000.00,
    paymentTerms: '30 days from invoice date',
    items: [
      {
        id: 'POI002-1',
        itemCode: 'MED-005',
        itemName: 'Amoxicillin 500mg Capsule',
        strength: '500mg',
        packSize: 100,
        orderedQuantity: 80000,
        receivedQuantity: 0,
        outstandingQuantity: 80000,
        unitPrice: 0.30,
        totalPrice: 24000.00,
      },
    ],
    expectedDeliveryDate: new Date('2025-01-10'),
    deliveryAddress: 'Pharmacy Sub Store, Hospital Lawas, Sarawak',
    requestedBy: 'Pharmacist Sarah',
    approvedBy: 'Chief Pharmacist Dr. Lim',
    approvedDate: new Date('2025-01-06'),
    receivedItems: 0,
    totalItems: 1,
    partiallyReceived: false,
    quotationNumber: 'QT-2024-1567',
    notes: 'Urgent order - stock out situation',
  },
];

// Mock Ward Requisitions
export const mockWardRequisitions: WardRequisition[] = [
  {
    id: 'REQ001',
    requisitionNumber: 'REQ-2025-0012',
    requisitionDate: new Date(today.setHours(8, 0, 0)),
    wardName: 'General Ward',
    wardCode: 'GW-01',
    requestedBy: 'Staff Nurse Fatimah',
    contactNumber: '082-123456 ext 201',
    status: 'pending',
    priority: 'routine',
    items: [
      {
        id: 'REQI001-1',
        itemCode: 'MED-001',
        itemName: 'Paracetamol 500mg',
        strength: '500mg',
        requestedQuantity: 500,
        approvedQuantity: 0,
        issuedQuantity: 0,
        unitOfMeasure: 'Tablets',
        currentStock: 25000,
        available: true,
      },
      {
        id: 'REQI001-2',
        itemCode: 'CONS-001',
        itemName: 'Surgical Gloves (Size 7.5)',
        requestedQuantity: 10,
        approvedQuantity: 0,
        issuedQuantity: 0,
        unitOfMeasure: 'Pairs',
        currentStock: 120,
        available: true,
      },
    ],
    notes: 'Regular weekly requisition',
  },
  {
    id: 'REQ002',
    requisitionNumber: 'REQ-2025-0013',
    requisitionDate: new Date(today.setHours(9, 30, 0)),
    wardName: 'Emergency & Trauma',
    wardCode: 'EM-01',
    requestedBy: 'Dr. Kumar',
    contactNumber: '082-123456 ext 101',
    status: 'approved',
    priority: 'stat',
    items: [
      {
        id: 'REQI002-1',
        itemCode: 'MED-003',
        itemName: 'Morphine Sulphate 10mg/mL',
        strength: '10mg/mL',
        requestedQuantity: 10,
        approvedQuantity: 10,
        issuedQuantity: 0,
        unitOfMeasure: 'Ampoules',
        currentStock: 150,
        available: true,
      },
    ],
    processedBy: 'Pharmacist John',
    processedDate: new Date(today.setHours(9, 45, 0)),
    approvedBy: 'Pharmacist John',
    approvedDate: new Date(today.setHours(9, 45, 0)),
    notes: 'STAT order for emergency patient',
  },
  {
    id: 'REQ003',
    requisitionNumber: 'REQ-2025-0014',
    requisitionDate: new Date(today.setHours(10, 15, 0)),
    wardName: 'Paediatric Ward',
    wardCode: 'PW-01',
    requestedBy: 'Staff Nurse Aisha',
    contactNumber: '082-123456 ext 301',
    status: 'rejected',
    priority: 'routine',
    items: [
      {
        id: 'REQI003-1',
        itemCode: 'MED-005',
        itemName: 'Amoxicillin 500mg',
        strength: '500mg',
        requestedQuantity: 200,
        approvedQuantity: 0,
        issuedQuantity: 0,
        unitOfMeasure: 'Capsules',
        currentStock: 0,
        available: false,
      },
    ],
    processedBy: 'Pharmacist Sarah',
    processedDate: new Date(today.setHours(10, 25, 0)),
    rejectionReason: 'Item out of stock. PO raised. Expected delivery 10/01/2025',
    notes: 'Alternative item suggested: Amoxicillin Suspension',
  },
];

// Mock Statistics
export const mockPharmacySubStoreStats: PharmacySubStoreStats = {
  totalStockItems: 1245,
  totalStockValue: 2458750.00,
  lowStockItems: 45,
  criticalStockItems: 12,
  outOfStockItems: 8,
  
  expiredItems: 3,
  nearExpiryItems: 28,
  expiryValueAtRisk: 15680.00,
  
  pendingPOs: 12,
  awaitingDelivery: 8,
  totalPOValuePending: 485000.00,
  
  pendingRequisitions: 15,
  todaysRequisitions: 23,
  averageProcessingTime: 18,
  
  receiptsToday: 3,
  issuesToday: 18,
  requisitionsProcessed: 8,
  
  monthlyPurchaseValue: 1250000.00,
  monthlyIssueValue: 980000.00,
  
  stockTurnoverRatio: 4.2,
  fillRate: 92.5,
  
  coldChainItems: 45,
  coldChainStockValue: 125000.00,
};

export function getStockItems(): StockItem[] {
  return mockStockItems;
}

export function getPurchaseOrders(): PurchaseOrder[] {
  return mockPurchaseOrders;
}

export function getWardRequisitions(): WardRequisition[] {
  return mockWardRequisitions;
}

export function getPharmacySubStoreStats(): PharmacySubStoreStats {
  return mockPharmacySubStoreStats;
}

