import type {
  ImagingOrder,
  DICOMStudy,
  RadiologyReport,
  RadiologyEquipment,
  RadiologyStats,
  Radiologist,
  ImagingProtocol,
} from '../types/Radiology';

const today = new Date();

// Mock Imaging Orders
export const mockImagingOrders: ImagingOrder[] = [
  {
    id: 'IMG001',
    orderNumber: 'RAD-2025-0001',
    orderDate: new Date(today.setHours(7, 30, 0)),
    patientName: 'Ahmad bin Hassan',
    patientIC: '750615-10-5234',
    patientMRN: 'MRN-2024-00123',
    dateOfBirth: new Date('1975-06-15'),
    age: 49,
    gender: 'Male',
    modality: 'X-Ray',
    studyType: 'Chest X-Ray (PA & Lateral)',
    bodyPart: 'Chest',
    clinicalHistory: 'Chronic cough for 3 weeks',
    clinicalIndication: 'Rule out pneumonia, TB',
    orderingDepartment: 'General Medicine',
    orderingPhysician: 'Dr. Lim Wei Ming',
    priority: 'routine',
    scheduledDate: today,
    scheduledTime: '09:00',
    status: 'completed',
    performedBy: 'Radiographer Siti',
    performedAt: new Date(today.setHours(9, 15, 0)),
    contrast: false,
    sedation: false,
    isolation: false,
    portable: false,
    notes: 'Patient cooperative',
  },
  {
    id: 'IMG002',
    orderNumber: 'RAD-2025-0002',
    orderDate: new Date(today.setHours(8, 0, 0)),
    patientName: 'Siti Nurhaliza binti Abdullah',
    patientIC: '880824-08-2341',
    patientMRN: 'MRN-2024-00456',
    dateOfBirth: new Date('1988-08-24'),
    age: 36,
    gender: 'Female',
    modality: 'CT',
    studyType: 'CT Brain without contrast',
    bodyPart: 'Brain',
    clinicalHistory: 'Sudden onset severe headache with vomiting',
    clinicalIndication: 'Rule out intracranial hemorrhage, stroke',
    priorStudies: ['CT Brain 2023-12-15'],
    orderingDepartment: 'Emergency & Trauma',
    orderingPhysician: 'Dr. Kumar Velan',
    priority: 'stat',
    scheduledDate: today,
    scheduledTime: '10:00',
    status: 'in-progress',
    contrast: false,
    sedation: false,
    isolation: false,
    portable: false,
    pregnancyScreening: true,
    pregnancyStatus: 'negative',
    notes: 'STAT order - patient in emergency',
  },
  {
    id: 'IMG003',
    orderNumber: 'RAD-2025-0003',
    orderDate: new Date(today.setHours(8, 30, 0)),
    patientName: 'Rajendran s/o Suppiah',
    patientIC: '680405-05-3456',
    patientMRN: 'MRN-2024-00789',
    dateOfBirth: new Date('1968-04-05'),
    age: 56,
    gender: 'Male',
    modality: 'X-Ray',
    studyType: 'Right Knee AP & Lateral',
    bodyPart: 'Knee',
    laterality: 'Right',
    clinicalHistory: 'Fall 2 days ago, persistent pain and swelling',
    clinicalIndication: 'Rule out fracture, degenerative changes',
    orderingDepartment: 'Orthopedics',
    orderingPhysician: 'Dr. Chan Kok Wai',
    priority: 'urgent',
    scheduledDate: today,
    scheduledTime: '11:00',
    status: 'scheduled',
    contrast: false,
    sedation: false,
    isolation: false,
    portable: false,
  },
  {
    id: 'IMG004',
    orderNumber: 'RAD-2025-0004',
    orderDate: new Date(today.setHours(9, 0, 0)),
    patientName: 'Fatimah binti Ismail',
    patientIC: '920518-14-4567',
    patientMRN: 'MRN-2024-01012',
    dateOfBirth: new Date('1992-05-18'),
    age: 32,
    gender: 'Female',
    modality: 'Ultrasound',
    studyType: 'Obstetric Ultrasound (Second Trimester)',
    bodyPart: 'Abdomen/Pelvis',
    clinicalHistory: '24 weeks pregnant, routine antenatal scan',
    clinicalIndication: 'Fetal biometry, anomaly scan',
    orderingDepartment: 'Obstetrics',
    orderingPhysician: 'Dr. Nora Abdullah',
    priority: 'routine',
    scheduledDate: today,
    scheduledTime: '14:00',
    status: 'scheduled',
    contrast: false,
    sedation: false,
    isolation: false,
    portable: false,
    pregnancyScreening: false,
    pregnancyStatus: 'positive',
  },
  {
    id: 'IMG005',
    orderNumber: 'RAD-2025-0005',
    orderDate: new Date(today.setHours(9, 30, 0)),
    patientName: 'Wong Ah Meng',
    patientIC: '650920-10-6789',
    patientMRN: 'MRN-2024-01234',
    dateOfBirth: new Date('1965-09-20'),
    age: 59,
    gender: 'Male',
    modality: 'CT',
    studyType: 'CT Abdomen & Pelvis with IV contrast',
    bodyPart: 'Abdomen/Pelvis',
    clinicalHistory: 'Abdominal pain, weight loss, jaundice',
    clinicalIndication: 'Evaluate for pancreatic mass, liver lesions',
    priorStudies: ['Ultrasound Abdomen 2025-01-02'],
    orderingDepartment: 'General Surgery',
    orderingPhysician: 'Dr. Azmi Rahman',
    priority: 'urgent',
    scheduledDate: today,
    scheduledTime: '15:00',
    status: 'scheduled',
    contrast: true,
    contrastType: 'Iodinated IV contrast',
    sedation: false,
    isolation: false,
    portable: false,
    notes: 'Renal function: Cr 88 (normal), eGFR >60. Consent obtained.',
  },
  {
    id: 'IMG006',
    orderNumber: 'RAD-2025-0006',
    orderDate: new Date(today.setHours(10, 0, 0)),
    patientName: 'Lee Mei Ling',
    patientIC: '850310-08-8901',
    patientMRN: 'MRN-2024-01456',
    dateOfBirth: new Date('1985-03-10'),
    age: 39,
    gender: 'Female',
    modality: 'X-Ray',
    studyType: 'Portable Chest X-Ray (AP)',
    bodyPart: 'Chest',
    clinicalHistory: 'ICU patient, post intubation, ventilated',
    clinicalIndication: 'Check ETT position, evaluate for pneumothorax',
    orderingDepartment: 'ICU',
    orderingPhysician: 'Dr. Faridah Ahmad',
    priority: 'stat',
    status: 'pending',
    contrast: false,
    sedation: false,
    isolation: true,
    portable: true,
    notes: 'Isolation precautions required - COVID positive',
  },
];

// Mock DICOM Studies
export const mockDICOMStudies: DICOMStudy[] = [
  {
    id: 'STU001',
    studyInstanceUID: '1.2.840.10008.5.1.4.1.1.1.20250106.091500',
    accessionNumber: 'ACC-2025-0001',
    orderId: 'IMG001',
    patientName: 'Ahmad bin Hassan',
    patientMRN: 'MRN-2024-00123',
    modality: 'X-Ray',
    studyDescription: 'Chest X-Ray PA & Lateral',
    bodyPart: 'Chest',
    studyDate: today,
    studyTime: '09:15',
    numberOfSeries: 2,
    numberOfImages: 2,
    performingTechnologist: 'Radiographer Siti Azizah',
    equipment: 'Siemens Luminos dRF Max',
    imageQuality: 'excellent',
    status: 'final',
    storageLocation: '/dicom/2025/01/06/ACC-2025-0001',
    fileSize: 12.5,
    qaApproved: true,
    qaBy: 'Senior Radiographer Kumar',
    qaDate: new Date(today.setHours(9, 20, 0)),
  },
  {
    id: 'STU002',
    studyInstanceUID: '1.2.840.10008.5.1.4.1.1.2.20250106.100800',
    accessionNumber: 'ACC-2025-0002',
    orderId: 'IMG002',
    patientName: 'Siti Nurhaliza binti Abdullah',
    patientMRN: 'MRN-2024-00456',
    modality: 'CT',
    studyDescription: 'CT Brain without contrast',
    bodyPart: 'Brain',
    studyDate: today,
    studyTime: '10:08',
    numberOfSeries: 3,
    numberOfImages: 156,
    performingTechnologist: 'CT Radiographer Nurul Ain',
    equipment: 'GE Revolution CT 128-slice',
    imageQuality: 'good',
    technicalNotes: 'Patient slightly moved during acquisition, repeat scout',
    status: 'completed',
    storageLocation: '/dicom/2025/01/06/ACC-2025-0002',
    fileSize: 245.8,
    qaApproved: true,
    qaBy: 'Senior Radiographer Lim',
    qaDate: new Date(today.setHours(10, 35, 0)),
  },
];

// Mock Radiology Reports
export const mockRadiologyReports: RadiologyReport[] = [
  {
    id: 'REP001',
    reportNumber: 'RADREP-2025-0001',
    studyId: 'STU001',
    orderId: 'IMG001',
    accessionNumber: 'ACC-2025-0001',
    patientName: 'Ahmad bin Hassan',
    patientMRN: 'MRN-2024-00123',
    modality: 'X-Ray',
    studyDescription: 'Chest X-Ray PA & Lateral',
    indication: 'Chronic cough for 3 weeks. Rule out pneumonia, TB.',
    technique: 'PA and lateral views of the chest obtained.',
    comparison: 'No prior studies available for comparison.',
    findings: `The lungs are clear bilaterally with no focal consolidation, mass, or nodule. No pleural effusion or pneumothorax. The cardiomediastinal silhouette is within normal limits. Trachea is midline. Bony thorax is intact.`,
    impression: `1. No acute cardiopulmonary findings.
2. Clear lung fields bilaterally.
3. No radiographic evidence of pneumonia or active tuberculosis.

Recommendation: Clinical correlation advised. If symptoms persist, consider repeat imaging or further evaluation with CT chest.`,
    criticalFinding: false,
    reportedBy: 'Dr. Ahmad Radzi (Radiologist)',
    reportDate: new Date(today.setHours(10, 0, 0)),
    status: 'final',
    hasAddendum: false,
    notifiedToReferrer: true,
    notifiedAt: new Date(today.setHours(10, 5, 0)),
    templateUsed: 'Chest X-Ray Standard',
  },
  {
    id: 'REP002',
    reportNumber: 'RADREP-2025-0002',
    studyId: 'STU002',
    orderId: 'IMG002',
    accessionNumber: 'ACC-2025-0002',
    patientName: 'Siti Nurhaliza binti Abdullah',
    patientMRN: 'MRN-2024-00456',
    modality: 'CT',
    studyDescription: 'CT Brain without contrast',
    indication: 'Sudden onset severe headache with vomiting. Rule out intracranial hemorrhage, stroke.',
    technique: 'Non-contrast CT brain performed from skull base to vertex with 5mm slice thickness, multiplanar reformats obtained.',
    comparison: 'CT Brain dated 15/12/2023.',
    findings: `There is a large acute left subdural hematoma measuring approximately 15mm in maximum thickness with significant midline shift of approximately 8mm to the right. Associated mass effect on the left lateral ventricle with partial effacement. No underlying skull fracture identified. No subarachnoid hemorrhage. The gray-white matter differentiation is preserved. No acute infarct. Basal cisterns are patent. No hydrocephalus.

Compared to prior study: New finding, not present on previous imaging.`,
    impression: `CRITICAL FINDING - STAT NOTIFICATION GIVEN:

1. Large acute left subdural hematoma (approximately 15mm thick) with significant mass effect and 8mm midline shift.
2. Requires urgent neurosurgical consultation and intervention.

CRITICAL FINDING NOTIFICATION: Dr. Kumar Velan (Emergency Department) notified via phone at 10:45am on 06/01/2025 regarding findings requiring immediate neurosurgical referral.`,
    recommendations: 'URGENT neurosurgical consultation recommended.',
    criticalFinding: true,
    criticalNotes: 'Large SDH with mass effect - neurosurgery consulted',
    criticalNotifiedTo: 'Dr. Kumar Velan (Emergency) / Dr. Shahrul (Neurosurgery)',
    criticalNotifiedAt: new Date(today.setHours(10, 45, 0)),
    reportedBy: 'Dr. Chong Mei Lin (Consultant Radiologist)',
    reportDate: new Date(today.setHours(10, 40, 0)),
    status: 'final',
    hasAddendum: false,
    notifiedToReferrer: true,
    notifiedAt: new Date(today.setHours(10, 45, 0)),
    templateUsed: 'CT Brain Trauma',
  },
];

// Mock Equipment
export const mockRadiologyEquipment: RadiologyEquipment[] = [
  {
    id: 'EQ001',
    equipmentName: 'X-Ray Unit 1',
    modality: 'X-Ray',
    manufacturer: 'Siemens',
    model: 'Luminos dRF Max',
    serialNumber: 'SN-XR-001-2022',
    location: 'Radiology Department',
    room: 'X-Ray Room 1',
    status: 'operational',
    totalStudiesToday: 12,
    totalStudiesThisWeek: 67,
    totalStudiesThisMonth: 245,
    lastMaintenanceDate: new Date('2024-12-15'),
    nextMaintenanceDate: new Date('2025-03-15'),
    maintenanceInterval: 90,
    lastCalibrationDate: new Date('2024-12-15'),
    nextCalibrationDate: new Date('2025-06-15'),
    currentlyInUse: false,
    hasIssues: false,
  },
  {
    id: 'EQ002',
    equipmentName: 'CT Scanner',
    modality: 'CT',
    manufacturer: 'GE Healthcare',
    model: 'Revolution CT 128-slice',
    serialNumber: 'SN-CT-001-2021',
    location: 'Radiology Department',
    room: 'CT Suite',
    status: 'operational',
    totalStudiesToday: 8,
    totalStudiesThisWeek: 42,
    totalStudiesThisMonth: 168,
    lastMaintenanceDate: new Date('2024-11-20'),
    nextMaintenanceDate: new Date('2025-02-20'),
    maintenanceInterval: 90,
    lastCalibrationDate: new Date('2024-11-20'),
    nextCalibrationDate: new Date('2025-05-20'),
    currentlyInUse: true,
    currentStudy: 'IMG002 - CT Brain',
    estimatedCompletionTime: new Date(today.setHours(10, 50, 0)),
    hasIssues: false,
  },
  {
    id: 'EQ003',
    equipmentName: 'MRI Scanner',
    modality: 'MRI',
    manufacturer: 'Philips',
    model: 'Ingenia 1.5T',
    serialNumber: 'SN-MRI-001-2020',
    location: 'Radiology Department',
    room: 'MRI Suite',
    status: 'operational',
    totalStudiesToday: 5,
    totalStudiesThisWeek: 28,
    totalStudiesThisMonth: 112,
    lastMaintenanceDate: new Date('2024-12-01'),
    nextMaintenanceDate: new Date('2025-03-01'),
    maintenanceInterval: 90,
    lastCalibrationDate: new Date('2024-12-01'),
    nextCalibrationDate: new Date('2025-06-01'),
    currentlyInUse: false,
    hasIssues: false,
  },
  {
    id: 'EQ004',
    equipmentName: 'Ultrasound Unit 1',
    modality: 'Ultrasound',
    manufacturer: 'GE Healthcare',
    model: 'LOGIQ E10',
    serialNumber: 'SN-US-001-2023',
    location: 'Radiology Department',
    room: 'Ultrasound Room 1',
    status: 'operational',
    totalStudiesToday: 9,
    totalStudiesThisWeek: 52,
    totalStudiesThisMonth: 198,
    lastMaintenanceDate: new Date('2025-01-02'),
    nextMaintenanceDate: new Date('2025-04-02'),
    maintenanceInterval: 90,
    lastCalibrationDate: new Date('2025-01-02'),
    nextCalibrationDate: new Date('2025-07-02'),
    currentlyInUse: false,
    hasIssues: false,
  },
  {
    id: 'EQ005',
    equipmentName: 'Portable X-Ray',
    modality: 'X-Ray',
    manufacturer: 'Carestream',
    model: 'DRX-Revolution',
    serialNumber: 'SN-PXR-001-2022',
    location: 'Mobile Unit',
    room: 'Portable',
    status: 'maintenance',
    totalStudiesToday: 3,
    totalStudiesThisWeek: 15,
    totalStudiesThisMonth: 58,
    lastMaintenanceDate: new Date(today.setHours(8, 0, 0)),
    nextMaintenanceDate: new Date('2025-04-06'),
    maintenanceInterval: 90,
    lastCalibrationDate: new Date('2024-10-06'),
    nextCalibrationDate: new Date('2025-04-06'),
    currentlyInUse: false,
    hasIssues: true,
    issues: ['Detector battery requires replacement', 'Scheduled maintenance in progress'],
    reportedBy: 'Radiographer Kumar',
    reportedAt: new Date(today.setHours(7, 45, 0)),
    notes: 'Expected to be operational by 12:00pm',
  },
];

// Mock Radiologists
export const mockRadiologists: Radiologist[] = [
  {
    id: 'RAD001',
    name: 'Dr. Ahmad Radzi bin Hassan',
    designation: 'Consultant Radiologist',
    specialization: ['General Radiology', 'Chest Imaging', 'Musculoskeletal'],
    onDuty: true,
    availableForReporting: true,
    studiesReportedToday: 15,
    pendingReports: 8,
    contactNumber: '012-3456789',
  },
  {
    id: 'RAD002',
    name: 'Dr. Chong Mei Lin',
    designation: 'Consultant Radiologist',
    specialization: ['Neuroradiology', 'CT', 'MRI'],
    onDuty: true,
    availableForReporting: true,
    studiesReportedToday: 12,
    pendingReports: 5,
    contactNumber: '013-9876543',
  },
  {
    id: 'RAD003',
    name: 'Dr. Suresh Kumar',
    designation: 'Radiologist',
    specialization: ['Abdominal Imaging', 'Ultrasound', 'Interventional'],
    onDuty: true,
    availableForReporting: false,
    studiesReportedToday: 8,
    pendingReports: 12,
    contactNumber: '016-2345678',
  },
];

// Mock Stats
export const mockRadiologyStats: RadiologyStats = {
  totalOrdersToday: 28,
  pendingOrders: 4,
  completedStudies: 22,
  pendingReports: 25,
  
  statOrders: 2,
  urgentOrders: 5,
  routineOrders: 21,
  
  xrayStudies: 12,
  ctStudies: 8,
  mriStudies: 5,
  ultrasoundStudies: 3,
  
  averageReportingTime: 45,
  averageStudyDuration: 25,
  
  criticalFindingsToday: 1,
  
  equipmentOperational: 4,
  equipmentOffline: 1,
  
  repeatRate: 2.5,
  
  capacityUtilization: 75,
  estimatedWaitTime: 35,
};

export function getImagingOrders(): ImagingOrder[] {
  return mockImagingOrders;
}

export function getDICOMStudies(): DICOMStudy[] {
  return mockDICOMStudies;
}

export function getRadiologyReports(): RadiologyReport[] {
  return mockRadiologyReports;
}

export function getRadiologyEquipment(): RadiologyEquipment[] {
  return mockRadiologyEquipment;
}

export function getRadiologists(): Radiologist[] {
  return mockRadiologists;
}

export function getRadiologyStats(): RadiologyStats {
  return mockRadiologyStats;
}










