import type {
  StaffMember,
  LeaveApplication,
  BillingRecord,
  HospitalBed,
  OfficeAdminStats,
  DepartmentPerformance,
} from '../types/OfficeAdmin';

const today = new Date();

// Mock Staff Members
export const mockStaffMembers: StaffMember[] = [
  {
    id: 'STAFF001',
    staffId: 'HSL-001',
    name: 'Dr. Lim Wei Ming',
    icNumber: '750615-10-5234',
    department: 'General Medicine',
    position: 'Medical Officer',
    grade: 'UD44',
    employmentStatus: 'permanent',
    joinDate: new Date('2018-03-01'),
    email: 'limweiming@hospitallawas.gov.my',
    contactNumber: '012-3456789',
    address: 'Lawas, Sarawak',
    emergencyContact: 'Mrs. Lim',
    emergencyContactNumber: '013-9876543',
    qualifications: ['MBBS', 'MMed (Internal Medicine)'],
    certifications: ['ACLS', 'BLS Provider'],
    licenseNumber: 'MMC-12345',
    annualLeaveBalance: 18,
    sickLeaveBalance: 12,
    emergencyLeaveBalance: 7,
    totalAbsencesThisYear: 3,
    lastAppraisalDate: new Date('2024-06-15'),
    nextAppraisalDate: new Date('2025-06-15'),
    performanceRating: 4.5,
    isActive: true,
  },
  {
    id: 'STAFF002',
    staffId: 'HSL-045',
    name: 'Siti Azizah binti Ahmad',
    icNumber: '880824-08-2341',
    department: 'Pharmacy',
    position: 'Senior Pharmacist',
    grade: 'U48',
    employmentStatus: 'permanent',
    joinDate: new Date('2015-07-01'),
    email: 'sitiazizah@hospitallawas.gov.my',
    contactNumber: '013-9876543',
    address: 'Lawas, Sarawak',
    emergencyContact: 'Mr. Ahmad',
    emergencyContactNumber: '016-2345678',
    qualifications: ['B.Pharm', 'M.Clin.Pharm'],
    certifications: ['RPH License'],
    licenseNumber: 'PHAR-12345',
    annualLeaveBalance: 22,
    sickLeaveBalance: 14,
    emergencyLeaveBalance: 7,
    totalAbsencesThisYear: 2,
    lastAppraisalDate: new Date('2024-08-20'),
    nextAppraisalDate: new Date('2025-08-20'),
    performanceRating: 4.8,
    isActive: true,
  },
  {
    id: 'STAFF003',
    staffId: 'HSL-122',
    name: 'Kumar s/o Velan',
    icNumber: '920405-05-3456',
    department: 'Laboratory',
    position: 'Medical Laboratory Technologist',
    grade: 'U29',
    employmentStatus: 'contract',
    joinDate: new Date('2023-01-15'),
    email: 'kumarvelan@hospitallawas.gov.my',
    contactNumber: '016-2345678',
    address: 'Lawas, Sarawak',
    emergencyContact: 'Mrs. Devi',
    emergencyContactNumber: '019-8887766',
    qualifications: ['Diploma in Medical Laboratory Technology'],
    certifications: ['MLAB Certification'],
    annualLeaveBalance: 14,
    sickLeaveBalance: 14,
    emergencyLeaveBalance: 5,
    totalAbsencesThisYear: 1,
    isActive: true,
  },
  {
    id: 'STAFF004',
    staffId: 'HSL-088',
    name: 'Nurse Fatimah binti Ismail',
    icNumber: '850518-14-4567',
    department: 'General Ward',
    position: 'Staff Nurse',
    grade: 'U29',
    employmentStatus: 'permanent',
    joinDate: new Date('2016-09-01'),
    email: 'fatimah@hospitallawas.gov.my',
    contactNumber: '019-4445555',
    address: 'Lawas, Sarawak',
    emergencyContact: 'Mr. Ismail',
    emergencyContactNumber: '012-6667777',
    qualifications: ['Diploma in Nursing', 'Post-Basic Critical Care Nursing'],
    certifications: ['RN License', 'BLS Provider'],
    annualLeaveBalance: 20,
    sickLeaveBalance: 14,
    emergencyLeaveBalance: 7,
    totalAbsencesThisYear: 4,
    lastAppraisalDate: new Date('2024-09-01'),
    nextAppraisalDate: new Date('2025-09-01'),
    performanceRating: 4.2,
    isActive: true,
  },
];

// Mock Leave Applications
export const mockLeaveApplications: LeaveApplication[] = [
  {
    id: 'LEAVE001',
    applicationNumber: 'LEAVE-2025-0001',
    applicationDate: new Date('2025-01-02'),
    staffId: 'HSL-001',
    staffName: 'Dr. Lim Wei Ming',
    department: 'General Medicine',
    position: 'Medical Officer',
    leaveType: 'annual',
    startDate: new Date('2025-01-15'),
    endDate: new Date('2025-01-19'),
    totalDays: 5,
    reason: 'Family vacation',
    status: 'approved',
    submittedBy: 'Dr. Lim Wei Ming',
    reviewedBy: 'Dr. Hassan (Head of Department)',
    reviewedDate: new Date('2025-01-03'),
    reviewComments: 'Approved. Coverage arranged.',
    reliefOfficer: 'Dr. Kumar Velan',
    reliefOfficerAgreed: true,
  },
  {
    id: 'LEAVE002',
    applicationNumber: 'LEAVE-2025-0002',
    applicationDate: new Date(today.setHours(8, 30, 0)),
    staffId: 'HSL-088',
    staffName: 'Nurse Fatimah binti Ismail',
    department: 'General Ward',
    position: 'Staff Nurse',
    leaveType: 'sick',
    startDate: today,
    endDate: new Date(today.setDate(today.getDate() + 1)),
    totalDays: 2,
    reason: 'Fever and flu',
    status: 'pending',
    submittedBy: 'Nurse Fatimah',
    hasMedicalCertificate: true,
    notes: 'MC attached from Klinik Kesihatan',
  },
  {
    id: 'LEAVE003',
    applicationNumber: 'LEAVE-2025-0003',
    applicationDate: new Date('2025-01-04'),
    staffId: 'HSL-122',
    staffName: 'Kumar s/o Velan',
    department: 'Laboratory',
    position: 'Medical Laboratory Technologist',
    leaveType: 'emergency',
    startDate: new Date('2025-01-10'),
    endDate: new Date('2025-01-10'),
    totalDays: 1,
    reason: 'Urgent family matter',
    status: 'approved',
    submittedBy: 'Kumar',
    reviewedBy: 'Laboratory Supervisor',
    reviewedDate: new Date('2025-01-04'),
    reviewComments: 'Approved for emergency leave',
  },
];

// Mock Billing Records
export const mockBillingRecords: BillingRecord[] = [
  {
    id: 'BILL001',
    billNumber: 'BILL-2025-0001',
    billDate: today,
    patientName: 'Ahmad bin Hassan',
    patientIC: '750615-10-5234',
    patientMRN: 'MRN-2024-00123',
    claimType: 'government',
    items: [
      {
        id: 'BITEM001-1',
        itemCode: 'CONS-001',
        itemName: 'General Consultation',
        itemType: 'consultation',
        quantity: 1,
        unitPrice: 1.00,
        totalPrice: 1.00,
        chargingDepartment: 'Outpatient',
        isSubsidized: true,
        subsidyAmount: 49.00,
        coveredByInsurance: false,
      },
      {
        id: 'BITEM001-2',
        itemCode: 'MED-001',
        itemName: 'Paracetamol 500mg',
        itemType: 'medication',
        quantity: 20,
        unitPrice: 0.05,
        totalPrice: 1.00,
        chargingDepartment: 'Pharmacy',
        isSubsidized: true,
        subsidyAmount: 9.00,
        coveredByInsurance: false,
      },
    ],
    subtotal: 2.00,
    discounts: 0,
    gst: 0,
    totalAmount: 2.00,
    paidAmount: 2.00,
    outstandingAmount: 0,
    status: 'paid',
    processedBy: 'Receptionist Aisha',
    processedDate: today,
    paidDate: today,
    notes: 'Government subsidized healthcare - RM 1 consultation',
  },
  {
    id: 'BILL002',
    billNumber: 'BILL-2025-0002',
    billDate: today,
    patientName: 'Lee Mei Ling',
    patientIC: '920115-12-3456',
    patientMRN: 'MRN-2024-01456',
    claimType: 'panel',
    items: [
      {
        id: 'BITEM002-1',
        itemCode: 'LAB-001',
        itemName: 'Full Blood Count',
        itemType: 'lab-test',
        quantity: 1,
        unitPrice: 25.00,
        totalPrice: 25.00,
        chargingDepartment: 'Laboratory',
        isSubsidized: false,
        coveredByInsurance: false,
      },
      {
        id: 'BITEM002-2',
        itemCode: 'LAB-002',
        itemName: 'Lipid Profile',
        itemType: 'lab-test',
        quantity: 1,
        unitPrice: 35.00,
        totalPrice: 35.00,
        chargingDepartment: 'Laboratory',
        isSubsidized: false,
        coveredByInsurance: false,
      },
    ],
    subtotal: 60.00,
    discounts: 0,
    gst: 0,
    totalAmount: 60.00,
    paidAmount: 60.00,
    outstandingAmount: 0,
    panelName: 'Great Eastern Panel',
    panelApprovalNumber: 'GE-2025-001234',
    status: 'paid',
    processedBy: 'Billing Officer Sarah',
    processedDate: today,
    paidDate: today,
  },
  {
    id: 'BILL003',
    billNumber: 'BILL-2025-0003',
    billDate: today,
    patientName: 'Wong Ah Meng',
    patientIC: '650920-10-6789',
    patientMRN: 'MRN-2024-01234',
    claimType: 'insurance',
    items: [
      {
        id: 'BITEM003-1',
        itemCode: 'BED-001',
        itemName: 'General Ward Bed (2 days)',
        itemType: 'bed-charge',
        quantity: 2,
        unitPrice: 15.00,
        totalPrice: 30.00,
        chargingDepartment: 'General Ward',
        isSubsidized: true,
        subsidyAmount: 170.00,
        coveredByInsurance: true,
        insuranceCoverage: 30.00,
      },
      {
        id: 'BITEM003-2',
        itemCode: 'PROC-001',
        itemName: 'Minor Surgery',
        itemType: 'procedure',
        quantity: 1,
        unitPrice: 200.00,
        totalPrice: 200.00,
        chargingDepartment: 'Surgery',
        isSubsidized: false,
        coveredByInsurance: true,
        insuranceCoverage: 200.00,
      },
    ],
    subtotal: 230.00,
    discounts: 0,
    gst: 0,
    totalAmount: 230.00,
    paidAmount: 0,
    outstandingAmount: 0,
    insuranceProvider: 'Prudential',
    insurancePolicyNumber: 'PRU-2024-556789',
    insuranceCoverage: 230.00,
    insuranceApprovalNumber: 'PRU-APPR-2025-001',
    status: 'processing',
    processedBy: 'Insurance Claims Officer',
    processedDate: today,
    notes: 'Full coverage by insurance - claim submitted',
  },
];

// Mock Hospital Beds
export const mockHospitalBeds: HospitalBed[] = [
  {
    id: 'BED001',
    bedNumber: 'GW-A-01',
    ward: 'General Ward A',
    room: 'Room A1',
    bedType: 'general',
    status: 'occupied',
    currentPatient: 'Ahmad bin Hassan',
    currentPatientMRN: 'MRN-2024-00123',
    admissionDate: new Date('2025-01-04'),
    estimatedDischargeDate: new Date('2025-01-07'),
    dailyRate: 15.00,
    lastCleaningDate: new Date(today.setHours(6, 0, 0)),
    hasOxygen: true,
    hasSuction: false,
    hasMonitor: false,
  },
  {
    id: 'BED002',
    bedNumber: 'GW-A-02',
    ward: 'General Ward A',
    room: 'Room A1',
    bedType: 'general',
    status: 'available',
    dailyRate: 15.00,
    lastCleaningDate: new Date(today.setHours(7, 30, 0)),
    hasOxygen: true,
    hasSuction: false,
    hasMonitor: false,
  },
  {
    id: 'BED003',
    bedNumber: 'ICU-01',
    ward: 'ICU',
    room: 'ICU Bay 1',
    bedType: 'icu',
    status: 'occupied',
    currentPatient: 'Siti Nurhaliza',
    currentPatientMRN: 'MRN-2024-00456',
    admissionDate: new Date('2025-01-05'),
    dailyRate: 300.00,
    lastCleaningDate: new Date(today.setHours(8, 0, 0)),
    hasOxygen: true,
    hasSuction: true,
    hasMonitor: true,
  },
  {
    id: 'BED004',
    bedNumber: 'ICU-02',
    ward: 'ICU',
    room: 'ICU Bay 2',
    bedType: 'icu',
    status: 'available',
    dailyRate: 300.00,
    lastCleaningDate: new Date(today.setHours(6, 30, 0)),
    hasOxygen: true,
    hasSuction: true,
    hasMonitor: true,
  },
  {
    id: 'BED005',
    bedNumber: 'PVT-01',
    ward: 'Private Ward',
    room: 'Private Room 1',
    bedType: 'private',
    status: 'cleaning',
    dailyRate: 80.00,
    lastCleaningDate: new Date(today.setHours(9, 0, 0)),
    hasOxygen: true,
    hasSuction: false,
    hasMonitor: false,
    notes: 'Deep cleaning in progress',
  },
];

// Mock Department Performance
export const mockDepartmentPerformance: DepartmentPerformance[] = [
  {
    department: 'Emergency & Trauma',
    totalStaff: 18,
    staffOnDuty: 12,
    staffUtilization: 88,
    patientsServed: 45,
    proceduresCompleted: 12,
    averageWaitTime: 22,
    revenueGenerated: 8500.00,
    expensesIncurred: 4200.00,
    patientSatisfaction: 87,
    complaintCount: 2,
    resourceUtilization: 82,
    turnaroundTime: 28,
  },
  {
    department: 'General Ward',
    totalStaff: 24,
    staffOnDuty: 16,
    staffUtilization: 85,
    patientsServed: 32,
    proceduresCompleted: 8,
    averageWaitTime: 15,
    revenueGenerated: 6200.00,
    expensesIncurred: 3500.00,
    patientSatisfaction: 92,
    complaintCount: 1,
    resourceUtilization: 75,
    turnaroundTime: 35,
  },
  {
    department: 'Pharmacy',
    totalStaff: 12,
    staffOnDuty: 8,
    staffUtilization: 92,
    patientsServed: 125,
    proceduresCompleted: 125,
    averageWaitTime: 18,
    revenueGenerated: 15800.00,
    expensesIncurred: 12000.00,
    patientSatisfaction: 90,
    complaintCount: 3,
    resourceUtilization: 88,
    turnaroundTime: 12,
  },
  {
    department: 'Laboratory',
    totalStaff: 10,
    staffOnDuty: 7,
    staffUtilization: 90,
    patientsServed: 78,
    proceduresCompleted: 156,
    averageWaitTime: 45,
    revenueGenerated: 12400.00,
    expensesIncurred: 8500.00,
    complaintCount: 1,
    resourceUtilization: 85,
    turnaroundTime: 90,
  },
];

// Mock Stats
export const mockOfficeAdminStats: OfficeAdminStats = {
  totalStaff: 248,
  activeStaff: 242,
  staffOnLeave: 8,
  staffAbsent: 3,
  
  pendingLeaveApplications: 12,
  approvedLeavesToday: 3,
  
  attendanceRate: 96,
  averageWorkingHours: 8.2,
  overtimeHoursThisMonth: 156,
  
  totalBillsToday: 47,
  pendingClaims: 15,
  totalRevenueToday: 28450.00,
  outstandingPayments: 12680.00,
  
  insuranceClaimsProcessing: 8,
  insuranceClaimValue: 45200.00,
  
  totalBeds: 120,
  occupiedBeds: 89,
  availableBeds: 31,
  occupancyRate: 74.2,
  
  icuBeds: 8,
  icuOccupancy: 5,
  hduBeds: 6,
  hduOccupancy: 4,
  
  totalUserAccounts: 265,
  activeUsers: 248,
  lockedAccounts: 3,
  
  averageAdmissionTime: 28,
  averageLengthOfStay: 3.5,
  dischargesThisMonth: 142,
  
  monthlyRevenue: 845200.00,
  monthlyExpenses: 625400.00,
  monthlyProfit: 219800.00,
};

export function getStaffMembers(): StaffMember[] {
  return mockStaffMembers;
}

export function getLeaveApplications(): LeaveApplication[] {
  return mockLeaveApplications;
}

export function getBillingRecords(): BillingRecord[] {
  return mockBillingRecords;
}

export function getHospitalBeds(): HospitalBed[] {
  return mockHospitalBeds;
}

export function getDepartmentPerformance(): DepartmentPerformance[] {
  return mockDepartmentPerformance;
}

export function getOfficeAdminStats(): OfficeAdminStats {
  return mockOfficeAdminStats;
}










