export const SYSTEM_MODULES = {
  PHARMACY_LOGISTICS: 'pharmacy_logistics',
  PHARMACY_SUBSTORE: 'pharmacy_substore',
  PHARMACY_OUTPATIENT: 'pharmacy_outpatient',
  PHARMACY_EMERGENCY: 'pharmacy_emergency',
  PHARMACY_INPATIENT: 'pharmacy_inpatient',
  PHARMACY_GALENICAL: 'pharmacy_galenical',
  PHARMACY_FORMULARI: 'pharmacy_formulari',
  SYSTEM_PORTER: 'system_porter',
  SYSTEM_TRANSPORTER: 'system_transporter',
  SYSTEM_PRIVILEDGING: 'system_priviledging',
  SYSTEM_TEMPAHAN: 'system_tempahan',
  SYSTEM_PERHIMPUNAN: 'system_perhimpunan',
  SYSTEM_KUNCI: 'system_kunci',
  SYSTEM_CUTI: 'system_cuti',
  GENERAL_WARD: 'general_ward',
  PAEDIATRIC_WARD: 'paediatric_ward',
  MATERNITY_WARD: 'maternity_ward',
  EMERGENCY_TRAUMA: 'emergency_trauma',
  LABORATORY: 'laboratory',
  OPERATION_THEATER: 'operation_theater',
  CSSU_CSSD: 'cssu_cssd',
  RADIOLOGY: 'radiology',
  KLINIK_PAKAR: 'klinik_pakar',
  HAEMODIALYSIS: 'haemodialysis',
  DRIVER_ROOM: 'driver_room',
  HOSPITAL_OFFICE: 'hospital_office',
  FRONT_DESK: 'front_desk',
  PHARMACY: 'pharmacy',
  WARD: 'ward',
  BILLING: 'billing',
  HR: 'hr',
  ASSET: 'asset',
  REPORTS: 'reports',
} as const

export const MODULE_CATEGORIES = {
  PHARMACY: { code: 'pharmacy', name: 'Pharmacy', icon: 'Pill' },
  WARD: { code: 'ward', name: 'Ward Management', icon: 'Bed' },
  CLINICAL: { code: 'clinical', name: 'Clinical Services', icon: 'Stethoscope' },
  SUPPORT: { code: 'support', name: 'Support Services', icon: 'Settings' },
} as const

export const MODULE_DEFINITIONS = [
  {
    code: SYSTEM_MODULES.PHARMACY_LOGISTICS,
    name: 'MyWarrant',
    description: 'Central pharmacy logistics, inventory, procurement, and distribution',
    icon: 'Package',
    category: 'pharmacy',
  },
  {
    code: SYSTEM_MODULES.PHARMACY_SUBSTORE,
    name: 'Pharmacy Substore',
    description: 'Substore inventory and stock management',
    icon: 'Warehouse',
    category: 'pharmacy',
  },
  {
    code: SYSTEM_MODULES.PHARMACY_OUTPATIENT,
    name: 'Pharmacy Outpatient',
    description: 'Outpatient dispensing and prescription management',
    icon: 'Pill',
    category: 'pharmacy',
  },
  {
    code: SYSTEM_MODULES.PHARMACY_EMERGENCY,
    name: 'Pharmacy Emergency',
    description: 'Emergency pharmacy operations',
    icon: 'AlertCircle',
    category: 'pharmacy',
  },
  {
    code: SYSTEM_MODULES.PHARMACY_INPATIENT,
    name: 'Pharmacy In Patient',
    description: 'Inpatient medication management',
    icon: 'Bed',
    category: 'pharmacy',
  },
  {
    code: SYSTEM_MODULES.PHARMACY_GALENICAL,
    name: 'Pharmacy Galenical & Prepacking',
    description: 'Extemporaneous preparation and prepacking',
    icon: 'Beaker',
    category: 'pharmacy',
  },
  {
    code: SYSTEM_MODULES.PHARMACY_FORMULARI,
    name: 'MyFormulari',
    description: 'National and hospital drug formulary management',
    icon: 'Search',
    category: 'pharmacy',
  },
  {
    code: SYSTEM_MODULES.SYSTEM_PORTER,
    name: 'MyPorter',
    description: 'Patient and asset portering services',
    icon: 'Truck',
    category: 'support',
  },
  {
    code: SYSTEM_MODULES.SYSTEM_TRANSPORTER,
    name: 'MyTransporter',
    description: 'Vehicle Fleet & Transport Management System',
    icon: 'Car',
    category: 'support',
  },
  {
    code: SYSTEM_MODULES.SYSTEM_PRIVILEDGING,
    name: 'MyPriviledging',
    description: 'Staff clinical priviledging and credentialing',
    icon: 'UserCheck',
    category: 'support',
  },
  {
    code: SYSTEM_MODULES.SYSTEM_TEMPAHAN,
    name: 'MyTempahan',
    description: 'Facility and equipment booking system',
    icon: 'Calendar',
    category: 'support',
  },
  {
    code: SYSTEM_MODULES.SYSTEM_PERHIMPUNAN,
    name: 'MyPerhimpunan',
    description: 'Assembly & Events Management System',
    icon: 'Users',
    category: 'support',
  },
  {
    code: SYSTEM_MODULES.SYSTEM_KUNCI,
    name: 'MyKunci',
    description: 'Integrated Key Management System',
    icon: 'Key',
    category: 'support',
  },
  {
    code: SYSTEM_MODULES.SYSTEM_CUTI,
    name: 'MyCuti',
    description: 'Staff Leave Management System',
    icon: 'Plane',
    category: 'support',
  },
  {
    code: SYSTEM_MODULES.GENERAL_WARD,
    name: 'General Ward',
    description: 'General ward patient management',
    icon: 'BedDouble',
    category: 'ward',
  },
  {
    code: SYSTEM_MODULES.PAEDIATRIC_WARD,
    name: 'Paediatric Ward',
    description: 'Paediatric patient care and management',
    icon: 'Baby',
    category: 'ward',
  },
  {
    code: SYSTEM_MODULES.MATERNITY_WARD,
    name: 'Maternity Ward',
    description: 'Maternity and obstetrics care',
    icon: 'Heart',
    category: 'ward',
  },
  {
    code: SYSTEM_MODULES.EMERGENCY_TRAUMA,
    name: 'Emergency & Trauma',
    description: 'Emergency and trauma department management',
    icon: 'Ambulance',
    category: 'clinical',
  },
  {
    code: SYSTEM_MODULES.LABORATORY,
    name: 'Laboratory',
    description: 'Laboratory tests and results management',
    icon: 'FlaskConical',
    category: 'clinical',
  },
  {
    code: SYSTEM_MODULES.OPERATION_THEATER,
    name: 'Operation Theater',
    description: 'Operation theater scheduling and management',
    icon: 'Scissors',
    category: 'clinical',
  },
  {
    code: SYSTEM_MODULES.CSSU_CSSD,
    name: 'CSSU/CSSD',
    description: 'Central Sterile Supply Unit management',
    icon: 'ShieldCheck',
    category: 'clinical',
  },
  {
    code: SYSTEM_MODULES.RADIOLOGY,
    name: 'Radiology & Radiography',
    description: 'Imaging and radiology services',
    icon: 'Scan',
    category: 'clinical',
  },
  {
    code: SYSTEM_MODULES.KLINIK_PAKAR,
    name: 'Specialist Clinic',
    description: 'Specialist clinic management',
    icon: 'Stethoscope',
    category: 'clinical',
  },
  {
    code: SYSTEM_MODULES.HAEMODIALYSIS,
    name: 'Haemodialysis',
    description: 'Haemodialysis unit management',
    icon: 'Activity',
    category: 'clinical',
  },
  {
    code: SYSTEM_MODULES.DRIVER_ROOM,
    name: 'Driver Room',
    description: 'Driver and transport management',
    icon: 'Car',
    category: 'support',
  },
  {
    code: SYSTEM_MODULES.HOSPITAL_OFFICE,
    name: 'Hospital Office',
    description: 'Hospital administration office',
    icon: 'Building',
    category: 'support',
  },
  {
    code: SYSTEM_MODULES.FRONT_DESK,
    name: 'Front Desk',
    description: 'Reception and registration',
    icon: 'UserCheck',
    category: 'support',
  },
  {
    code: SYSTEM_MODULES.BILLING,
    name: 'Financial & Billing',
    description: 'Manage billing and financial operations',
    icon: 'DollarSign',
    category: 'support',
  },
  {
    code: SYSTEM_MODULES.HR,
    name: 'Human Resources',
    description: 'Manage HR operations and employee data',
    icon: 'Users',
    category: 'support',
  },
  {
    code: SYSTEM_MODULES.ASSET,
    name: 'Asset Management',
    description: 'Manage hospital assets and equipment',
    icon: 'Package',
    category: 'support',
  },
  {
    code: SYSTEM_MODULES.REPORTS,
    name: 'Advanced Reports',
    description: 'Access advanced reporting and analytics',
    icon: 'FileText',
    category: 'support',
  },
] as const
