export const SYSTEM_ROLES = {
  SYSTEM_ADMIN: 'system_admin',
  HOSPITAL_ADMIN: 'hospital_admin',
  PHARMACY_DIRECTOR: 'pharmacy_director',
  PHARMACY_MANAGER: 'pharmacy_manager',
  PHARMACIST: 'pharmacist',
  PHARMACY_ASSISTANT: 'pharmacy_assistant',
  PHARMACY_STOREKEEPER: 'pharmacy_storekeeper',
  PHARMACY_STAFF: 'pharmacy_staff',
  NURSE: 'nurse',
  DOCTOR: 'doctor',
  MEDICAL_OFFICER: 'medical_officer',
  ASSISTANT_MEDICAL_OFFICER: 'assistant_medical_officer',
  ASSISTANT_PHARMACIST: 'assistant_pharmacist',
  HOSPITAL_ADMINISTRATOR: 'hospital_administrator',
  STAFF: 'staff',
  TRANSPORT_DRIVER: 'transport_driver',
  TRANSPORT_ADMIN: 'transport_admin',
  PORTER_STAFF: 'porter_staff',
  PORTER_SUPERVISOR: 'porter_supervisor',
  PORTER_ADMIN: 'porter_admin',
} as const

export const ROLE_DISPLAY_NAMES: Record<string, string> = {
  [SYSTEM_ROLES.SYSTEM_ADMIN]: 'System Administrator',
  [SYSTEM_ROLES.HOSPITAL_ADMIN]: 'Hospital Administrator',
  [SYSTEM_ROLES.PHARMACY_DIRECTOR]: 'Pharmacy Director',
  [SYSTEM_ROLES.PHARMACY_MANAGER]: 'Pharmacy Manager',
  [SYSTEM_ROLES.PHARMACIST]: 'Pharmacist',
  [SYSTEM_ROLES.PHARMACY_ASSISTANT]: 'Pharmacy Assistant',
  [SYSTEM_ROLES.PHARMACY_STOREKEEPER]: 'Store Keeper',
  [SYSTEM_ROLES.PHARMACY_STAFF]: 'Pharmacy Staff',
  [SYSTEM_ROLES.NURSE]: 'Nurse',
  [SYSTEM_ROLES.DOCTOR]: 'Doctor',
  [SYSTEM_ROLES.MEDICAL_OFFICER]: 'Medical Officer',
  [SYSTEM_ROLES.ASSISTANT_MEDICAL_OFFICER]: 'Assistant Medical Officer',
  [SYSTEM_ROLES.ASSISTANT_PHARMACIST]: 'Assistant Pharmacist',
  [SYSTEM_ROLES.HOSPITAL_ADMINISTRATOR]: 'Hospital Administrator',
  [SYSTEM_ROLES.STAFF]: 'Staff',
  [SYSTEM_ROLES.TRANSPORT_DRIVER]: 'Transport Driver',
  [SYSTEM_ROLES.TRANSPORT_ADMIN]: 'Transport Admin',
  [SYSTEM_ROLES.PORTER_STAFF]: 'Porter (PPK)',
  [SYSTEM_ROLES.PORTER_SUPERVISOR]: 'Penyelia Porter (PPK Supervisor)',
  [SYSTEM_ROLES.PORTER_ADMIN]: 'Porter Admin',
} as const

