import type { DrugItem } from '../types/DrugItem';

// Extended drug database with remaining 100 drugs (101-200)
export const extendedDrugItems: DrugItem[] = [
  // Hematology
  {
    id: 'drug-101',
    drugCode: 'HEM-001',
    drugName: 'Ferrous Sulfate 200mg Tablet',
    dosageForm: 'Tablet',
    sku: 'FER-200-TAB',
    category: 'Hematology',
    supplier: 'MediCare Solutions',
    budgetSource: 'APPL',
    unitPrice: 0.08,
    stockLevel: 10000,
    minLevel: 2500,
    maxLevel: 25000,
    status: 'Active',
    createdAt: '2024-01-10',
    updatedAt: '2024-12-01'
  },
  {
    id: 'drug-102',
    drugCode: 'HEM-002',
    drugName: 'Folic Acid 5mg Tablet',
    dosageForm: 'Tablet',
    sku: 'FOL-5-TAB',
    category: 'Hematology',
    supplier: 'PharmaCorp Malaysia',
    budgetSource: 'CC/DP',
    unitPrice: 0.05,
    stockLevel: 15000,
    minLevel: 4000,
    maxLevel: 40000,
    status: 'Active',
    createdAt: '2024-01-15',
    updatedAt: '2024-12-01'
  },
  {
    id: 'drug-103',
    drugCode: 'HEM-003',
    drugName: 'Cyanocobalamin 1000mcg Injection',
    dosageForm: 'Injection',
    sku: 'CYA-1000-INJ',
    category: 'Hematology',
    supplier: 'BioPharm Solutions',
    budgetSource: 'APPL',
    unitPrice: 2.50,
    stockLevel: 500,
    minLevel: 100,
    maxLevel: 1000,
    status: 'Active',
    createdAt: '2024-01-20',
    updatedAt: '2024-12-01'
  },
  {
    id: 'drug-104',
    drugCode: 'HEM-004',
    drugName: 'Erythropoietin 4000 units Injection',
    dosageForm: 'Injection',
    sku: 'ERY-4000-INJ',
    category: 'Hematology',
    supplier: 'Global Medical',
    budgetSource: 'CC/DP',
    unitPrice: 45.00,
    stockLevel: 100,
    minLevel: 20,
    maxLevel: 200,
    status: 'Active',
    createdAt: '2024-02-01',
    updatedAt: '2024-12-01'
  },
  {
    id: 'drug-105',
    drugCode: 'HEM-005',
    drugName: 'Tranexamic Acid 500mg Tablet',
    dosageForm: 'Tablet',
    sku: 'TRA-500-TAB',
    category: 'Hematology',
    supplier: 'Prime Health Corp',
    budgetSource: 'APPL',
    unitPrice: 0.35,
    stockLevel: 2000,
    minLevel: 500,
    maxLevel: 5000,
    status: 'Active',
    createdAt: '2024-02-05',
    updatedAt: '2024-12-01'
  },

  // Urology
  {
    id: 'drug-106',
    drugCode: 'URO-001',
    drugName: 'Tamsulosin 0.4mg Capsule',
    dosageForm: 'Capsule',
    sku: 'TAM-04-CAP',
    category: 'Urology',
    supplier: 'MediSupply Sdn Bhd',
    budgetSource: 'CC/DP',
    unitPrice: 0.65,
    stockLevel: 3000,
    minLevel: 800,
    maxLevel: 8000,
    status: 'Active',
    createdAt: '2024-01-12',
    updatedAt: '2024-12-01'
  },
  {
    id: 'drug-107',
    drugCode: 'URO-002',
    drugName: 'Finasteride 5mg Tablet',
    dosageForm: 'Tablet',
    sku: 'FIN-5-TAB',
    category: 'Urology',
    supplier: 'BioPharm Solutions',
    budgetSource: 'APPL',
    unitPrice: 0.85,
    stockLevel: 2000,
    minLevel: 500,
    maxLevel: 5000,
    status: 'Active',
    createdAt: '2024-01-15',
    updatedAt: '2024-12-01'
  },
  {
    id: 'drug-108',
    drugCode: 'URO-003',
    drugName: 'Dutasteride 0.5mg Capsule',
    dosageForm: 'Capsule',
    sku: 'DUT-05-CAP',
    category: 'Urology',
    supplier: 'Global Medical',
    budgetSource: 'CC/DP',
    unitPrice: 1.50,
    stockLevel: 1500,
    minLevel: 400,
    maxLevel: 4000,
    status: 'Active',
    createdAt: '2024-01-18',
    updatedAt: '2024-12-01'
  },
  {
    id: 'drug-109',
    drugCode: 'URO-004',
    drugName: 'Oxybutynin 5mg Tablet',
    dosageForm: 'Tablet',
    sku: 'OXY-5-TAB',
    category: 'Urology',
    supplier: 'Prime Health Corp',
    budgetSource: 'APPL',
    unitPrice: 0.45,
    stockLevel: 2500,
    minLevel: 600,
    maxLevel: 6000,
    status: 'Active',
    createdAt: '2024-02-01',
    updatedAt: '2024-12-01'
  },
  {
    id: 'drug-110',
    drugCode: 'URO-005',
    drugName: 'Solifenacin 5mg Tablet',
    dosageForm: 'Tablet',
    sku: 'SOL-5-TAB',
    category: 'Urology',
    supplier: 'MediCare Solutions',
    budgetSource: 'CC/DP',
    unitPrice: 1.20,
    stockLevel: 1800,
    minLevel: 450,
    maxLevel: 4500,
    status: 'Active',
    createdAt: '2024-02-05',
    updatedAt: '2024-12-01'
  },

  // Oncology
  {
    id: 'drug-111',
    drugCode: 'ONC-001',
    drugName: 'Cisplatin 50mg Injection',
    dosageForm: 'Injection',
    sku: 'CIS-50-INJ',
    category: 'Oncology',
    supplier: 'Global Medical',
    budgetSource: 'APPL',
    unitPrice: 85.00,
    stockLevel: 50,
    minLevel: 10,
    maxLevel: 100,
    status: 'Active',
    createdAt: '2024-01-10',
    updatedAt: '2024-12-01'
  },
  {
    id: 'drug-112',
    drugCode: 'ONC-002',
    drugName: 'Doxorubicin 50mg Injection',
    dosageForm: 'Injection',
    sku: 'DOX-50-INJ',
    category: 'Oncology',
    supplier: 'Prime Health Corp',
    budgetSource: 'CC/DP',
    unitPrice: 120.00,
    stockLevel: 40,
    minLevel: 8,
    maxLevel: 80,
    status: 'Active',
    createdAt: '2024-01-15',
    updatedAt: '2024-12-01'
  },
  {
    id: 'drug-113',
    drugCode: 'ONC-003',
    drugName: 'Paclitaxel 30mg Injection',
    dosageForm: 'Injection',
    sku: 'PAC-30-INJ',
    category: 'Oncology',
    supplier: 'BioPharm Solutions',
    budgetSource: 'APPL',
    unitPrice: 95.00,
    stockLevel: 35,
    minLevel: 7,
    maxLevel: 70,
    status: 'Active',
    createdAt: '2024-01-20',
    updatedAt: '2024-12-01'
  },
  {
    id: 'drug-114',
    drugCode: 'ONC-004',
    drugName: 'Carboplatin 150mg Injection',
    dosageForm: 'Injection',
    sku: 'CAR-150-INJ',
    category: 'Oncology',
    supplier: 'MediSupply Sdn Bhd',
    budgetSource: 'CC/DP',
    unitPrice: 75.00,
    stockLevel: 45,
    minLevel: 9,
    maxLevel: 90,
    status: 'Active',
    createdAt: '2024-02-01',
    updatedAt: '2024-12-01'
  },
  {
    id: 'drug-115',
    drugCode: 'ONC-005',
    drugName: 'Methotrexate 50mg Injection',
    dosageForm: 'Injection',
    sku: 'MET-50-INJ',
    category: 'Oncology',
    supplier: 'MediCare Solutions',
    budgetSource: 'APPL',
    unitPrice: 25.00,
    stockLevel: 80,
    minLevel: 16,
    maxLevel: 160,
    status: 'Active',
    createdAt: '2024-02-05',
    updatedAt: '2024-12-01'
  },

  // Rheumatology
  {
    id: 'drug-116',
    drugCode: 'RHE-001',
    drugName: 'Methotrexate 2.5mg Tablet',
    dosageForm: 'Tablet',
    sku: 'MET-25-TAB',
    category: 'Rheumatology',
    supplier: 'PharmaCorp Malaysia',
    budgetSource: 'APPL',
    unitPrice: 0.15,
    stockLevel: 5000,
    minLevel: 1200,
    maxLevel: 12000,
    status: 'Active',
    createdAt: '2024-01-12',
    updatedAt: '2024-12-01'
  },
  {
    id: 'drug-117',
    drugCode: 'RHE-002',
    drugName: 'Sulfasalazine 500mg Tablet',
    dosageForm: 'Tablet',
    sku: 'SUL-500-TAB',
    category: 'Rheumatology',
    supplier: 'BioPharm Solutions',
    budgetSource: 'CC/DP',
    unitPrice: 0.25,
    stockLevel: 3000,
    minLevel: 800,
    maxLevel: 8000,
    status: 'Active',
    createdAt: '2024-01-15',
    updatedAt: '2024-12-01'
  },
  {
    id: 'drug-118',
    drugCode: 'RHE-003',
    drugName: 'Hydroxychloroquine 200mg Tablet',
    dosageForm: 'Tablet',
    sku: 'HYD-200-TAB',
    category: 'Rheumatology',
    supplier: 'Global Medical',
    budgetSource: 'APPL',
    unitPrice: 0.35,
    stockLevel: 4000,
    minLevel: 1000,
    maxLevel: 10000,
    status: 'Active',
    createdAt: '2024-01-18',
    updatedAt: '2024-12-01'
  },
  {
    id: 'drug-119',
    drugCode: 'RHE-004',
    drugName: 'Leflunomide 20mg Tablet',
    dosageForm: 'Tablet',
    sku: 'LEF-20-TAB',
    category: 'Rheumatology',
    supplier: 'Prime Health Corp',
    budgetSource: 'CC/DP',
    unitPrice: 1.20,
    stockLevel: 1500,
    minLevel: 400,
    maxLevel: 4000,
    status: 'Active',
    createdAt: '2024-02-01',
    updatedAt: '2024-12-01'
  },
  {
    id: 'drug-120',
    drugCode: 'RHE-005',
    drugName: 'Etanercept 50mg Injection',
    dosageForm: 'Injection',
    sku: 'ETA-50-INJ',
    category: 'Rheumatology',
    supplier: 'MediCare Solutions',
    budgetSource: 'APPL',
    unitPrice: 450.00,
    stockLevel: 20,
    minLevel: 4,
    maxLevel: 40,
    status: 'Active',
    createdAt: '2024-02-05',
    updatedAt: '2024-12-01'
  },

  // Additional categories to reach 200 total...
  // I'll continue with more categories in the next part
];
