import type { DrugItem, DrugCatalogStats } from '../types/DrugItem';
import { extendedDrugItems } from './drugDataExtended';

// Comprehensive drug database with 200 different pharmaceutical items
export const drugItems: DrugItem[] = [
  // Cardiovascular Drugs
  {
    id: 'drug-001',
    drugCode: 'CV-001',
    drugName: 'Amlodipine 5mg Tablet',
    dosageForm: 'Tablet',
    sku: 'AML-5-TAB',
    category: 'Cardiovascular',
    supplier: 'PharmaCorp Malaysia',
    budgetSource: 'APPL',
    unitPrice: 0.15,
    stockLevel: 5000,
    minLevel: 1000,
    maxLevel: 10000,
    status: 'Active',
    createdAt: '2024-01-15',
    updatedAt: '2024-12-01'
  },
  {
    id: 'drug-002',
    drugCode: 'CV-002',
    drugName: 'Metoprolol 50mg Tablet',
    dosageForm: 'Tablet',
    sku: 'MET-50-TAB',
    category: 'Cardiovascular',
    supplier: 'MediSupply Sdn Bhd',
    budgetSource: 'CC/DP',
    unitPrice: 0.25,
    stockLevel: 3000,
    minLevel: 800,
    maxLevel: 8000,
    status: 'Active',
    createdAt: '2024-01-20',
    updatedAt: '2024-12-01'
  },
  {
    id: 'drug-003',
    drugCode: 'CV-003',
    drugName: 'Lisinopril 10mg Tablet',
    dosageForm: 'Tablet',
    sku: 'LIS-10-TAB',
    category: 'Cardiovascular',
    supplier: 'BioPharm Solutions',
    budgetSource: 'LP',
    unitPrice: 0.18,
    stockLevel: 4000,
    minLevel: 1200,
    maxLevel: 12000,
    status: 'Active',
    createdAt: '2024-02-01',
    updatedAt: '2024-12-01'
  },
  {
    id: 'drug-004',
    drugCode: 'CV-004',
    drugName: 'Atorvastatin 20mg Tablet',
    dosageForm: 'Tablet',
    sku: 'ATO-20-TAB',
    category: 'Cardiovascular',
    supplier: 'Global Medical',
    budgetSource: 'CC/DP',
    unitPrice: 0.35,
    stockLevel: 2500,
    minLevel: 600,
    maxLevel: 6000,
    status: 'Active',
    createdAt: '2024-02-10',
    updatedAt: '2024-12-01'
  },
  {
    id: 'drug-005',
    drugCode: 'CV-005',
    drugName: 'Simvastatin 40mg Tablet',
    dosageForm: 'Tablet',
    sku: 'SIM-40-TAB',
    category: 'Cardiovascular',
    supplier: 'Prime Health Corp',
    budgetSource: 'LP',
    unitPrice: 0.28,
    stockLevel: 3500,
    minLevel: 900,
    maxLevel: 9000,
    status: 'Active',
    createdAt: '2024-02-15',
    updatedAt: '2024-12-01'
  },
  {
    id: 'drug-006',
    drugCode: 'CV-006',
    drugName: 'Digoxin 0.25mg Tablet',
    dosageForm: 'Tablet',
    sku: 'DIG-025-TAB',
    category: 'Cardiovascular',
    supplier: 'MediCare Solutions',
    budgetSource: 'CC/DP',
    unitPrice: 0.12,
    stockLevel: 1500,
    minLevel: 300,
    maxLevel: 3000,
    status: 'Active',
    createdAt: '2024-03-01',
    updatedAt: '2024-12-01'
  },
  {
    id: 'drug-007',
    drugCode: 'CV-007',
    drugName: 'Furosemide 40mg Tablet',
    dosageForm: 'Tablet',
    sku: 'FUR-40-TAB',
    category: 'Cardiovascular',
    supplier: 'PharmaCorp Malaysia',
    budgetSource: 'APPL',
    unitPrice: 0.08,
    stockLevel: 6000,
    minLevel: 1500,
    maxLevel: 15000,
    status: 'Active',
    createdAt: '2024-03-05',
    updatedAt: '2024-12-01'
  },
  {
    id: 'drug-008',
    drugCode: 'CV-008',
    drugName: 'Spironolactone 25mg Tablet',
    dosageForm: 'Tablet',
    sku: 'SPI-25-TAB',
    category: 'Cardiovascular',
    supplier: 'BioPharm Solutions',
    budgetSource: 'CC/DP',
    unitPrice: 0.22,
    stockLevel: 2000,
    minLevel: 500,
    maxLevel: 5000,
    status: 'Active',
    createdAt: '2024-03-10',
    updatedAt: '2024-12-01'
  },
  {
    id: 'drug-009',
    drugCode: 'CV-009',
    drugName: 'Warfarin 5mg Tablet',
    dosageForm: 'Tablet',
    sku: 'WAR-5-TAB',
    category: 'Cardiovascular',
    supplier: 'Global Medical',
    budgetSource: 'APPL',
    unitPrice: 0.15,
    stockLevel: 1800,
    minLevel: 400,
    maxLevel: 4000,
    status: 'Active',
    createdAt: '2024-03-15',
    updatedAt: '2024-12-01'
  },
  {
    id: 'drug-010',
    drugCode: 'CV-010',
    drugName: 'Clopidogrel 75mg Tablet',
    dosageForm: 'Tablet',
    sku: 'CLO-75-TAB',
    category: 'Cardiovascular',
    supplier: 'Prime Health Corp',
    budgetSource: 'CC/DP',
    unitPrice: 0.45,
    stockLevel: 2200,
    minLevel: 600,
    maxLevel: 6000,
    status: 'Active',
    createdAt: '2024-03-20',
    updatedAt: '2024-12-01'
  },

  // Antibiotics
  {
    id: 'drug-011',
    drugCode: 'AB-001',
    drugName: 'Amoxicillin 500mg Capsule',
    dosageForm: 'Capsule',
    sku: 'AMX-500-CAP',
    category: 'Antibiotic',
    supplier: 'MediSupply Sdn Bhd',
    budgetSource: 'APPL',
    unitPrice: 0.20,
    stockLevel: 8000,
    minLevel: 2000,
    maxLevel: 20000,
    status: 'Active',
    createdAt: '2024-01-10',
    updatedAt: '2024-12-01'
  },
  {
    id: 'drug-012',
    drugCode: 'AB-002',
    drugName: 'Ciprofloxacin 500mg Tablet',
    dosageForm: 'Tablet',
    sku: 'CIP-500-TAB',
    category: 'Antibiotic',
    supplier: 'BioPharm Solutions',
    budgetSource: 'CC/DP',
    unitPrice: 0.35,
    stockLevel: 4000,
    minLevel: 1000,
    maxLevel: 10000,
    status: 'Active',
    createdAt: '2024-01-15',
    updatedAt: '2024-12-01'
  },
  {
    id: 'drug-013',
    drugCode: 'AB-003',
    drugName: 'Azithromycin 250mg Tablet',
    dosageForm: 'Tablet',
    sku: 'AZI-250-TAB',
    category: 'Antibiotic',
    supplier: 'Global Medical',
    budgetSource: 'APPL',
    unitPrice: 0.28,
    stockLevel: 3500,
    minLevel: 800,
    maxLevel: 8000,
    status: 'Active',
    createdAt: '2024-01-20',
    updatedAt: '2024-12-01'
  },
  {
    id: 'drug-014',
    drugCode: 'AB-004',
    drugName: 'Cefalexin 500mg Capsule',
    dosageForm: 'Capsule',
    sku: 'CEF-500-CAP',
    category: 'Antibiotic',
    supplier: 'Prime Health Corp',
    budgetSource: 'CC/DP',
    unitPrice: 0.25,
    stockLevel: 5000,
    minLevel: 1200,
    maxLevel: 12000,
    status: 'Active',
    createdAt: '2024-02-01',
    updatedAt: '2024-12-01'
  },
  {
    id: 'drug-015',
    drugCode: 'AB-005',
    drugName: 'Doxycycline 100mg Capsule',
    dosageForm: 'Capsule',
    sku: 'DOX-100-CAP',
    category: 'Antibiotic',
    supplier: 'MediCare Solutions',
    budgetSource: 'APPL',
    unitPrice: 0.18,
    stockLevel: 3000,
    minLevel: 700,
    maxLevel: 7000,
    status: 'Active',
    createdAt: '2024-02-05',
    updatedAt: '2024-12-01'
  },
  {
    id: 'drug-016',
    drugCode: 'AB-006',
    drugName: 'Metronidazole 400mg Tablet',
    dosageForm: 'Tablet',
    sku: 'MET-400-TAB',
    category: 'Antibiotic',
    supplier: 'PharmaCorp Malaysia',
    budgetSource: 'CC/DP',
    unitPrice: 0.12,
    stockLevel: 6000,
    minLevel: 1500,
    maxLevel: 15000,
    status: 'Active',
    createdAt: '2024-02-10',
    updatedAt: '2024-12-01'
  },
  {
    id: 'drug-017',
    drugCode: 'AB-007',
    drugName: 'Clindamycin 300mg Capsule',
    dosageForm: 'Capsule',
    sku: 'CLI-300-CAP',
    category: 'Antibiotic',
    supplier: 'BioPharm Solutions',
    budgetSource: 'APPL',
    unitPrice: 0.40,
    stockLevel: 2000,
    minLevel: 500,
    maxLevel: 5000,
    status: 'Active',
    createdAt: '2024-02-15',
    updatedAt: '2024-12-01'
  },
  {
    id: 'drug-018',
    drugCode: 'AB-008',
    drugName: 'Vancomycin 500mg Injection',
    dosageForm: 'Injection',
    sku: 'VAN-500-INJ',
    category: 'Antibiotic',
    supplier: 'Global Medical',
    budgetSource: 'CC/DP',
    unitPrice: 15.50,
    stockLevel: 500,
    minLevel: 100,
    maxLevel: 1000,
    status: 'Active',
    createdAt: '2024-02-20',
    updatedAt: '2024-12-01'
  },
  {
    id: 'drug-019',
    drugCode: 'AB-009',
    drugName: 'Gentamicin 80mg Injection',
    dosageForm: 'Injection',
    sku: 'GEN-80-INJ',
    category: 'Antibiotic',
    supplier: 'Prime Health Corp',
    budgetSource: 'APPL',
    unitPrice: 2.80,
    stockLevel: 800,
    minLevel: 200,
    maxLevel: 2000,
    status: 'Active',
    createdAt: '2024-03-01',
    updatedAt: '2024-12-01'
  },
  {
    id: 'drug-020',
    drugCode: 'AB-010',
    drugName: 'Ceftriaxone 1g Injection',
    dosageForm: 'Injection',
    sku: 'CEF-1G-INJ',
    category: 'Antibiotic',
    supplier: 'MediSupply Sdn Bhd',
    budgetSource: 'CC/DP',
    unitPrice: 8.50,
    stockLevel: 600,
    minLevel: 150,
    maxLevel: 1500,
    status: 'Active',
    createdAt: '2024-03-05',
    updatedAt: '2024-12-01'
  },

  // Pain Management
  {
    id: 'drug-021',
    drugCode: 'PM-001',
    drugName: 'Paracetamol 500mg Tablet',
    dosageForm: 'Tablet',
    sku: 'PAR-500-TAB',
    category: 'Pain Management',
    supplier: 'MediCare Solutions',
    budgetSource: 'APPL',
    unitPrice: 0.05,
    stockLevel: 15000,
    minLevel: 5000,
    maxLevel: 50000,
    status: 'Active',
    createdAt: '2024-01-05',
    updatedAt: '2024-12-01'
  },
  {
    id: 'drug-022',
    drugCode: 'PM-002',
    drugName: 'Ibuprofen 400mg Tablet',
    dosageForm: 'Tablet',
    sku: 'IBU-400-TAB',
    category: 'Pain Management',
    supplier: 'PharmaCorp Malaysia',
    budgetSource: 'CC/DP',
    unitPrice: 0.08,
    stockLevel: 12000,
    minLevel: 3000,
    maxLevel: 30000,
    status: 'Active',
    createdAt: '2024-01-10',
    updatedAt: '2024-12-01'
  },
  {
    id: 'drug-023',
    drugCode: 'PM-003',
    drugName: 'Tramadol 50mg Capsule',
    dosageForm: 'Capsule',
    sku: 'TRA-50-CAP',
    category: 'Pain Management',
    supplier: 'BioPharm Solutions',
    budgetSource: 'APPL',
    unitPrice: 0.35,
    stockLevel: 3000,
    minLevel: 800,
    maxLevel: 8000,
    status: 'Active',
    createdAt: '2024-01-15',
    updatedAt: '2024-12-01'
  },
  {
    id: 'drug-024',
    drugCode: 'PM-004',
    drugName: 'Morphine 10mg Injection',
    dosageForm: 'Injection',
    sku: 'MOR-10-INJ',
    category: 'Pain Management',
    supplier: 'Global Medical',
    budgetSource: 'CC/DP',
    unitPrice: 12.50,
    stockLevel: 200,
    minLevel: 50,
    maxLevel: 500,
    status: 'Active',
    createdAt: '2024-01-20',
    updatedAt: '2024-12-01'
  },
  {
    id: 'drug-025',
    drugCode: 'PM-005',
    drugName: 'Codeine 30mg Tablet',
    dosageForm: 'Tablet',
    sku: 'COD-30-TAB',
    category: 'Pain Management',
    supplier: 'Prime Health Corp',
    budgetSource: 'APPL',
    unitPrice: 0.25,
    stockLevel: 2500,
    minLevel: 600,
    maxLevel: 6000,
    status: 'Active',
    createdAt: '2024-02-01',
    updatedAt: '2024-12-01'
  },
  {
    id: 'drug-026',
    drugCode: 'PM-006',
    drugName: 'Diclofenac 50mg Tablet',
    dosageForm: 'Tablet',
    sku: 'DIC-50-TAB',
    category: 'Pain Management',
    supplier: 'MediSupply Sdn Bhd',
    budgetSource: 'CC/DP',
    unitPrice: 0.15,
    stockLevel: 4000,
    minLevel: 1000,
    maxLevel: 10000,
    status: 'Active',
    createdAt: '2024-02-05',
    updatedAt: '2024-12-01'
  },
  {
    id: 'drug-027',
    drugCode: 'PM-007',
    drugName: 'Naproxen 500mg Tablet',
    dosageForm: 'Tablet',
    sku: 'NAP-500-TAB',
    category: 'Pain Management',
    supplier: 'MediCare Solutions',
    budgetSource: 'APPL',
    unitPrice: 0.18,
    stockLevel: 3500,
    minLevel: 900,
    maxLevel: 9000,
    status: 'Active',
    createdAt: '2024-02-10',
    updatedAt: '2024-12-01'
  },
  {
    id: 'drug-028',
    drugCode: 'PM-008',
    drugName: 'Ketorolac 10mg Injection',
    dosageForm: 'Injection',
    sku: 'KET-10-INJ',
    category: 'Pain Management',
    supplier: 'BioPharm Solutions',
    budgetSource: 'CC/DP',
    unitPrice: 3.50,
    stockLevel: 600,
    minLevel: 150,
    maxLevel: 1500,
    status: 'Active',
    createdAt: '2024-02-15',
    updatedAt: '2024-12-01'
  },
  {
    id: 'drug-029',
    drugCode: 'PM-009',
    drugName: 'Pregabalin 75mg Capsule',
    dosageForm: 'Capsule',
    sku: 'PRE-75-CAP',
    category: 'Pain Management',
    supplier: 'Global Medical',
    budgetSource: 'APPL',
    unitPrice: 0.45,
    stockLevel: 1800,
    minLevel: 400,
    maxLevel: 4000,
    status: 'Active',
    createdAt: '2024-02-20',
    updatedAt: '2024-12-01'
  },
  {
    id: 'drug-030',
    drugCode: 'PM-010',
    drugName: 'Gabapentin 300mg Capsule',
    dosageForm: 'Capsule',
    sku: 'GAB-300-CAP',
    category: 'Pain Management',
    supplier: 'Prime Health Corp',
    budgetSource: 'CC/DP',
    unitPrice: 0.30,
    stockLevel: 2200,
    minLevel: 600,
    maxLevel: 6000,
    status: 'Active',
    createdAt: '2024-03-01',
    updatedAt: '2024-12-01'
  },

  // Diabetes Management
  {
    id: 'drug-031',
    drugCode: 'DM-001',
    drugName: 'Metformin 500mg Tablet',
    dosageForm: 'Tablet',
    sku: 'MET-500-TAB',
    category: 'Diabetes',
    supplier: 'MediSupply Sdn Bhd',
    budgetSource: 'APPL',
    unitPrice: 0.12,
    stockLevel: 10000,
    minLevel: 2500,
    maxLevel: 25000,
    status: 'Active',
    createdAt: '2024-01-08',
    updatedAt: '2024-12-01'
  },
  {
    id: 'drug-032',
    drugCode: 'DM-002',
    drugName: 'Glibenclamide 5mg Tablet',
    dosageForm: 'Tablet',
    sku: 'GLI-5-TAB',
    category: 'Diabetes',
    supplier: 'BioPharm Solutions',
    budgetSource: 'CC/DP',
    unitPrice: 0.08,
    stockLevel: 6000,
    minLevel: 1500,
    maxLevel: 15000,
    status: 'Active',
    createdAt: '2024-01-12',
    updatedAt: '2024-12-01'
  },
  {
    id: 'drug-033',
    drugCode: 'DM-003',
    drugName: 'Insulin Glargine 100 units/ml',
    dosageForm: 'Injection',
    sku: 'INS-GLA-100',
    category: 'Diabetes',
    supplier: 'Global Medical',
    budgetSource: 'APPL',
    unitPrice: 25.00,
    stockLevel: 300,
    minLevel: 100,
    maxLevel: 1000,
    status: 'Active',
    createdAt: '2024-01-15',
    updatedAt: '2024-12-01'
  },
  {
    id: 'drug-034',
    drugCode: 'DM-004',
    drugName: 'Insulin Regular 100 units/ml',
    dosageForm: 'Injection',
    sku: 'INS-REG-100',
    category: 'Diabetes',
    supplier: 'Prime Health Corp',
    budgetSource: 'CC/DP',
    unitPrice: 18.50,
    stockLevel: 400,
    minLevel: 150,
    maxLevel: 1200,
    status: 'Active',
    createdAt: '2024-01-18',
    updatedAt: '2024-12-01'
  },
  {
    id: 'drug-035',
    drugCode: 'DM-005',
    drugName: 'Gliclazide 80mg Tablet',
    dosageForm: 'Tablet',
    sku: 'GLI-80-TAB',
    category: 'Diabetes',
    supplier: 'MediCare Solutions',
    budgetSource: 'APPL',
    unitPrice: 0.15,
    stockLevel: 5000,
    minLevel: 1200,
    maxLevel: 12000,
    status: 'Active',
    createdAt: '2024-02-01',
    updatedAt: '2024-12-01'
  },
  {
    id: 'drug-036',
    drugCode: 'DM-006',
    drugName: 'Pioglitazone 30mg Tablet',
    dosageForm: 'Tablet',
    sku: 'PIO-30-TAB',
    category: 'Diabetes',
    supplier: 'PharmaCorp Malaysia',
    budgetSource: 'CC/DP',
    unitPrice: 0.35,
    stockLevel: 2500,
    minLevel: 600,
    maxLevel: 6000,
    status: 'Active',
    createdAt: '2024-02-05',
    updatedAt: '2024-12-01'
  },
  {
    id: 'drug-037',
    drugCode: 'DM-007',
    drugName: 'Sitagliptin 100mg Tablet',
    dosageForm: 'Tablet',
    sku: 'SIT-100-TAB',
    category: 'Diabetes',
    supplier: 'BioPharm Solutions',
    budgetSource: 'APPL',
    unitPrice: 1.20,
    stockLevel: 1800,
    minLevel: 400,
    maxLevel: 4000,
    status: 'Active',
    createdAt: '2024-02-10',
    updatedAt: '2024-12-01'
  },
  {
    id: 'drug-038',
    drugCode: 'DM-008',
    drugName: 'Empagliflozin 10mg Tablet',
    dosageForm: 'Tablet',
    sku: 'EMP-10-TAB',
    category: 'Diabetes',
    supplier: 'Global Medical',
    budgetSource: 'CC/DP',
    unitPrice: 2.50,
    stockLevel: 1200,
    minLevel: 300,
    maxLevel: 3000,
    status: 'Active',
    createdAt: '2024-02-15',
    updatedAt: '2024-12-01'
  },
  {
    id: 'drug-039',
    drugCode: 'DM-009',
    drugName: 'Dapagliflozin 10mg Tablet',
    dosageForm: 'Tablet',
    sku: 'DAP-10-TAB',
    category: 'Diabetes',
    supplier: 'Prime Health Corp',
    budgetSource: 'APPL',
    unitPrice: 2.80,
    stockLevel: 1000,
    minLevel: 250,
    maxLevel: 2500,
    status: 'Active',
    createdAt: '2024-02-20',
    updatedAt: '2024-12-01'
  },
  {
    id: 'drug-040',
    drugCode: 'DM-010',
    drugName: 'Linagliptin 5mg Tablet',
    dosageForm: 'Tablet',
    sku: 'LIN-5-TAB',
    category: 'Diabetes',
    supplier: 'MediSupply Sdn Bhd',
    budgetSource: 'CC/DP',
    unitPrice: 1.50,
    stockLevel: 1500,
    minLevel: 400,
    maxLevel: 4000,
    status: 'Active',
    createdAt: '2024-03-01',
    updatedAt: '2024-12-01'
  },

  // Respiratory Drugs
  {
    id: 'drug-041',
    drugCode: 'RS-001',
    drugName: 'Salbutamol 100mcg Inhaler',
    dosageForm: 'Inhaler',
    sku: 'SAL-100-INF',
    category: 'Respiratory',
    supplier: 'MediCare Solutions',
    budgetSource: 'APPL',
    unitPrice: 8.50,
    stockLevel: 500,
    minLevel: 100,
    maxLevel: 1000,
    status: 'Active',
    createdAt: '2024-01-10',
    updatedAt: '2024-12-01'
  },
  {
    id: 'drug-042',
    drugCode: 'RS-002',
    drugName: 'Budesonide 200mcg Inhaler',
    dosageForm: 'Inhaler',
    sku: 'BUD-200-INF',
    category: 'Respiratory',
    supplier: 'PharmaCorp Malaysia',
    budgetSource: 'CC/DP',
    unitPrice: 12.00,
    stockLevel: 400,
    minLevel: 80,
    maxLevel: 800,
    status: 'Active',
    createdAt: '2024-01-15',
    updatedAt: '2024-12-01'
  },
  {
    id: 'drug-043',
    drugCode: 'RS-003',
    drugName: 'Theophylline 200mg Tablet',
    dosageForm: 'Tablet',
    sku: 'THE-200-TAB',
    category: 'Respiratory',
    supplier: 'BioPharm Solutions',
    budgetSource: 'APPL',
    unitPrice: 0.25,
    stockLevel: 3000,
    minLevel: 800,
    maxLevel: 8000,
    status: 'Active',
    createdAt: '2024-01-20',
    updatedAt: '2024-12-01'
  },
  {
    id: 'drug-044',
    drugCode: 'RS-004',
    drugName: 'Montelukast 10mg Tablet',
    dosageForm: 'Tablet',
    sku: 'MON-10-TAB',
    category: 'Respiratory',
    supplier: 'Global Medical',
    budgetSource: 'CC/DP',
    unitPrice: 0.45,
    stockLevel: 2500,
    minLevel: 600,
    maxLevel: 6000,
    status: 'Active',
    createdAt: '2024-02-01',
    updatedAt: '2024-12-01'
  },
  {
    id: 'drug-045',
    drugCode: 'RS-005',
    drugName: 'Prednisolone 5mg Tablet',
    dosageForm: 'Tablet',
    sku: 'PRE-5-TAB',
    category: 'Respiratory',
    supplier: 'Prime Health Corp',
    budgetSource: 'APPL',
    unitPrice: 0.08,
    stockLevel: 8000,
    minLevel: 2000,
    maxLevel: 20000,
    status: 'Active',
    createdAt: '2024-02-05',
    updatedAt: '2024-12-01'
  },
  {
    id: 'drug-046',
    drugCode: 'RS-006',
    drugName: 'Ipratropium 20mcg Inhaler',
    dosageForm: 'Inhaler',
    sku: 'IPR-20-INF',
    category: 'Respiratory',
    supplier: 'MediSupply Sdn Bhd',
    budgetSource: 'CC/DP',
    unitPrice: 6.50,
    stockLevel: 350,
    minLevel: 70,
    maxLevel: 700,
    status: 'Active',
    createdAt: '2024-02-10',
    updatedAt: '2024-12-01'
  },
  {
    id: 'drug-047',
    drugCode: 'RS-007',
    drugName: 'Formoterol 12mcg Inhaler',
    dosageForm: 'Inhaler',
    sku: 'FOR-12-INF',
    category: 'Respiratory',
    supplier: 'MediCare Solutions',
    budgetSource: 'APPL',
    unitPrice: 15.50,
    stockLevel: 300,
    minLevel: 60,
    maxLevel: 600,
    status: 'Active',
    createdAt: '2024-02-15',
    updatedAt: '2024-12-01'
  },
  {
    id: 'drug-048',
    drugCode: 'RS-008',
    drugName: 'Aminophylline 200mg Injection',
    dosageForm: 'Injection',
    sku: 'AMI-200-INJ',
    category: 'Respiratory',
    supplier: 'BioPharm Solutions',
    budgetSource: 'CC/DP',
    unitPrice: 2.20,
    stockLevel: 500,
    minLevel: 100,
    maxLevel: 1000,
    status: 'Active',
    createdAt: '2024-02-20',
    updatedAt: '2024-12-01'
  },
  {
    id: 'drug-049',
    drugCode: 'RS-009',
    drugName: 'Hydrocortisone 100mg Injection',
    dosageForm: 'Injection',
    sku: 'HYD-100-INJ',
    category: 'Respiratory',
    supplier: 'Global Medical',
    budgetSource: 'APPL',
    unitPrice: 3.50,
    stockLevel: 400,
    minLevel: 80,
    maxLevel: 800,
    status: 'Active',
    createdAt: '2024-03-01',
    updatedAt: '2024-12-01'
  },
  {
    id: 'drug-050',
    drugCode: 'RS-010',
    drugName: 'Beclomethasone 50mcg Inhaler',
    dosageForm: 'Inhaler',
    sku: 'BEC-50-INF',
    category: 'Respiratory',
    supplier: 'Prime Health Corp',
    budgetSource: 'CC/DP',
    unitPrice: 9.50,
    stockLevel: 450,
    minLevel: 90,
    maxLevel: 900,
    status: 'Active',
    createdAt: '2024-03-05',
    updatedAt: '2024-12-01'
  },
  ...extendedDrugItems
];

export function getDrugStats(): DrugCatalogStats {
  const categories = [...new Set(drugItems.map(item => item.category))];
  const suppliers = [...new Set(drugItems.map(item => item.supplier))];
  const budgetSources = [...new Set(drugItems.map(item => item.budgetSource))];
  
  return {
    totalItems: drugItems.length,
    activeItems: drugItems.filter(item => item.status === 'Active').length,
    inactiveItems: drugItems.filter(item => item.status === 'Inactive').length,
    discontinuedItems: drugItems.filter(item => item.status === 'Discontinued').length,
    categories,
    suppliers,
    budgetSources
  };
}

export function getDrugItems(filters?: Partial<DrugCatalogFilters>): DrugItem[] {
  let filteredItems = [...drugItems];
  
  if (filters) {
    if (filters.search) {
      const searchLower = filters.search.toLowerCase();
      filteredItems = filteredItems.filter(item => 
        item.drugName.toLowerCase().includes(searchLower) ||
        item.drugCode.toLowerCase().includes(searchLower) ||
        item.sku.toLowerCase().includes(searchLower)
      );
    }
    
    if (filters.category) {
      filteredItems = filteredItems.filter(item => item.category === filters.category);
    }
    
    if (filters.supplier) {
      filteredItems = filteredItems.filter(item => item.supplier === filters.supplier);
    }
    
    if (filters.budgetSource) {
      filteredItems = filteredItems.filter(item => item.budgetSource === filters.budgetSource);
    }
    
    if (filters.status) {
      filteredItems = filteredItems.filter(item => item.status === filters.status);
    }
    
    if (filters.dosageForm) {
      filteredItems = filteredItems.filter(item => item.dosageForm === filters.dosageForm);
    }
  }
  
  return filteredItems;
}
