-- Add missing therapeutic classes if they don't already exist
INSERT INTO public.drug_categories (hospital_id, category_code, category_name, description, updated_at)
VALUES 
    (NULL, 'ANTIVIRAL', 'Antivirals', 'Medications for viral infections', NOW()),
    (NULL, 'ANTIFUNGAL', 'Antifungals', 'Medications for fungal infections', NOW()),
    (NULL, 'ANTIPROTOZOAL_ANTIMALARIAL', 'Antiprotozoals & Antimalarials', 'Medications for protozoal and malarial infections', NOW()),
    (NULL, 'ANTHELMINTIC', 'Anthelmintics', 'Medications for parasitic worm infections', NOW()),
    (NULL, 'ANALGESIC_NON_OPIOID', 'Analgesics (Non-Opioid/Antipyretics)', 'Pain relief and fever medications excluding opioids', NOW()),
    (NULL, 'ANALGESIC_GENERAL', 'Analgesics', 'General pain relief medications', NOW()),
    (NULL, 'TC_NSAID', 'NSAIDs', 'Non-steroidal anti-inflammatory drugs', NOW()),
    (NULL, 'ANTIEPILEPTIC', 'Antiepileptics', 'Medications for seizures and epilepsy', NOW()),
    (NULL, 'STEROID', 'Steroid', 'Steroidal medications', NOW()),
    (NULL, 'HYPNOTIC_SEDATIVE', 'Hypnotics & Sedatives', 'Medications for sleep and sedation', NOW()),
    (NULL, 'ANTIDEPRESSANT', 'Antidepressants', 'Medications for depression', NOW()),
    (NULL, 'ANTIPSYCHOTIC', 'Antipsychotics', 'Medications for psychotic disorders', NOW()),
    (NULL, 'ANTIPARKINSONIAN', 'Antiparkinsonian Drugs', 'Medications for Parkinson''s disease', NOW()),
    (NULL, 'ANTIASTHMATIC_BRONCHODILATOR', 'Antiasthmatics & Bronchodilators', 'Medications for asthma and respiratory relief', NOW()),
    (NULL, 'ANTIHISTAMINE', 'Antihistamines', 'Medications for allergies', NOW()),
    (NULL, 'COUGH_COLD_PREPARATION', 'Cough & Cold Preparations', 'Medications for cough and cold symptoms', NOW()),
    (NULL, 'NASAL_DECONGESTANT', 'Nasal Decongestants', 'Medications for nasal congestion', NOW()),
    (NULL, 'MUSCLE_RELAXANT', 'Muscle Relaxants', 'Medications for muscle spasms', NOW()),
    (NULL, 'ANTIGOUT', 'Antigout Preparations', 'Medications for gout', NOW()),
    (NULL, 'HORMONE_ENDOCRINE', 'Hormones & Endocrine', 'Medications for hormonal and endocrine disorders', NOW()),
    (NULL, 'CONTRACEPTIVE', 'Contraceptives', 'Birth control medications', NOW()),
    (NULL, 'OPHTHALMIC', 'Ophthalmic (Eye) Preparations', 'Eye care medications', NOW()),
    (NULL, 'OTOLOGICAL', 'Otological (Ear) Preparations', 'Ear care medications', NOW()),
    (NULL, 'CYTOTOXIC', 'Cytotoxic Chemotherapy', 'Medications for cancer treatment', NOW()),
    (NULL, 'HUMAN_INSULIN', 'Human Insulin', 'Standard human insulin products', NOW()),
    (NULL, 'INSULIN_ANALOGUE', 'Insulin Analogues', 'Modified insulin products', NOW()),
    (NULL, 'TC_ANTI_TUBERCULOSIS', 'Anti-Tuberculosis (Anti-TB)', 'Medications for tuberculosis treatment', NOW()),
    (NULL, 'IMMUNOSUPPRESSANT', 'Immunosuppressants', 'Medications that suppress the immune system', NOW()),
    (NULL, 'THROMBOLYTIC_FIBRINOLYTIC', 'Thrombolytics / Fibrinolytics', 'Medications used to dissolve blood clots', NOW()),
    (NULL, 'ANTIPLATELET', 'Anti-Platelet', 'Medications that prevent blood clot formation', NOW()),
    (NULL, 'ANTICOAGULANT', 'Anti-Coagulant', 'Medications that slow down blood clotting', NOW()),
    (NULL, 'ANTI_ANAEMIA', 'Anti-Anaemia', 'Medications for the treatment of anaemia', NOW())
ON CONFLICT (hospital_id, category_code) DO NOTHING;
