import type {
  DialysisPatient,
  DialysisSession,
  DialysisMachine,
  HaemodialysisStats,
  DialysisStaff,
} from '../types/Haemodialysis';

const today = new Date();

// Mock Dialysis Patients
export const mockDialysisPatients: DialysisPatient[] = [
  {
    id: 'HD001',
    patientMRN: 'MRN-HD-00123',
    patientName: 'Ahmad bin Hassan',
    patientIC: '650615-10-5234',
    dateOfBirth: new Date('1965-06-15'),
    age: 59,
    gender: 'Male',
    contactNumber: '012-3456789',
    diagnosis: 'End-Stage Renal Disease (ESRD) secondary to Diabetic Nephropathy',
    comorbidities: ['Type 2 Diabetes Mellitus', 'Hypertension', 'Ischemic Heart Disease'],
    allergies: ['Penicillin'],
    bloodType: 'O+',
    dialysisStartDate: new Date('2020-03-15'),
    dialysisDuration: 4.8,
    schedule: 'Monday-Wednesday-Friday',
    sessionDuration: 4,
    accessType: 'AVF',
    accessSite: 'Left radiocephalic fistula',
    accessCreationDate: new Date('2020-01-10'),
    dryWeight: 65.0,
    dialysateFlow: 500,
    bloodFlow: 300,
    dialyzer: 'Fresenius F8HPS',
    heparinDose: 2000,
    lastKtV: 1.4,
    lastURR: 72,
    adequacy: 'adequate',
    lastSessionDate: new Date('2025-01-03'),
    lastPreWeight: 67.5,
    lastPostWeight: 65.2,
    lastUltrafiltration: 2.3,
    emergencyContactName: 'Fatimah binti Ahmad (Wife)',
    emergencyContactRelation: 'Spouse',
    emergencyContactNumber: '013-9876543',
    isActive: true,
    notes: 'Good compliance, stable patient',
  },
  {
    id: 'HD002',
    patientMRN: 'MRN-HD-00456',
    patientName: 'Lim Ah Moi',
    patientIC: '720824-08-2341',
    dateOfBirth: new Date('1972-08-24'),
    age: 52,
    gender: 'Female',
    contactNumber: '016-2345678',
    diagnosis: 'ESRD secondary to Chronic Glomerulonephritis',
    comorbidities: ['Hypertension', 'Anemia'],
    allergies: [],
    bloodType: 'A+',
    dialysisStartDate: new Date('2021-06-20'),
    dialysisDuration: 3.5,
    schedule: 'Tuesday-Thursday-Saturday',
    sessionDuration: 4,
    accessType: 'AVF',
    accessSite: 'Right brachiocephalic fistula',
    accessCreationDate: new Date('2021-04-15'),
    dryWeight: 52.0,
    dialysateFlow: 500,
    bloodFlow: 280,
    dialyzer: 'Gambro Polyflux 170H',
    heparinDose: 1500,
    lastKtV: 1.5,
    lastURR: 75,
    adequacy: 'adequate',
    lastSessionDate: new Date('2025-01-04'),
    lastPreWeight: 54.8,
    lastPostWeight: 52.3,
    lastUltrafiltration: 2.5,
    emergencyContactName: 'Lim Wei Chong (Son)',
    emergencyContactRelation: 'Child',
    emergencyContactNumber: '011-88776655',
    isActive: true,
  },
  {
    id: 'HD003',
    patientMRN: 'MRN-HD-00789',
    patientName: 'Kumar s/o Suppiah',
    patientIC: '580405-05-3456',
    dateOfBirth: new Date('1958-04-05'),
    age: 66,
    gender: 'Male',
    contactNumber: '019-4445555',
    diagnosis: 'ESRD secondary to Hypertensive Nephropathy',
    comorbidities: ['Hypertension', 'Dyslipidemia', 'Gout'],
    allergies: ['Sulfa drugs'],
    bloodType: 'B+',
    dialysisStartDate: new Date('2018-09-01'),
    dialysisDuration: 6.3,
    schedule: 'Monday-Wednesday-Friday',
    sessionDuration: 4,
    accessType: 'permcath',
    accessSite: 'Right internal jugular vein',
    accessCreationDate: new Date('2024-11-15'),
    dryWeight: 70.0,
    dialysateFlow: 500,
    bloodFlow: 250,
    dialyzer: 'Fresenius F7HPS',
    heparinDose: 1000,
    lastKtV: 1.2,
    lastURR: 65,
    adequacy: 'borderline',
    lastSessionDate: new Date('2025-01-03'),
    lastPreWeight: 72.8,
    lastPostWeight: 70.5,
    lastUltrafiltration: 2.3,
    emergencyContactName: 'Devi a/p Suppiah (Daughter)',
    emergencyContactRelation: 'Child',
    emergencyContactNumber: '012-6667777',
    isActive: true,
    notes: 'Recent catheter placement due to AVF thrombosis. Plan for new AVF creation',
  },
  {
    id: 'HD004',
    patientMRN: 'MRN-HD-01012',
    patientName: 'Noraini binti Abdullah',
    patientIC: '851218-14-4567',
    dateOfBirth: new Date('1985-12-18'),
    age: 39,
    gender: 'Female',
    contactNumber: '013-7778888',
    diagnosis: 'ESRD secondary to Lupus Nephritis',
    comorbidities: ['Systemic Lupus Erythematosus', 'Hypertension'],
    allergies: ['Contrast media'],
    bloodType: 'AB+',
    dialysisStartDate: new Date('2023-02-10'),
    dialysisDuration: 1.9,
    schedule: 'Tuesday-Thursday-Saturday',
    sessionDuration: 4,
    accessType: 'AVF',
    accessSite: 'Left brachiocephalic fistula',
    accessCreationDate: new Date('2022-12-05'),
    dryWeight: 58.0,
    dialysateFlow: 500,
    bloodFlow: 300,
    dialyzer: 'Fresenius F8HPS',
    heparinDose: 2000,
    lastKtV: 1.6,
    lastURR: 78,
    adequacy: 'adequate',
    lastSessionDate: new Date('2025-01-04'),
    lastPreWeight: 60.2,
    lastPostWeight: 58.1,
    lastUltrafiltration: 2.1,
    emergencyContactName: 'Mohd Rizal bin Hassan (Husband)',
    emergencyContactRelation: 'Spouse',
    emergencyContactNumber: '017-99998888',
    isActive: true,
  },
];

// Mock Dialysis Sessions
export const mockDialysisSessions: DialysisSession[] = [
  {
    id: 'SESS001',
    sessionNumber: 'HD-2025-0001',
    sessionDate: today,
    patientMRN: 'MRN-HD-00123',
    patientName: 'Ahmad bin Hassan',
    scheduledStartTime: '08:00',
    scheduledEndTime: '12:00',
    shift: 'Morning',
    status: 'in-progress',
    machineNumber: 'HD-M01',
    preDialysisTime: new Date(today.setHours(7, 45, 0)),
    preWeight: 67.8,
    preBloodPressure: '145/85',
    prePulse: 78,
    preTemperature: 36.8,
    preAssessmentNotes: 'Patient feels well, no complaints',
    actualStartTime: new Date(today.setHours(8, 5, 0)),
    bloodFlow: 300,
    dialysateFlow: 500,
    heparinBolus: 2000,
    heparinInfusion: 500,
    intradialyticRecords: [
      {
        time: new Date(today.setHours(8, 30, 0)),
        bloodPressure: '140/82',
        pulse: 76,
        ultrafiltrationRate: 600,
        transmembranePressure: 150,
        venousPressure: 120,
        arterialPressure: -180,
      },
      {
        time: new Date(today.setHours(9, 30, 0)),
        bloodPressure: '138/80',
        pulse: 74,
        ultrafiltrationRate: 580,
        transmembranePressure: 148,
        venousPressure: 118,
        arterialPressure: -175,
      },
    ],
    hadComplications: false,
    performedBy: 'Dialysis Nurse Siti',
    supervisedBy: 'Dr. Kumar (Nephrologist)',
  },
  {
    id: 'SESS002',
    sessionNumber: 'HD-2025-0002',
    sessionDate: today,
    patientMRN: 'MRN-HD-00456',
    patientName: 'Lim Ah Moi',
    scheduledStartTime: '14:00',
    scheduledEndTime: '18:00',
    shift: 'Afternoon',
    status: 'scheduled',
    machineNumber: 'HD-M02',
  },
  {
    id: 'SESS003',
    sessionNumber: 'HD-2025-0003',
    sessionDate: today,
    patientMRN: 'MRN-HD-00789',
    patientName: 'Kumar s/o Suppiah',
    scheduledStartTime: '08:00',
    scheduledEndTime: '12:00',
    shift: 'Morning',
    status: 'completed',
    machineNumber: 'HD-M03',
    preDialysisTime: new Date(today.setHours(7, 50, 0)),
    preWeight: 72.5,
    preBloodPressure: '160/95',
    prePulse: 82,
    preTemperature: 36.7,
    preAssessmentNotes: 'Patient complains of mild headache',
    actualStartTime: new Date(today.setHours(8, 10, 0)),
    actualEndTime: new Date(today.setHours(12, 15, 0)),
    actualDuration: 245,
    bloodFlow: 250,
    dialysateFlow: 500,
    heparinBolus: 1000,
    heparinInfusion: 500,
    intradialyticRecords: [
      {
        time: new Date(today.setHours(8, 45, 0)),
        bloodPressure: '155/92',
        pulse: 80,
        ultrafiltrationRate: 550,
        transmembranePressure: 145,
        venousPressure: 115,
        arterialPressure: -170,
      },
      {
        time: new Date(today.setHours(10, 15, 0)),
        bloodPressure: '140/85',
        pulse: 76,
        ultrafiltrationRate: 540,
        transmembranePressure: 142,
        venousPressure: 112,
        arterialPressure: -168,
        symptoms: 'Mild dizziness',
        interventions: 'UFR reduced to 500 mL/hr, given 100mL NS bolus',
      },
    ],
    postDialysisTime: new Date(today.setHours(12, 20, 0)),
    postWeight: 70.2,
    postBloodPressure: '135/80',
    postPulse: 74,
    postTemperature: 36.6,
    postAssessmentNotes: 'Patient stable post-dialysis, headache resolved',
    ultrafiltrationVolume: 2.3,
    actualUltrafiltration: 2.3,
    hadComplications: true,
    complications: [
      {
        id: 'COMP001',
        complicationType: 'Intradialytic Hypotension',
        severity: 'mild',
        onsetTime: new Date(today.setHours(10, 10, 0)),
        description: 'BP dropped to 100/60 with dizziness',
        management: 'UFR reduced, NS bolus 100mL given, patient positioned supine',
        resolved: true,
        resolutionTime: new Date(today.setHours(10, 25, 0)),
      },
    ],
    performedBy: 'Dialysis Nurse Ahmad',
    supervisedBy: 'Dr. Kumar (Nephrologist)',
    notes: 'Consider reducing dry weight by 0.5kg',
  },
];

// Mock Dialysis Machines
export const mockDialysisMachines: DialysisMachine[] = [
  {
    id: 'MAC001',
    machineNumber: 'HD-M01',
    manufacturer: 'Fresenius Medical Care',
    model: '5008S',
    serialNumber: 'FMC-5008S-2020-001',
    status: 'in-use',
    currentPatient: 'Ahmad bin Hassan',
    currentSessionId: 'SESS001',
    sessionStartTime: new Date(today.setHours(8, 5, 0)),
    estimatedEndTime: new Date(today.setHours(12, 5, 0)),
    station: 'Station 1',
    shift: 'Morning',
    lastMaintenanceDate: new Date('2024-12-15'),
    nextMaintenanceDate: new Date('2025-03-15'),
    lastDisinfectionDate: new Date('2025-01-05'),
    nextDisinfectionDate: new Date('2025-01-06'),
    totalSessionsToday: 1,
    totalSessionsThisMonth: 5,
    totalHoursThisMonth: 20,
    hasIssues: false,
  },
  {
    id: 'MAC002',
    machineNumber: 'HD-M02',
    manufacturer: 'Fresenius Medical Care',
    model: '5008S',
    serialNumber: 'FMC-5008S-2020-002',
    status: 'available',
    station: 'Station 2',
    shift: 'Afternoon',
    lastMaintenanceDate: new Date('2024-11-20'),
    nextMaintenanceDate: new Date('2025-02-20'),
    lastDisinfectionDate: new Date('2025-01-05'),
    nextDisinfectionDate: new Date('2025-01-06'),
    totalSessionsToday: 0,
    totalSessionsThisMonth: 6,
    totalHoursThisMonth: 24,
    hasIssues: false,
  },
  {
    id: 'MAC003',
    machineNumber: 'HD-M03',
    manufacturer: 'Gambro (Baxter)',
    model: 'AK 200 Ultra S',
    serialNumber: 'GMB-AK200-2019-003',
    status: 'disinfecting',
    station: 'Station 3',
    shift: 'Morning',
    lastMaintenanceDate: new Date('2024-12-01'),
    nextMaintenanceDate: new Date('2025-03-01'),
    lastDisinfectionDate: new Date(today.setHours(12, 30, 0)),
    nextDisinfectionDate: new Date('2025-01-07'),
    totalSessionsToday: 1,
    totalSessionsThisMonth: 7,
    totalHoursThisMonth: 28,
    hasIssues: false,
    notes: 'Post-session disinfection in progress',
  },
  {
    id: 'MAC004',
    machineNumber: 'HD-M04',
    manufacturer: 'Fresenius Medical Care',
    model: '5008S',
    serialNumber: 'FMC-5008S-2021-004',
    status: 'maintenance',
    station: 'Station 4',
    shift: 'Morning',
    lastMaintenanceDate: new Date(today.setHours(8, 0, 0)),
    nextMaintenanceDate: new Date('2025-04-06'),
    lastDisinfectionDate: new Date('2025-01-04'),
    nextDisinfectionDate: new Date('2025-01-08'),
    totalSessionsToday: 0,
    totalSessionsThisMonth: 5,
    totalHoursThisMonth: 18,
    hasIssues: true,
    issues: ['Dialysate pump calibration required', 'Pressure sensor replacement'],
    reportedBy: 'Technician John',
    notes: 'Scheduled maintenance in progress, expected completion 2:00 PM',
  },
  {
    id: 'MAC005',
    machineNumber: 'HD-M05',
    manufacturer: 'Nipro',
    model: 'Surdial 55X',
    serialNumber: 'NPR-SD55X-2021-005',
    status: 'available',
    station: 'Station 5',
    shift: 'Afternoon',
    lastMaintenanceDate: new Date('2024-12-10'),
    nextMaintenanceDate: new Date('2025-03-10'),
    lastDisinfectionDate: new Date('2025-01-05'),
    nextDisinfectionDate: new Date('2025-01-06'),
    totalSessionsToday: 0,
    totalSessionsThisMonth: 4,
    totalHoursThisMonth: 16,
    hasIssues: false,
  },
];

// Mock Staff
export const mockDialysisStaff: DialysisStaff[] = [
  {
    id: 'STAFF001',
    name: 'Dr. Kumar Velan',
    designation: 'Consultant Nephrologist',
    role: 'Nephrologist',
    onDuty: true,
    shift: 'Morning',
    patientsAssignedToday: 12,
    sessionsCompletedToday: 5,
    specialization: ['Chronic Kidney Disease', 'Transplantation', 'Peritoneal Dialysis'],
    contactNumber: '012-3456789',
  },
  {
    id: 'STAFF002',
    name: 'Dialysis Nurse Siti Azizah',
    designation: 'Senior Dialysis Nurse',
    role: 'Dialysis Nurse',
    onDuty: true,
    shift: 'Morning',
    patientsAssignedToday: 4,
    sessionsCompletedToday: 2,
    contactNumber: '013-9876543',
  },
  {
    id: 'STAFF003',
    name: 'Dialysis Nurse Ahmad Faiz',
    designation: 'Dialysis Nurse',
    role: 'Dialysis Nurse',
    onDuty: true,
    shift: 'Morning',
    patientsAssignedToday: 3,
    sessionsCompletedToday: 1,
    contactNumber: '016-2345678',
  },
  {
    id: 'STAFF004',
    name: 'Dialysis Nurse Lim Mei Ling',
    designation: 'Dialysis Nurse',
    role: 'Dialysis Nurse',
    onDuty: true,
    shift: 'Afternoon',
    patientsAssignedToday: 4,
    sessionsCompletedToday: 0,
    contactNumber: '019-8887766',
  },
];

// Mock Stats
export const mockHaemodialysisStats: HaemodialysisStats = {
  totalActivePatients: 48,
  scheduledToday: 18,
  completedToday: 5,
  ongoingSessions: 1,
  
  morningSessionsToday: 9,
  afternoonSessionsToday: 6,
  eveningSessionsToday: 3,
  
  averageKtV: 1.4,
  adequateDialysisRate: 88,
  complicationRate: 8,
  
  totalMachines: 5,
  availableMachines: 2,
  machinesInUse: 1,
  machinesOffline: 2,
  
  averageSessionDuration: 4.0,
  machineUtilizationRate: 82,
  patientWaitTime: 8,
  
  missedSessionsThisMonth: 3,
  adverseEventsThisMonth: 2,
  waterQualityTests: 12,
  waterQualityPassRate: 100,
  
  avfRate: 75,
  catheterRate: 25,
  
  nursesOnDuty: 3,
  doctorsOnDuty: 1,
};

export function getDialysisPatients(): DialysisPatient[] {
  return mockDialysisPatients;
}

export function getDialysisSessions(): DialysisSession[] {
  return mockDialysisSessions;
}

export function getDialysisMachines(): DialysisMachine[] {
  return mockDialysisMachines;
}

export function getDialysisStaff(): DialysisStaff[] {
  return mockDialysisStaff;
}

export function getHaemodialysisStats(): HaemodialysisStats {
  return mockHaemodialysisStats;
}










