// SPUB Mock Data

import { 
  Patient, 
  SPUBRequest, 
  SPUBReceive, 
  DispenseRecord, 
  MedicationBalance,
  SPUBStatistics 
} from './types';

export const mockPatients: Patient[] = [
  {
    id: 'P001',
    nric: '850312-10-5678',
    name: 'Tan Mei Ling',
    age: 40,
    gender: 'Female',
    contactNumber: '+60123456789',
    email: 'meiling.tan@email.com',
    address: 'No. 23, Jalan Harmoni, Taman Sentosa, 50400 Kuala Lumpur',
    homeClinic: 'Klinik Kesihatan Sentosa',
    homeFacilityCode: 'KKS001',
    chronicConditions: ['Hypertension', 'Type 2 Diabetes'],
    allergies: ['Penicillin'],
  },
  {
    id: 'P002',
    nric: '720625-08-3421',
    name: 'Ahmad bin Hassan',
    age: 53,
    gender: 'Male',
    contactNumber: '+60198765432',
    email: 'ahmad.hassan@email.com',
    address: 'Lot 45, Taman Melati, 43000 Kajang, Selangor',
    homeClinic: 'Klinik Kesihatan Kajang',
    homeFacilityCode: 'KKK002',
    chronicConditions: ['Hypertension', 'Hyperlipidemia', 'Ischemic Heart Disease'],
    allergies: [],
  },
  {
    id: 'P003',
    nric: '901118-14-7890',
    name: 'Lim Siew Hui',
    age: 35,
    gender: 'Female',
    contactNumber: '+60167894561',
    email: 'siewhui.lim@email.com',
    address: '12A, Jalan Bunga Raya, 47000 Petaling Jaya, Selangor',
    homeClinic: 'Klinik Kesihatan Petaling Jaya',
    homeFacilityCode: 'KKPJ003',
    chronicConditions: ['Hypothyroidism', 'Asthma'],
    allergies: ['Aspirin'],
  },
  {
    id: 'P004',
    nric: '650504-06-2345',
    name: 'Rajesh Kumar',
    age: 60,
    gender: 'Male',
    contactNumber: '+60125678901',
    email: 'rajesh.kumar@email.com',
    address: '88, Taman Sri Sentosa, 52100 Kepong, Kuala Lumpur',
    homeClinic: 'Klinik Kesihatan Kepong',
    homeFacilityCode: 'KKK004',
    chronicConditions: ['Type 2 Diabetes', 'Chronic Kidney Disease', 'Hypertension'],
    allergies: ['Sulfa drugs'],
  },
  {
    id: 'P005',
    nric: '950822-03-6789',
    name: 'Nurul Aisyah binti Abdullah',
    age: 30,
    gender: 'Female',
    contactNumber: '+60134567890',
    email: 'nurul.aisyah@email.com',
    address: '34B, Jalan Merdeka, 40000 Shah Alam, Selangor',
    homeClinic: 'Klinik Kesihatan Shah Alam',
    homeFacilityCode: 'KKSA005',
    chronicConditions: ['Epilepsy'],
    allergies: [],
  },
];

export const mockSPUBRequests: SPUBRequest[] = [
  {
    id: 'REQ001',
    requestNumber: 'SPUB-2025-001',
    patientId: 'P001',
    patient: mockPatients[0],
    medications: [
      {
        id: 'M001',
        drugCode: 'AMLOD5',
        drugName: 'Amlodipine',
        strength: '5mg',
        form: 'Tablet',
        quantity: 60,
        unit: 'tablets',
        dosage: '1 tablet',
        frequency: 'Once daily',
        route: 'Oral',
        duration: 60,
        instructions: 'Take in the morning with or without food',
      },
      {
        id: 'M002',
        drugCode: 'METF500',
        drugName: 'Metformin',
        strength: '500mg',
        form: 'Tablet',
        quantity: 120,
        unit: 'tablets',
        dosage: '1 tablet',
        frequency: 'Twice daily',
        route: 'Oral',
        duration: 60,
        instructions: 'Take with meals to reduce stomach upset',
      },
      {
        id: 'M003',
        drugCode: 'ATOR20',
        drugName: 'Atorvastatin',
        strength: '20mg',
        form: 'Tablet',
        quantity: 60,
        unit: 'tablets',
        dosage: '1 tablet',
        frequency: 'Once daily at night',
        route: 'Oral',
        duration: 60,
        instructions: 'Take at bedtime',
      },
    ],
    requestDate: '2025-10-08T09:30:00',
    requestedBy: 'Dr. Sarah Wong',
    targetFacility: 'Klinik Kesihatan Sentosa',
    targetFacilityCode: 'KKS001',
    status: 'sent',
    expectedStartDate: '2025-10-20',
    totalItems: 3,
    priority: 'routine',
    notes: 'Patient moving back to home clinic for regular follow-up',
    emailSentDate: '2025-10-08T10:15:00',
    acknowledgementDate: '2025-10-08T14:30:00',
  },
  {
    id: 'REQ002',
    requestNumber: 'SPUB-2025-002',
    patientId: 'P002',
    patient: mockPatients[1],
    medications: [
      {
        id: 'M004',
        drugCode: 'PERIN8',
        drugName: 'Perindopril',
        strength: '8mg',
        form: 'Tablet',
        quantity: 90,
        unit: 'tablets',
        dosage: '1 tablet',
        frequency: 'Once daily',
        route: 'Oral',
        duration: 90,
        instructions: 'Take in the morning before meals',
      },
      {
        id: 'M005',
        drugCode: 'SIMVA40',
        drugName: 'Simvastatin',
        strength: '40mg',
        form: 'Tablet',
        quantity: 90,
        unit: 'tablets',
        dosage: '1 tablet',
        frequency: 'Once daily at night',
        route: 'Oral',
        duration: 90,
        instructions: 'Take at bedtime',
      },
      {
        id: 'M006',
        drugCode: 'ASP100',
        drugName: 'Aspirin',
        strength: '100mg',
        form: 'Tablet',
        quantity: 90,
        unit: 'tablets',
        dosage: '1 tablet',
        frequency: 'Once daily',
        route: 'Oral',
        duration: 90,
        instructions: 'Take after food',
      },
      {
        id: 'M007',
        drugCode: 'BISOP5',
        drugName: 'Bisoprolol',
        strength: '5mg',
        form: 'Tablet',
        quantity: 90,
        unit: 'tablets',
        dosage: '1 tablet',
        frequency: 'Once daily',
        route: 'Oral',
        duration: 90,
        instructions: 'Take in the morning',
      },
    ],
    requestDate: '2025-10-09T11:00:00',
    requestedBy: 'Dr. Kumar Raj',
    targetFacility: 'Klinik Kesihatan Kajang',
    targetFacilityCode: 'KKK002',
    status: 'acknowledged',
    expectedStartDate: '2025-10-25',
    totalItems: 4,
    priority: 'routine',
    notes: 'Post-discharge follow-up. Patient stable.',
    emailSentDate: '2025-10-09T11:30:00',
    acknowledgementDate: '2025-10-09T15:45:00',
  },
  {
    id: 'REQ003',
    requestNumber: 'SPUB-2025-003',
    patientId: 'P003',
    patient: mockPatients[2],
    medications: [
      {
        id: 'M008',
        drugCode: 'LEVO100',
        drugName: 'Levothyroxine',
        strength: '100mcg',
        form: 'Tablet',
        quantity: 90,
        unit: 'tablets',
        dosage: '1 tablet',
        frequency: 'Once daily',
        route: 'Oral',
        duration: 90,
        instructions: 'Take on empty stomach, 30 minutes before breakfast',
      },
      {
        id: 'M009',
        drugCode: 'SALBU200',
        drugName: 'Salbutamol Inhaler',
        strength: '200mcg',
        form: 'Inhaler',
        quantity: 2,
        unit: 'inhalers',
        dosage: '2 puffs',
        frequency: 'As needed',
        route: 'Inhalation',
        duration: 90,
        instructions: 'Use as needed for breathlessness. Max 8 puffs per day.',
      },
    ],
    requestDate: '2025-10-10T14:20:00',
    requestedBy: 'Dr. Fatimah Zahra',
    targetFacility: 'Klinik Kesihatan Petaling Jaya',
    targetFacilityCode: 'KKPJ003',
    status: 'ready',
    expectedStartDate: '2025-10-18',
    totalItems: 2,
    priority: 'routine',
    emailSentDate: '2025-10-10T14:45:00',
    acknowledgementDate: '2025-10-10T16:00:00',
  },
  {
    id: 'REQ004',
    requestNumber: 'SPUB-2025-004',
    patientId: 'P004',
    patient: mockPatients[3],
    medications: [
      {
        id: 'M010',
        drugCode: 'GLIM2',
        drugName: 'Glimepiride',
        strength: '2mg',
        form: 'Tablet',
        quantity: 60,
        unit: 'tablets',
        dosage: '1 tablet',
        frequency: 'Once daily before breakfast',
        route: 'Oral',
        duration: 60,
        instructions: 'Take before breakfast',
      },
      {
        id: 'M011',
        drugCode: 'LOSART50',
        drugName: 'Losartan',
        strength: '50mg',
        form: 'Tablet',
        quantity: 60,
        unit: 'tablets',
        dosage: '1 tablet',
        frequency: 'Once daily',
        route: 'Oral',
        duration: 60,
        instructions: 'Take with or without food',
      },
    ],
    requestDate: '2025-10-11T10:00:00',
    requestedBy: 'Dr. Ahmad Firdaus',
    targetFacility: 'Klinik Kesihatan Kepong',
    targetFacilityCode: 'KKK004',
    status: 'pending',
    expectedStartDate: '2025-10-28',
    totalItems: 2,
    priority: 'routine',
  },
  {
    id: 'REQ005',
    requestNumber: 'SPUB-2025-005',
    patientId: 'P005',
    patient: mockPatients[4],
    medications: [
      {
        id: 'M012',
        drugCode: 'CARBA200',
        drugName: 'Carbamazepine',
        strength: '200mg',
        form: 'Tablet',
        quantity: 180,
        unit: 'tablets',
        dosage: '1 tablet',
        frequency: 'Three times daily',
        route: 'Oral',
        duration: 60,
        instructions: 'Take with food. Do not stop suddenly.',
      },
    ],
    requestDate: '2025-10-11T15:30:00',
    requestedBy: 'Dr. Lim Wei Jian',
    targetFacility: 'Klinik Kesihatan Shah Alam',
    targetFacilityCode: 'KKSA005',
    status: 'urgent',
    expectedStartDate: '2025-10-15',
    totalItems: 1,
    priority: 'urgent',
    notes: 'Patient needs urgent transfer due to seizure control issues',
  },
];

export const mockSPUBReceives: SPUBReceive[] = [
  {
    id: 'RCV001',
    requestId: 'REQ003',
    receiveNumber: 'SPUB-RCV-2025-001',
    requestNumber: 'SPUB-2025-003',
    patient: mockPatients[2],
    medications: [
      {
        medicationId: 'M008',
        expectedQuantity: 90,
        receivedQuantity: 90,
        batchNumber: 'LT2024Q3-089',
        expiryDate: '2026-08-31',
        receivedDate: '2025-10-11T09:30:00',
        receivedBy: 'Pharmacist Lee Ai Lin',
        status: 'completed',
      },
      {
        medicationId: 'M009',
        expectedQuantity: 2,
        receivedQuantity: 2,
        batchNumber: 'SB2024-456',
        expiryDate: '2026-12-31',
        receivedDate: '2025-10-11T09:30:00',
        receivedBy: 'Pharmacist Lee Ai Lin',
        status: 'completed',
      },
    ],
    receivedDate: '2025-10-11T09:30:00',
    receivedBy: 'Pharmacist Lee Ai Lin',
    status: 'completed',
    sourceFacility: 'Klinik Kesihatan Petaling Jaya',
    totalItemsExpected: 2,
    totalItemsReceived: 2,
    notes: 'All items received in good condition',
    discrepancies: false,
  },
  {
    id: 'RCV002',
    requestId: 'REQ001',
    receiveNumber: 'SPUB-RCV-2025-002',
    requestNumber: 'SPUB-2025-001',
    patient: mockPatients[0],
    medications: [
      {
        medicationId: 'M001',
        expectedQuantity: 60,
        receivedQuantity: 60,
        batchNumber: 'AML2024-234',
        expiryDate: '2027-03-31',
        receivedDate: '2025-10-11T14:15:00',
        receivedBy: 'Pharmacist Chen Wei Ming',
        status: 'completed',
      },
      {
        medicationId: 'M002',
        expectedQuantity: 120,
        receivedQuantity: 90,
        batchNumber: 'MET2024-567',
        expiryDate: '2026-11-30',
        receivedDate: '2025-10-11T14:15:00',
        receivedBy: 'Pharmacist Chen Wei Ming',
        status: 'partial',
        discrepancyReason: 'Short supply at source facility. Balance of 30 tablets to be sent next week.',
      },
      {
        medicationId: 'M003',
        expectedQuantity: 60,
        receivedQuantity: 60,
        batchNumber: 'AT2024-890',
        expiryDate: '2027-06-30',
        receivedDate: '2025-10-11T14:15:00',
        receivedBy: 'Pharmacist Chen Wei Ming',
        status: 'completed',
      },
    ],
    receivedDate: '2025-10-11T14:15:00',
    receivedBy: 'Pharmacist Chen Wei Ming',
    status: 'partial',
    sourceFacility: 'Klinik Kesihatan Sentosa',
    totalItemsExpected: 3,
    totalItemsReceived: 2,
    notes: 'Partial receipt. Metformin short supplied. Follow-up required.',
    discrepancies: true,
  },
];

export const mockDispenseRecords: DispenseRecord[] = [
  {
    id: 'DISP001',
    requestId: 'REQ003',
    patientId: 'P003',
    patient: mockPatients[2],
    medications: mockSPUBRequests[2].medications,
    scheduledDate: '2025-10-18',
    status: 'ready',
    counselingCompleted: false,
    notes: 'Patient scheduled for morning collection',
  },
  {
    id: 'DISP002',
    requestId: 'REQ001',
    patientId: 'P001',
    patient: mockPatients[0],
    medications: mockSPUBRequests[0].medications,
    scheduledDate: '2025-10-20',
    status: 'ready',
    counselingCompleted: false,
    notes: 'Partial medications available. Awaiting Metformin balance.',
  },
  {
    id: 'DISP003',
    requestId: 'REQ002',
    patientId: 'P002',
    patient: mockPatients[1],
    medications: mockSPUBRequests[1].medications,
    scheduledDate: '2025-10-25',
    status: 'scheduled',
    counselingCompleted: false,
  },
];

export const mockMedicationBalances: MedicationBalance[] = [
  {
    id: 'BAL001',
    patientId: 'P003',
    patientName: 'Lim Siew Hui',
    medicationId: 'M008',
    drugName: 'Levothyroxine 100mcg',
    strength: '100mcg',
    totalReceived: 90,
    totalDispensed: 0,
    balance: 90,
    unit: 'tablets',
    nextScheduledDate: '2025-10-18',
    status: 'adequate',
    expiryDate: '2026-08-31',
  },
  {
    id: 'BAL002',
    patientId: 'P003',
    patientName: 'Lim Siew Hui',
    medicationId: 'M009',
    drugName: 'Salbutamol Inhaler',
    strength: '200mcg',
    totalReceived: 2,
    totalDispensed: 0,
    balance: 2,
    unit: 'inhalers',
    nextScheduledDate: '2025-10-18',
    status: 'adequate',
    expiryDate: '2026-12-31',
  },
  {
    id: 'BAL003',
    patientId: 'P001',
    patientName: 'Tan Mei Ling',
    medicationId: 'M001',
    drugName: 'Amlodipine 5mg',
    strength: '5mg',
    totalReceived: 60,
    totalDispensed: 0,
    balance: 60,
    unit: 'tablets',
    nextScheduledDate: '2025-10-20',
    status: 'adequate',
    expiryDate: '2027-03-31',
  },
  {
    id: 'BAL004',
    patientId: 'P001',
    patientName: 'Tan Mei Ling',
    medicationId: 'M002',
    drugName: 'Metformin 500mg',
    strength: '500mg',
    totalReceived: 90,
    totalDispensed: 0,
    balance: 90,
    unit: 'tablets',
    nextScheduledDate: '2025-10-20',
    status: 'low',
    expiryDate: '2026-11-30',
  },
  {
    id: 'BAL005',
    patientId: 'P001',
    patientName: 'Tan Mei Ling',
    medicationId: 'M003',
    drugName: 'Atorvastatin 20mg',
    strength: '20mg',
    totalReceived: 60,
    totalDispensed: 0,
    balance: 60,
    unit: 'tablets',
    nextScheduledDate: '2025-10-20',
    status: 'adequate',
    expiryDate: '2027-06-30',
  },
];

export const mockStatistics: SPUBStatistics = {
  totalActivePatients: 45,
  pendingRequests: 8,
  awaitingReceipt: 12,
  readyToDispense: 5,
  lowStockAlerts: 3,
  dispensedThisMonth: 127,
  requestsThisMonth: 38,
  averageProcessingTime: 5.2,
};


