import type {
  Prescription,
  PrescribedMedication,
  DrugInteraction,
  PharmacyCounterStats,
  Pharmacist,
} from '../types/PharmacyCounter';

const today = new Date();

// Mock Prescriptions
export const mockPrescriptions: Prescription[] = [
  {
    id: 'RX001',
    prescriptionNumber: 'RX-2025-0001',
    prescriptionDate: new Date(today.setHours(8, 30, 0)),
    patientName: 'Ahmad bin Hassan',
    patientIC: '750615-10-5234',
    patientMRN: 'MRN-2024-00123',
    dateOfBirth: new Date('1975-06-15'),
    age: 49,
    gender: 'Male',
    contactNumber: '012-3456789',
    prescribedBy: 'Dr. Lim Wei Ming',
    prescriberLicenseNo: 'MMC-12345',
    department: 'General Medicine',
    type: 'new',
    priority: 'routine',
    status: 'dispensed',
    medications: [
      {
        id: 'MED001-1',
        drugName: 'Metformin',
        genericName: 'Metformin Hydrochloride',
        strength: '500mg',
        dosageForm: 'Tablet',
        dosage: '1 tablet',
        frequency: 'Twice daily',
        route: 'Oral',
        duration: '30 days',
        quantity: 60,
        substitutable: true,
        batchNumber: 'MET-2024-12345',
        expiryDate: new Date('2026-12-31'),
        beforeMeals: false,
        afterMeals: true,
        withFood: true,
        specialInstructions: 'Take with food to reduce gastric upset',
        isControlled: false,
        isHighAlert: false,
        requiresCounseling: true,
        inStock: true,
        availableQuantity: 5000,
        unitPrice: 0.15,
        totalPrice: 9.0,
        subsidized: true,
      },
      {
        id: 'MED001-2',
        drugName: 'Simvastatin',
        genericName: 'Simvastatin',
        strength: '20mg',
        dosageForm: 'Tablet',
        dosage: '1 tablet',
        frequency: 'Once daily at night',
        route: 'Oral',
        duration: '30 days',
        quantity: 30,
        substitutable: true,
        batchNumber: 'SIM-2024-67890',
        expiryDate: new Date('2026-11-30'),
        beforeMeals: false,
        afterMeals: false,
        withFood: false,
        specialInstructions: 'Take at bedtime',
        isControlled: false,
        isHighAlert: false,
        requiresCounseling: true,
        inStock: true,
        availableQuantity: 3000,
        unitPrice: 0.25,
        totalPrice: 7.5,
        subsidized: true,
      },
    ],
    diagnosis: 'Type 2 Diabetes Mellitus, Hyperlipidemia',
    allergies: ['Penicillin'],
    chronicConditions: ['Type 2 Diabetes', 'Hypertension'],
    currentMedications: ['Amlodipine 5mg OD'],
    verifiedBy: 'Pharmacist Sarah',
    verifiedAt: new Date(today.setHours(9, 0, 0)),
    dispensedBy: 'Pharmacist Sarah',
    dispensedAt: new Date(today.setHours(9, 15, 0)),
    counselingStatus: 'completed',
    counseledBy: 'Pharmacist Sarah',
    counseledAt: new Date(today.setHours(9, 20, 0)),
    counselingNotes: 'Patient counseled on medication use, side effects, and lifestyle modifications',
    paymentMethod: 'government',
    totalAmount: 16.5,
    paidAmount: 0,
    paymentStatus: 'waived',
    queueNumber: 'Q-001',
    receivedAt: new Date(today.setHours(8, 45, 0)),
    estimatedWaitTime: 15,
    hasInteractions: false,
    hasAllergies: false,
    hasDuplicateTherapy: false,
    requiresFollowUp: true,
    followUpDate: new Date(today.setDate(today.getDate() + 30)),
    followUpNotes: 'Monitor blood glucose, review in 1 month',
  },
  {
    id: 'RX002',
    prescriptionNumber: 'RX-2025-0002',
    prescriptionDate: new Date(today.setHours(9, 0, 0)),
    patientName: 'Siti Nurhaliza binti Abdullah',
    patientIC: '880824-08-2341',
    patientMRN: 'MRN-2024-00456',
    dateOfBirth: new Date('1988-08-24'),
    age: 36,
    gender: 'Female',
    contactNumber: '013-9876543',
    prescribedBy: 'Dr. Kumar Velan',
    prescriberLicenseNo: 'MMC-23456',
    department: 'Emergency & Trauma',
    type: 'stat',
    priority: 'stat',
    status: 'in-progress',
    medications: [
      {
        id: 'MED002-1',
        drugName: 'Amoxicillin',
        genericName: 'Amoxicillin Trihydrate',
        strength: '500mg',
        dosageForm: 'Capsule',
        dosage: '1 capsule',
        frequency: 'Three times daily',
        route: 'Oral',
        duration: '7 days',
        quantity: 21,
        substitutable: true,
        batchNumber: 'AMOX-2024-11111',
        expiryDate: new Date('2026-10-31'),
        beforeMeals: false,
        afterMeals: false,
        withFood: false,
        specialInstructions: 'Complete the full course even if symptoms improve',
        isControlled: false,
        isHighAlert: false,
        requiresCounseling: true,
        inStock: true,
        availableQuantity: 2000,
        unitPrice: 0.30,
        totalPrice: 6.3,
        subsidized: true,
      },
      {
        id: 'MED002-2',
        drugName: 'Paracetamol',
        genericName: 'Paracetamol',
        strength: '500mg',
        dosageForm: 'Tablet',
        dosage: '1-2 tablets',
        frequency: 'Every 6 hours as needed',
        route: 'Oral',
        duration: '5 days',
        quantity: 20,
        substitutable: false,
        batchNumber: 'PARA-2024-22222',
        expiryDate: new Date('2027-01-31'),
        beforeMeals: false,
        afterMeals: false,
        withFood: false,
        specialInstructions: 'For pain and fever. Do not exceed 4g (8 tablets) in 24 hours',
        isControlled: false,
        isHighAlert: true,
        requiresCounseling: true,
        inStock: true,
        availableQuantity: 10000,
        unitPrice: 0.05,
        totalPrice: 1.0,
        subsidized: true,
      },
    ],
    diagnosis: 'Upper Respiratory Tract Infection',
    allergies: [],
    chronicConditions: [],
    currentMedications: [],
    verifiedBy: 'Pharmacist John',
    verifiedAt: new Date(today.setHours(9, 10, 0)),
    counselingStatus: 'in-progress',
    paymentMethod: 'cash',
    totalAmount: 7.3,
    paidAmount: 0,
    paymentStatus: 'pending',
    queueNumber: 'Q-002',
    receivedAt: new Date(today.setHours(9, 5, 0)),
    estimatedWaitTime: 10,
    hasInteractions: false,
    hasAllergies: false,
    hasDuplicateTherapy: false,
    requiresFollowUp: false,
  },
  {
    id: 'RX003',
    prescriptionNumber: 'RX-2025-0003',
    prescriptionDate: new Date(today.setHours(9, 30, 0)),
    patientName: 'Rajendran s/o Suppiah',
    patientIC: '680405-05-3456',
    patientMRN: 'MRN-2024-00789',
    dateOfBirth: new Date('1968-04-05'),
    age: 56,
    gender: 'Male',
    contactNumber: '016-2345678',
    prescribedBy: 'Dr. Chan Kok Wai',
    prescriberLicenseNo: 'MMC-34567',
    department: 'Orthopedics',
    type: 'new',
    priority: 'urgent',
    status: 'verified',
    medications: [
      {
        id: 'MED003-1',
        drugName: 'Diclofenac Sodium',
        genericName: 'Diclofenac Sodium',
        strength: '50mg',
        dosageForm: 'Tablet (enteric coated)',
        dosage: '1 tablet',
        frequency: 'Three times daily',
        route: 'Oral',
        duration: '5 days',
        quantity: 15,
        substitutable: true,
        batchNumber: 'DICLO-2024-33333',
        expiryDate: new Date('2026-09-30'),
        beforeMeals: false,
        afterMeals: true,
        withFood: true,
        specialInstructions: 'Take with food. Stop if stomach pain or black stools occur',
        isControlled: false,
        isHighAlert: true,
        requiresCounseling: true,
        inStock: true,
        availableQuantity: 1500,
        unitPrice: 0.40,
        totalPrice: 6.0,
        subsidized: true,
      },
      {
        id: 'MED003-2',
        drugName: 'Omeprazole',
        genericName: 'Omeprazole',
        strength: '20mg',
        dosageForm: 'Capsule',
        dosage: '1 capsule',
        frequency: 'Once daily before breakfast',
        route: 'Oral',
        duration: '5 days',
        quantity: 5,
        substitutable: true,
        batchNumber: 'OMEP-2024-44444',
        expiryDate: new Date('2026-08-31'),
        beforeMeals: true,
        afterMeals: false,
        withFood: false,
        specialInstructions: 'Take 30 minutes before breakfast',
        isControlled: false,
        isHighAlert: false,
        requiresCounseling: false,
        inStock: true,
        availableQuantity: 2500,
        unitPrice: 0.35,
        totalPrice: 1.75,
        subsidized: true,
      },
    ],
    diagnosis: 'Right knee sprain with pain',
    allergies: [],
    chronicConditions: ['Osteoarthritis'],
    currentMedications: [],
    verifiedBy: 'Pharmacist Sarah',
    verifiedAt: new Date(today.setHours(9, 45, 0)),
    counselingStatus: 'required',
    paymentMethod: 'government',
    totalAmount: 7.75,
    paidAmount: 0,
    paymentStatus: 'waived',
    queueNumber: 'Q-003',
    receivedAt: new Date(today.setHours(9, 35, 0)),
    estimatedWaitTime: 12,
    hasInteractions: false,
    hasAllergies: false,
    hasDuplicateTherapy: false,
    requiresFollowUp: false,
    notes: 'Gastroprotection added due to NSAID use',
  },
  {
    id: 'RX004',
    prescriptionNumber: 'RX-2025-0004',
    prescriptionDate: new Date(today.setHours(10, 0, 0)),
    patientName: 'Lee Mei Ling',
    patientIC: '920115-12-3456',
    patientMRN: 'MRN-2024-01456',
    dateOfBirth: new Date('1992-01-15'),
    age: 33,
    gender: 'Female',
    contactNumber: '019-4445555',
    prescribedBy: 'Dr. Faridah Ahmad',
    prescriberLicenseNo: 'MMC-45678',
    department: 'Psychiatry',
    type: 'refill',
    priority: 'routine',
    status: 'pending',
    medications: [
      {
        id: 'MED004-1',
        drugName: 'Fluoxetine',
        genericName: 'Fluoxetine Hydrochloride',
        strength: '20mg',
        dosageForm: 'Capsule',
        dosage: '1 capsule',
        frequency: 'Once daily in the morning',
        route: 'Oral',
        duration: '30 days',
        quantity: 30,
        substitutable: false,
        batchNumber: 'FLUOX-2024-55555',
        expiryDate: new Date('2026-12-31'),
        beforeMeals: false,
        afterMeals: false,
        withFood: false,
        specialInstructions: 'Do not stop suddenly. Contact doctor if side effects occur',
        isControlled: false,
        isHighAlert: true,
        requiresCounseling: true,
        inStock: true,
        availableQuantity: 800,
        unitPrice: 1.50,
        totalPrice: 45.0,
        subsidized: false,
      },
    ],
    diagnosis: 'Major Depressive Disorder',
    allergies: [],
    chronicConditions: ['Depression'],
    currentMedications: ['Fluoxetine 20mg OD (refill)'],
    counselingStatus: 'required',
    paymentMethod: 'insurance',
    insuranceProvider: 'Great Eastern',
    insurancePolicyNumber: 'GE-2024-556789',
    totalAmount: 45.0,
    copayAmount: 10.0,
    paidAmount: 0,
    paymentStatus: 'pending',
    queueNumber: 'Q-004',
    receivedAt: new Date(today.setHours(10, 5, 0)),
    estimatedWaitTime: 20,
    hasInteractions: false,
    hasAllergies: false,
    hasDuplicateTherapy: false,
    requiresFollowUp: true,
    followUpDate: new Date(today.setDate(today.getDate() + 30)),
    followUpNotes: 'Regular follow-up with psychiatrist required',
  },
  {
    id: 'RX005',
    prescriptionNumber: 'RX-2025-0005',
    prescriptionDate: new Date(today.setHours(10, 15, 0)),
    patientName: 'Wong Ah Meng',
    patientIC: '650920-10-6789',
    patientMRN: 'MRN-2024-01234',
    dateOfBirth: new Date('1965-09-20'),
    age: 59,
    gender: 'Male',
    contactNumber: '012-6667777',
    prescribedBy: 'Dr. Azizah Rahman',
    prescriberLicenseNo: 'MMC-56789',
    department: 'Cardiology',
    type: 'new',
    priority: 'urgent',
    status: 'pending',
    medications: [
      {
        id: 'MED005-1',
        drugName: 'Aspirin',
        genericName: 'Acetylsalicylic Acid',
        strength: '100mg',
        dosageForm: 'Tablet (dispersible)',
        dosage: '1 tablet',
        frequency: 'Once daily',
        route: 'Oral',
        duration: '30 days',
        quantity: 30,
        substitutable: false,
        batchNumber: 'ASP-2024-66666',
        expiryDate: new Date('2027-03-31'),
        beforeMeals: false,
        afterMeals: true,
        withFood: true,
        specialInstructions: 'Dissolve in water before taking. Take after food',
        isControlled: false,
        isHighAlert: true,
        requiresCounseling: true,
        inStock: true,
        availableQuantity: 5000,
        unitPrice: 0.10,
        totalPrice: 3.0,
        subsidized: true,
      },
      {
        id: 'MED005-2',
        drugName: 'Atorvastatin',
        genericName: 'Atorvastatin Calcium',
        strength: '40mg',
        dosageForm: 'Tablet',
        dosage: '1 tablet',
        frequency: 'Once daily at night',
        route: 'Oral',
        duration: '30 days',
        quantity: 30,
        substitutable: true,
        batchNumber: 'ATOR-2024-77777',
        expiryDate: new Date('2026-11-30'),
        beforeMeals: false,
        afterMeals: false,
        withFood: false,
        specialInstructions: 'Take at bedtime. Report muscle pain immediately',
        isControlled: false,
        isHighAlert: false,
        requiresCounseling: true,
        inStock: true,
        availableQuantity: 2000,
        unitPrice: 0.60,
        totalPrice: 18.0,
        subsidized: true,
      },
      {
        id: 'MED005-3',
        drugName: 'Bisoprolol',
        genericName: 'Bisoprolol Fumarate',
        strength: '5mg',
        dosageForm: 'Tablet',
        dosage: '1 tablet',
        frequency: 'Once daily in the morning',
        route: 'Oral',
        duration: '30 days',
        quantity: 30,
        substitutable: true,
        batchNumber: 'BISO-2024-88888',
        expiryDate: new Date('2026-10-31'),
        beforeMeals: false,
        afterMeals: false,
        withFood: false,
        specialInstructions: 'Do not stop suddenly. Check pulse regularly',
        isControlled: false,
        isHighAlert: true,
        requiresCounseling: true,
        inStock: true,
        availableQuantity: 1200,
        unitPrice: 0.55,
        totalPrice: 16.5,
        subsidized: true,
      },
    ],
    diagnosis: 'Acute Coronary Syndrome, post-PCI',
    allergies: [],
    chronicConditions: ['Ischemic Heart Disease', 'Hypertension', 'Hyperlipidemia'],
    currentMedications: [],
    counselingStatus: 'required',
    paymentMethod: 'government',
    totalAmount: 37.5,
    paidAmount: 0,
    paymentStatus: 'waived',
    queueNumber: 'Q-005',
    receivedAt: new Date(today.setHours(10, 20, 0)),
    estimatedWaitTime: 25,
    hasInteractions: false,
    hasAllergies: false,
    hasDuplicateTherapy: false,
    requiresFollowUp: true,
    followUpDate: new Date(today.setDate(today.getDate() + 7)),
    followUpNotes: 'Urgent cardiology follow-up in 1 week',
    notes: 'New cardiac medications - extensive counseling required',
  },
];

// Mock Pharmacists
export const mockPharmacists: Pharmacist[] = [
  {
    id: 'PHAR001',
    name: 'Pharmacist Sarah Tan',
    registrationNumber: 'PHAR-12345',
    specialization: ['Clinical Pharmacy', 'Diabetes Management'],
    onDuty: true,
    availableForDispensing: true,
    prescriptionsDispensedToday: 28,
    counselingSessionsToday: 15,
    pendingPrescriptions: 3,
    counterNumber: 'Counter 1',
    contactNumber: '012-3456789',
  },
  {
    id: 'PHAR002',
    name: 'Pharmacist John Wong',
    registrationNumber: 'PHAR-23456',
    specialization: ['Emergency Pharmacy', 'Anticoagulation'],
    onDuty: true,
    availableForDispensing: false,
    prescriptionsDispensedToday: 22,
    counselingSessionsToday: 10,
    pendingPrescriptions: 5,
    counterNumber: 'Counter 2',
    contactNumber: '013-9876543',
  },
  {
    id: 'PHAR003',
    name: 'Pharmacist Aisha Rahman',
    registrationNumber: 'PHAR-34567',
    specialization: ['Pediatric Pharmacy', 'Oncology'],
    onDuty: true,
    availableForDispensing: true,
    prescriptionsDispensedToday: 18,
    counselingSessionsToday: 12,
    pendingPrescriptions: 2,
    counterNumber: 'Counter 3',
    contactNumber: '016-2345678',
  },
];

// Mock Stats
export const mockPharmacyCounterStats: PharmacyCounterStats = {
  totalPrescriptionsToday: 85,
  pendingPrescriptions: 12,
  dispensedPrescriptions: 68,
  
  statPrescriptions: 3,
  urgentPrescriptions: 15,
  routinePrescriptions: 67,
  
  currentQueueSize: 8,
  averageWaitTime: 18,
  longestWaitTime: 45,
  
  interactionsCaught: 5,
  allergiesPrevented: 2,
  duplicateTherapyDetected: 3,
  
  counselingSessionsToday: 37,
  averageCounselingTime: 8,
  
  totalRevenueToday: 2847.50,
  insuranceClaimsToday: 12,
  
  averageDispensingTime: 12,
  prescriptionsPerHour: 5,
  
  outOfStockItems: 3,
  nearExpiryAlerts: 8,
};

export function getPrescriptions(): Prescription[] {
  return mockPrescriptions;
}

export function getPharmacists(): Pharmacist[] {
  return mockPharmacists;
}

export function getPharmacyCounterStats(): PharmacyCounterStats {
  return mockPharmacyCounterStats;
}










