import type {
  Visitor,
  Appointment,
  PatientRegistration,
  QueueEntry,
  FrontDeskStats,
  Counter,
} from '../types/FrontDesk';

const today = new Date();
const yesterday = new Date(today);
yesterday.setDate(yesterday.getDate() - 1);

// Mock Visitors
export const mockVisitors: Visitor[] = [
  {
    id: 'V001',
    name: 'Ahmad bin Abdullah',
    icNumber: '850615-10-5234',
    contactNumber: '012-3456789',
    type: 'family',
    status: 'visiting',
    checkInTime: new Date(today.setHours(8, 30, 0)),
    purposeOfVisit: 'Visit patient',
    hostName: 'Siti Nurhaliza',
    hostDepartment: 'General Ward',
    hostBedNumber: 'A-15',
    badgeNumber: 'V-001',
    badgeIssued: true,
    vehicleNumber: 'WXY 1234',
    temperatureChecked: true,
    temperature: 36.5,
    healthDeclarationSigned: true,
  },
  {
    id: 'V002',
    name: 'Lee Mei Ling',
    icNumber: '920824-08-2341',
    contactNumber: '013-9876543',
    type: 'patient',
    status: 'checked-in',
    checkInTime: new Date(today.setHours(9, 15, 0)),
    purposeOfVisit: 'Outpatient consultation',
    hostDepartment: 'Outpatient Clinic',
    badgeNumber: 'P-042',
    badgeIssued: true,
    temperatureChecked: true,
    temperature: 36.8,
    healthDeclarationSigned: true,
  },
  {
    id: 'V003',
    name: 'Kumar Suppiah',
    icNumber: '780310-05-3456',
    contactNumber: '016-2345678',
    type: 'vendor',
    status: 'visiting',
    checkInTime: new Date(today.setHours(10, 0, 0)),
    purposeOfVisit: 'Medical equipment delivery',
    hostName: 'Encik Hassan (Procurement)',
    hostDepartment: 'Pharmacy Sub Store',
    badgeNumber: 'VD-015',
    badgeIssued: true,
    vehicleNumber: 'BGK 9988 K',
    temperatureChecked: true,
    temperature: 36.7,
    healthDeclarationSigned: true,
  },
  {
    id: 'V004',
    name: 'Fatimah binti Ismail',
    icNumber: '950518-14-4567',
    contactNumber: '019-8765432',
    type: 'family',
    status: 'checked-out',
    checkInTime: new Date(today.setHours(7, 45, 0)),
    checkOutTime: new Date(today.setHours(9, 30, 0)),
    purposeOfVisit: 'Visit newborn',
    hostName: 'Nurul Aisyah',
    hostDepartment: 'Maternity Ward',
    hostBedNumber: 'M-08',
    badgeNumber: 'V-002',
    badgeIssued: true,
    temperatureChecked: true,
    temperature: 36.6,
    healthDeclarationSigned: true,
    notes: 'First-time grandmother, very excited!',
  },
  {
    id: 'V005',
    name: 'Dr. Robert Chen',
    icNumber: '720920-10-6789',
    contactNumber: '012-8887766',
    type: 'official',
    status: 'visiting',
    checkInTime: new Date(today.setHours(10, 30, 0)),
    purposeOfVisit: 'Medical audit inspection',
    hostName: 'Dr. Faridah (Medical Director)',
    hostDepartment: 'Office Administration',
    badgeNumber: 'OF-003',
    badgeIssued: true,
    temperatureChecked: true,
    temperature: 36.4,
    healthDeclarationSigned: true,
  },
];

// Mock Appointments
export const mockAppointments: Appointment[] = [
  {
    id: 'APT001',
    appointmentNumber: 'A2025-0001',
    patientName: 'Tan Ah Kow',
    patientIC: '680405-10-1234',
    patientContact: '012-3334444',
    dateOfBirth: new Date('1968-04-05'),
    appointmentDate: today,
    appointmentTime: '09:00',
    estimatedDuration: 30,
    department: 'General Medicine',
    doctor: 'Dr. Lim Wei Ming',
    appointmentType: 'follow-up',
    status: 'completed',
    arrivedAt: new Date(today.setHours(8, 45, 0)),
    checkedInBy: 'Receptionist A',
    queueNumber: 'GM-001',
    calledAt: new Date(today.setHours(9, 5, 0)),
    reasonForVisit: 'Diabetes follow-up',
    isFollowUp: true,
    previousVisitDate: new Date('2024-12-06'),
    reminderSent: true,
    hostNotified: true,
  },
  {
    id: 'APT002',
    appointmentNumber: 'A2025-0002',
    patientName: 'Siti Aminah',
    patientIC: '880612-08-5678',
    patientContact: '013-5556666',
    dateOfBirth: new Date('1988-06-12'),
    appointmentDate: today,
    appointmentTime: '10:30',
    estimatedDuration: 45,
    department: 'Obstetrics',
    doctor: 'Dr. Nora Abdullah',
    appointmentType: 'consultation',
    status: 'in-progress',
    arrivedAt: new Date(today.setHours(10, 20, 0)),
    checkedInBy: 'Receptionist B',
    queueNumber: 'OB-003',
    calledAt: new Date(today.setHours(10, 35, 0)),
    reasonForVisit: 'Prenatal check-up (28 weeks)',
    specialRequirements: 'Wheelchair access',
    isFollowUp: true,
    previousVisitDate: new Date('2024-09-15'),
    reminderSent: true,
    hostNotified: true,
  },
  {
    id: 'APT003',
    appointmentNumber: 'A2025-0003',
    patientName: 'Mohammad Rizal',
    patientIC: '750920-05-2345',
    patientContact: '016-7778888',
    dateOfBirth: new Date('1975-09-20'),
    appointmentDate: today,
    appointmentTime: '11:00',
    estimatedDuration: 30,
    department: 'Cardiology',
    doctor: 'Dr. Kumar Velan',
    appointmentType: 'follow-up',
    status: 'arrived',
    arrivedAt: new Date(today.setHours(10, 50, 0)),
    checkedInBy: 'Receptionist A',
    queueNumber: 'CAR-005',
    reasonForVisit: 'Post-angioplasty review',
    isFollowUp: true,
    previousVisitDate: new Date('2024-11-20'),
    reminderSent: true,
    hostNotified: true,
  },
  {
    id: 'APT004',
    appointmentNumber: 'A2025-0004',
    patientName: 'Lim Siew Hoon',
    patientIC: '920115-12-3456',
    patientContact: '019-4445555',
    dateOfBirth: new Date('1992-01-15'),
    appointmentDate: today,
    appointmentTime: '14:00',
    estimatedDuration: 20,
    department: 'Vaccination Clinic',
    doctor: 'Nurse Azizah',
    appointmentType: 'vaccination',
    status: 'scheduled',
    reasonForVisit: 'COVID-19 booster',
    isFollowUp: false,
    reminderSent: true,
    hostNotified: false,
  },
  {
    id: 'APT005',
    appointmentNumber: 'A2025-0005',
    patientName: 'Ravi Kumar',
    patientIC: '860728-10-4567',
    patientContact: '012-6667777',
    dateOfBirth: new Date('1986-07-28'),
    appointmentDate: today,
    appointmentTime: '15:30',
    estimatedDuration: 60,
    department: 'Orthopedics',
    doctor: 'Dr. Chan Kok Wai',
    appointmentType: 'procedure',
    status: 'scheduled',
    reasonForVisit: 'Knee arthroscopy',
    specialRequirements: 'Fasting required',
    isFollowUp: false,
    reminderSent: true,
    hostNotified: false,
    notes: 'Patient has been fasting since midnight',
  },
  {
    id: 'APT006',
    appointmentNumber: 'A2025-0006',
    patientName: 'Wong Mei Yee',
    patientIC: '700303-08-5678',
    patientContact: '013-8889999',
    dateOfBirth: new Date('1970-03-03'),
    appointmentDate: today,
    appointmentTime: '09:30',
    estimatedDuration: 30,
    department: 'Dermatology',
    doctor: 'Dr. Aisha Rahman',
    appointmentType: 'consultation',
    status: 'no-show',
    reasonForVisit: 'Skin rash evaluation',
    isFollowUp: false,
    reminderSent: true,
    hostNotified: false,
    notes: 'Did not arrive, no contact made',
  },
];

// Mock Queue Entries
export const mockQueueEntries: QueueEntry[] = [
  {
    id: 'Q001',
    queueNumber: 'GM-002',
    patientName: 'Tan Ah Kow',
    appointmentId: 'APT001',
    department: 'General Medicine',
    serviceType: 'Consultation',
    status: 'completed',
    priority: 'normal',
    joinedAt: new Date(today.setHours(8, 45, 0)),
    calledAt: new Date(today.setHours(9, 5, 0)),
    servingAt: new Date(today.setHours(9, 8, 0)),
    completedAt: new Date(today.setHours(9, 35, 0)),
    estimatedWaitTime: 0,
    currentlyServing: 'Room 3',
  },
  {
    id: 'Q002',
    queueNumber: 'OB-003',
    patientName: 'Siti Aminah',
    appointmentId: 'APT002',
    department: 'Obstetrics',
    serviceType: 'Prenatal Check',
    status: 'serving',
    priority: 'normal',
    joinedAt: new Date(today.setHours(10, 20, 0)),
    calledAt: new Date(today.setHours(10, 35, 0)),
    servingAt: new Date(today.setHours(10, 38, 0)),
    estimatedWaitTime: 0,
    currentlyServing: 'Room 7',
  },
  {
    id: 'Q003',
    queueNumber: 'CAR-005',
    patientName: 'Mohammad Rizal',
    appointmentId: 'APT003',
    department: 'Cardiology',
    serviceType: 'Follow-up',
    status: 'called',
    priority: 'normal',
    joinedAt: new Date(today.setHours(10, 50, 0)),
    calledAt: new Date(today.setHours(11, 5, 0)),
    estimatedWaitTime: 5,
    currentlyServing: 'Room 12',
  },
  {
    id: 'Q004',
    queueNumber: 'EM-015',
    patientName: 'Ali bin Hassan (Walk-in)',
    department: 'Emergency',
    serviceType: 'Emergency',
    status: 'serving',
    priority: 'urgent',
    joinedAt: new Date(today.setHours(10, 55, 0)),
    calledAt: new Date(today.setHours(10, 56, 0)),
    servingAt: new Date(today.setHours(10, 57, 0)),
    estimatedWaitTime: 0,
    currentlyServing: 'Triage Room',
    notes: 'Chest pain, priority assessment',
  },
  {
    id: 'Q005',
    queueNumber: 'PH-008',
    patientName: 'Letchumi Devi (Walk-in)',
    department: 'Pharmacy Counter',
    serviceType: 'Medication Collection',
    status: 'waiting',
    priority: 'normal',
    joinedAt: new Date(today.setHours(11, 0, 0)),
    estimatedWaitTime: 15,
  },
  {
    id: 'Q006',
    queueNumber: 'LAB-012',
    patientName: 'Chen Wei Jun (Walk-in)',
    department: 'Laboratory',
    serviceType: 'Blood Test',
    status: 'waiting',
    priority: 'normal',
    joinedAt: new Date(today.setHours(11, 10, 0)),
    estimatedWaitTime: 25,
  },
];

// Mock Counters
export const mockCounters: Counter[] = [
  {
    id: 'C001',
    counterNumber: 'Counter 1',
    status: 'open',
    staffName: 'Receptionist A - Aisha',
    currentPatient: 'Mohammad Rizal',
    servicesOffered: ['Registration', 'Appointment', 'General Inquiry'],
  },
  {
    id: 'C002',
    counterNumber: 'Counter 2',
    status: 'open',
    staffName: 'Receptionist B - Nurul',
    servicesOffered: ['Registration', 'Appointment', 'Payment'],
  },
  {
    id: 'C003',
    counterNumber: 'Counter 3',
    status: 'busy',
    staffName: 'Receptionist C - Lee',
    currentPatient: 'Tan Ah Meng',
    servicesOffered: ['Payment', 'Document Collection'],
  },
  {
    id: 'C004',
    counterNumber: 'Counter 4',
    status: 'closed',
    servicesOffered: ['Break/Closed'],
  },
];

// Mock Stats
export const mockFrontDeskStats: FrontDeskStats = {
  totalVisitorsToday: 87,
  currentVisitors: 23,
  checkedOutVisitors: 64,
  
  totalAppointmentsToday: 124,
  completedAppointments: 45,
  pendingAppointments: 68,
  noShows: 11,
  
  currentQueueSize: 34,
  averageWaitTime: 18,
  longestWaitTime: 45,
  
  newRegistrationsToday: 12,
  
  peakHour: '09:00 - 10:00',
  occupancyRate: 78,
};

// Mock Patient Registration (recent)
export const mockRecentRegistrations: PatientRegistration[] = [
  {
    id: 'REG001',
    registrationNumber: 'R2025-00145',
    registrationDate: today,
    name: 'Nurul Izzah binti Kamal',
    icNumber: '950824-08-3456',
    dateOfBirth: new Date('1995-08-24'),
    age: 29,
    gender: 'Female',
    address: 'No. 45, Jalan Bunga Raya 3/2',
    city: 'Kuala Lumpur',
    state: 'Wilayah Persekutuan',
    postcode: '50300',
    contactNumber: '011-22334455',
    email: 'nurulizzah@email.com',
    emergencyContactName: 'Kamal bin Ahmad (Father)',
    emergencyContactRelation: 'Father',
    emergencyContactNumber: '012-66778899',
    bloodType: 'O+',
    allergies: ['Penicillin'],
    chronicConditions: [],
    currentMedications: [],
    hasInsurance: true,
    insuranceProvider: 'Great Eastern',
    insurancePolicyNumber: 'GE-2024-556789',
    consentForTreatment: true,
    consentForDataSharing: true,
    consentDate: today,
    registeredBy: 'Receptionist A',
    status: 'active',
  },
  {
    id: 'REG002',
    registrationNumber: 'R2025-00146',
    registrationDate: today,
    name: 'Lim Wei Jian',
    icNumber: '001215-10-4567',
    dateOfBirth: new Date('2000-12-15'),
    age: 24,
    gender: 'Male',
    address: 'Blok C-15-08, Pangsapuri Cemerlang',
    city: 'Petaling Jaya',
    state: 'Selangor',
    postcode: '46200',
    contactNumber: '017-99887766',
    emergencyContactName: 'Lim Ah Chong (Father)',
    emergencyContactRelation: 'Father',
    emergencyContactNumber: '016-88776655',
    allergies: [],
    chronicConditions: ['Asthma'],
    currentMedications: ['Ventolin inhaler'],
    hasInsurance: false,
    consentForTreatment: true,
    consentForDataSharing: false,
    consentDate: today,
    registeredBy: 'Receptionist B',
    status: 'pending',
  },
];

export function getTodaysVisitors(): Visitor[] {
  return mockVisitors;
}

export function getTodaysAppointments(): Appointment[] {
  return mockAppointments;
}

export function getCurrentQueue(): QueueEntry[] {
  return mockQueueEntries;
}

export function getCounterStatus(): Counter[] {
  return mockCounters;
}

export function getFrontDeskStats(): FrontDeskStats {
  return mockFrontDeskStats;
}

export function getRecentRegistrations(): PatientRegistration[] {
  return mockRecentRegistrations;
}







