import type { Supplier, SupplierStats } from '../types/Supplier';

export const suppliers: Supplier[] = [
  {
    id: 'supplier-001',
    companyName: 'Pharmaniaga Berhad',
    address: 'No. 7, Lorong Keluli 1B, Kawasan Perindustrian Bukit Raja Selatan, 40000 Shah Alam, Selangor',
    email: 'info@pharmaniaga.com.my',
    phone: '+60 3-3342 9999',
    category: 'Pharmaceutical',
    status: 'Active',
    rating: 4.8,
    lastContact: '2024-11-15',
    totalOrders: 156,
    totalValue: 2450000,
    specialties: ['Generic Medicines', 'Vaccines', 'Pharmaceutical Distribution'],
    website: 'www.pharmaniaga.com.my',
    contactPerson: 'Ahmad Rahman',
    createdAt: '2024-01-01',
    updatedAt: '2024-12-01'
  },
  {
    id: 'supplier-002',
    companyName: 'Zuellig Pharma Sdn Bhd',
    address: 'B-11-01, The Ascent, Paradigm, No. 1 Jalan SS7/26A, Kelana Jaya, 47301 Petaling Jaya, Selangor',
    email: 'procurementsustainability@zuelligpharma.com',
    phone: '+60 3-5566 2288',
    category: 'Pharmaceutical',
    status: 'Active',
    rating: 4.6,
    lastContact: '2024-11-20',
    totalOrders: 89,
    totalValue: 1890000,
    specialties: ['Specialty Medicines', 'Oncology', 'Rare Diseases'],
    website: 'www.zuelligpharma.com',
    contactPerson: 'Sarah Lim',
    createdAt: '2024-01-15',
    updatedAt: '2024-12-01'
  },
  {
    id: 'supplier-003',
    companyName: 'DKSH Malaysia Sdn Bhd (Healthcare)',
    address: 'Level 8, Menara LGB, 1 Jalan Wan Kadir, Taman Tun Dr Ismail, 60000 Kuala Lumpur',
    email: 'healthcare@dksh.com.my',
    phone: '+60 3-2692 8888',
    category: 'Medical Equipment',
    status: 'Active',
    rating: 4.7,
    lastContact: '2024-11-18',
    totalOrders: 203,
    totalValue: 3200000,
    specialties: ['Medical Devices', 'Diagnostic Equipment', 'Surgical Instruments'],
    website: 'www.dksh.com.my',
    contactPerson: 'Dr. Raj Kumar',
    createdAt: '2024-02-01',
    updatedAt: '2024-12-01'
  },
  {
    id: 'supplier-004',
    companyName: 'Abbott Laboratories (M) Sdn Bhd',
    address: 'No. 1, Jalan Teknologi 3/6, Kota Damansara, 47810 Petaling Jaya, Selangor',
    email: 'malaysia@abbott.com',
    phone: '+60 3-7831 6000',
    category: 'Pharmaceutical',
    status: 'Active',
    rating: 4.9,
    lastContact: '2024-11-25',
    totalOrders: 134,
    totalValue: 2100000,
    specialties: ['Nutrition', 'Diagnostics', 'Medical Devices'],
    website: 'www.abbott.com.my',
    contactPerson: 'Jennifer Tan',
    createdAt: '2024-01-20',
    updatedAt: '2024-12-01'
  },
  {
    id: 'supplier-005',
    companyName: 'Roche (Malaysia) Sdn Bhd',
    address: 'Level 20, Menara IGB, Mid Valley City, Lingkaran Syed Putra, 59200 Kuala Lumpur',
    email: 'malaysia@roche.com',
    phone: '+60 3-2299 1888',
    category: 'Pharmaceutical',
    status: 'Active',
    rating: 4.8,
    lastContact: '2024-11-22',
    totalOrders: 67,
    totalValue: 1800000,
    specialties: ['Oncology', 'Diagnostics', 'Personalized Healthcare'],
    website: 'www.roche.com.my',
    contactPerson: 'Dr. Michael Chen',
    createdAt: '2024-02-10',
    updatedAt: '2024-12-01'
  },
  {
    id: 'supplier-006',
    companyName: 'Duopharma Biotech Sdn Bhd',
    address: 'Lot 2593, Jalan Teknologi 3/4, Taman Sains Selangor 1, Kota Damansara, 47810 Petaling Jaya, Selangor',
    email: 'cs@duopharmabiotech.com',
    phone: '+60 3-7831 2000',
    category: 'Pharmaceutical',
    status: 'Active',
    rating: 4.5,
    lastContact: '2024-11-16',
    totalOrders: 98,
    totalValue: 1650000,
    specialties: ['Biotechnology', 'Generic Medicines', 'Contract Manufacturing'],
    website: 'www.duopharmabiotech.com',
    contactPerson: 'Ahmad Fauzi',
    createdAt: '2024-01-25',
    updatedAt: '2024-12-01'
  },
  {
    id: 'supplier-007',
    companyName: 'LKL International Berhad',
    address: 'No. 1, Jalan Teknologi 3/6, Kota Damansara, 47810 Petaling Jaya, Selangor',
    email: 'info@lklbeds.com',
    phone: '+60 3-7831 3000',
    category: 'Medical Equipment',
    status: 'Active',
    rating: 4.3,
    lastContact: '2024-11-19',
    totalOrders: 45,
    totalValue: 890000,
    specialties: ['Hospital Beds', 'Medical Furniture', 'Healthcare Equipment'],
    website: 'www.lklbeds.com',
    contactPerson: 'Lim Siew Choo',
    createdAt: '2024-02-05',
    updatedAt: '2024-12-01'
  },
  {
    id: 'supplier-008',
    companyName: 'Borneo Indah Sdn Bhd',
    address: 'Lot 1234, Jalan Industri 3, Kawasan Perindustrian Senai, 81400 Senai, Johor',
    email: 'kch@borneoindah.com.my',
    phone: '+60 6-336 2222',
    category: 'Healthcare Services',
    status: 'Active',
    rating: 4.4,
    lastContact: '2024-11-17',
    totalOrders: 76,
    totalValue: 1200000,
    specialties: ['Medical Supplies', 'Laboratory Equipment', 'Healthcare Services'],
    website: 'www.borneoindah.com.my',
    contactPerson: 'Khor Chee Heng',
    createdAt: '2024-01-30',
    updatedAt: '2024-12-01'
  },
  {
    id: 'supplier-009',
    companyName: 'Top Glove Corporation Berhad',
    address: 'Top Glove Tower, 16, Persiaran Setia Dagang, Setia Alam, Seksyen U13, 40170 Shah Alam, Selangor',
    email: 'info@topglove.com',
    phone: '+60 3-3366 8888',
    category: 'Medical Equipment',
    status: 'Active',
    rating: 4.6,
    lastContact: '2024-11-21',
    totalOrders: 234,
    totalValue: 2800000,
    specialties: ['Medical Gloves', 'Protective Equipment', 'Healthcare Products'],
    website: 'www.topglove.com',
    contactPerson: 'Tan Sri Lim Wee Chai',
    createdAt: '2024-01-10',
    updatedAt: '2024-12-01'
  },
  {
    id: 'supplier-010',
    companyName: 'Hartalega Holdings Berhad',
    address: 'No. 1, Jalan Teknologi 3/6, Kota Damansara, 47810 Petaling Jaya, Selangor',
    email: 'info@hartalega.com.my',
    phone: '+60 3-7831 4000',
    category: 'Medical Equipment',
    status: 'Active',
    rating: 4.7,
    lastContact: '2024-11-23',
    totalOrders: 189,
    totalValue: 2200000,
    specialties: ['Nitrile Gloves', 'Medical Gloves', 'Protective Equipment'],
    website: 'www.hartalega.com.my',
    contactPerson: 'Kuan Mun Leong',
    createdAt: '2024-01-12',
    updatedAt: '2024-12-01'
  },
  {
    id: 'supplier-011',
    companyName: 'Sime Darby Healthcare',
    address: 'Level 2, Wisma Sime Darby, Jalan Sultan Ismail, 50250 Kuala Lumpur',
    email: 'healthcare@sime darby.com',
    phone: '+60 3-2050 8888',
    category: 'Healthcare Services',
    status: 'Active',
    rating: 4.5,
    lastContact: '2024-11-14',
    totalOrders: 112,
    totalValue: 1950000,
    specialties: ['Healthcare Services', 'Medical Equipment', 'Pharmaceutical Distribution'],
    website: 'www.simedarby.com',
    contactPerson: 'Dr. Norazman',
    createdAt: '2024-02-15',
    updatedAt: '2024-12-01'
  },
  {
    id: 'supplier-012',
    companyName: 'KPJ Healthcare Berhad',
    address: 'Level 9, Menara KPJ, No. 2, Jalan Teknologi 3/6, Kota Damansara, 47810 Petaling Jaya, Selangor',
    email: 'info@kpjhealthcare.com.my',
    phone: '+60 3-7831 5000',
    category: 'Healthcare Services',
    status: 'Active',
    rating: 4.8,
    lastContact: '2024-11-26',
    totalOrders: 78,
    totalValue: 1450000,
    specialties: ['Hospital Services', 'Medical Equipment', 'Healthcare Technology'],
    website: 'www.kpjhealthcare.com.my',
    contactPerson: 'Ahmad Zahid',
    createdAt: '2024-01-18',
    updatedAt: '2024-12-01'
  },
  {
    id: 'supplier-013',
    companyName: 'Sunway Medical Centre',
    address: '5, Jalan Lagoon Selatan, Bandar Sunway, 47500 Subang Jaya, Selangor',
    email: 'info@sunwaymedical.com',
    phone: '+60 3-7491 9191',
    category: 'Healthcare Services',
    status: 'Active',
    rating: 4.9,
    lastContact: '2024-11-24',
    totalOrders: 56,
    totalValue: 1100000,
    specialties: ['Medical Services', 'Diagnostic Equipment', 'Specialized Care'],
    website: 'www.sunwaymedical.com',
    contactPerson: 'Dr. Suresh',
    createdAt: '2024-02-20',
    updatedAt: '2024-12-01'
  },
  {
    id: 'supplier-014',
    companyName: 'Gleneagles Kuala Lumpur',
    address: '282 & 286, Jalan Ampang, 50450 Kuala Lumpur',
    email: 'info@gleneagleskl.com.my',
    phone: '+60 3-4141 3000',
    category: 'Healthcare Services',
    status: 'Active',
    rating: 4.7,
    lastContact: '2024-11-13',
    totalOrders: 43,
    totalValue: 980000,
    specialties: ['Hospital Services', 'Medical Equipment', 'Specialized Treatments'],
    website: 'www.gleneagleskl.com.my',
    contactPerson: 'Dr. Lim',
    createdAt: '2024-01-28',
    updatedAt: '2024-12-01'
  },
  {
    id: 'supplier-015',
    companyName: 'Pantai Holdings Berhad',
    address: 'Level 9, Menara Pantai, No. 1, Jalan Bukit Pantai, 59200 Kuala Lumpur',
    email: 'info@pantai.com.my',
    phone: '+60 3-2299 1888',
    category: 'Healthcare Services',
    status: 'Active',
    rating: 4.6,
    lastContact: '2024-11-27',
    totalOrders: 91,
    totalValue: 1750000,
    specialties: ['Hospital Services', 'Medical Equipment', 'Healthcare Management'],
    website: 'www.pantai.com.my',
    contactPerson: 'Dr. Azman',
    createdAt: '2024-02-08',
    updatedAt: '2024-12-01'
  }
];

export function getSuppliers(): Supplier[] {
  return suppliers;
}

export function getSupplierStats(): SupplierStats {
  const totalSuppliers = suppliers.length;
  const activeSuppliers = suppliers.filter(s => s.status === 'Active').length;
  const pendingSuppliers = suppliers.filter(s => s.status === 'Pending').length;
  const averageRating = suppliers.reduce((sum, s) => sum + s.rating, 0) / totalSuppliers;
  const totalValue = suppliers.reduce((sum, s) => sum + s.totalValue, 0);

  return {
    totalSuppliers,
    activeSuppliers,
    pendingSuppliers,
    averageRating: Math.round(averageRating * 10) / 10,
    totalValue
  };
}
